// SINH TỰ ĐỘNG bởi `pnpm codegen` từ OpenAPI của Django Ninja.
// KHÔNG SỬA TAY — mọi thay đổi sẽ mất ở lần codegen kế tiếp.
// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { QuanTriBanNguoiDungData, QuanTriBanNguoiDungErrors, QuanTriBanNguoiDungResponses, QuanTriDatAnBinhLuanData, QuanTriDatAnBinhLuanErrors, QuanTriDatAnBinhLuanResponses, QuanTriDatAnMachData, QuanTriDatAnMachErrors, QuanTriDatAnMachResponses, QuanTriDatAnMocData, QuanTriDatAnMocErrors, QuanTriDatAnMocResponses, QuanTriDatKhoaMachData, QuanTriDatKhoaMachErrors, QuanTriDatKhoaMachResponses, QuanTriDongBaoCaoData, QuanTriDongBaoCaoErrors, QuanTriDongBaoCaoResponses, QuanTriGoBanNguoiDungData, QuanTriGoBanNguoiDungErrors, QuanTriGoBanNguoiDungResponses, QuanTriLietKeBaoCaoData, QuanTriLietKeBaoCaoErrors, QuanTriLietKeBaoCaoResponses, QuanTriLietKeNhatKyData, QuanTriLietKeNhatKyErrors, QuanTriLietKeNhatKyResponses, QuanTriLietKeSubData, QuanTriLietKeSubErrors, QuanTriLietKeSubResponses, QuanTriSuaSubData, QuanTriSuaSubErrors, QuanTriSuaSubResponses, QuanTriTaoSubData, QuanTriTaoSubErrors, QuanTriTaoSubResponses, QuanTriToiData, QuanTriToiErrors, QuanTriToiResponses, QuanTriXemMachData, QuanTriXemMachErrors, QuanTriXemMachResponses, QuanTriXemNguoiDungData, QuanTriXemNguoiDungErrors, QuanTriXemNguoiDungResponses, QuanTriXoaSubData, QuanTriXoaSubErrors, QuanTriXoaSubResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Dat An Binh Luan Endpoint
 *
 * Mod ẩn / gỡ ẩn một bình luận. Idempotent.
 *
 * Gỡ ẩn **không** hồi sinh bình luận mà tác giả đã tự xoá — `deleted_at` là trục khác
 * và endpoint này không chạm tới nó.
 */
export const quanTriDatAnBinhLuan = <ThrowOnError extends boolean = false>(options: Options<QuanTriDatAnBinhLuanData, ThrowOnError>): RequestResult<QuanTriDatAnBinhLuanResponses, QuanTriDatAnBinhLuanErrors, ThrowOnError> => (options.client ?? client).post<QuanTriDatAnBinhLuanResponses, QuanTriDatAnBinhLuanErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/admin/comments/{comment_id}/an',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Xem Mach
 *
 * Trang chi tiết một mạch cho mod (PLAN 9.3 mục 2) — mọi mốc, kể cả ẩn và bia mộ.
 *
 * Trả **cả** mốc đã bị ẩn và bia mộ, kèm trích yếu nội dung: mod cần đọc để quyết gỡ ẩn.
 * Đó là chuyện khu này được phép làm mà `GET /api/v1/machs/{id}` thì không — xem
 * docstring `api/quan_tri_schemas.py`.
 *
 * Số truy vấn là HẰNG SỐ (mạch + mốc kèm tác giả), không phụ thuộc số mốc.
 */
export const quanTriXemMach = <ThrowOnError extends boolean = false>(options: Options<QuanTriXemMachData, ThrowOnError>): RequestResult<QuanTriXemMachResponses, QuanTriXemMachErrors, ThrowOnError> => (options.client ?? client).get<QuanTriXemMachResponses, QuanTriXemMachErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/admin/machs/{mach_id}',
    ...options
});

/**
 * Dat An Mach Endpoint
 *
 * Mod ẩn / gỡ ẩn cả mạch. Idempotent.
 *
 * Mạch bị ẩn biến mất khỏi hai feed, khỏi trang sub, khỏi hồ sơ tác giả và khỏi
 * `sitemap`; `GET /machs/{id}` công khai trả 404. Nó **không** đổi con số denormalize
 * nào của chính nó — xem `core/ghi.py::dat_an_mach`.
 */
export const quanTriDatAnMach = <ThrowOnError extends boolean = false>(options: Options<QuanTriDatAnMachData, ThrowOnError>): RequestResult<QuanTriDatAnMachResponses, QuanTriDatAnMachErrors, ThrowOnError> => (options.client ?? client).post<QuanTriDatAnMachResponses, QuanTriDatAnMachErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/admin/machs/{mach_id}/an',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Dat Khoa Mach Endpoint
 *
 * Mod khoá / mở khoá một mạch: đọc được, cấm mọi tương tác (PLAN 5.10). Idempotent.
 *
 * **Trục riêng, khác "đóng sổ" của tác giả.** Endpoint này không đụng `status`, nên
 * "mạch đã đóng bị mod khoá" vẫn diễn đạt được. Mạch bị khoá luôn ở mặt CẶN.
 */
export const quanTriDatKhoaMach = <ThrowOnError extends boolean = false>(options: Options<QuanTriDatKhoaMachData, ThrowOnError>): RequestResult<QuanTriDatKhoaMachResponses, QuanTriDatKhoaMachErrors, ThrowOnError> => (options.client ?? client).post<QuanTriDatKhoaMachResponses, QuanTriDatKhoaMachErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/admin/machs/{mach_id}/khoa',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Toi
 *
 * Mod đang đăng nhập là ai. Trả 401 nếu chưa đăng nhập, 403 nếu không phải staff.
 *
 * Đây cũng là endpoint **gieo cookie CSRF** cho khu quản trị: app admin gọi nó khi mở
 * trang, rồi mọi request ghi sau đó gửi kèm `X-CSRFToken` đọc từ cookie ấy.
 */
export const quanTriToi = <ThrowOnError extends boolean = false>(options?: Options<QuanTriToiData, ThrowOnError>): RequestResult<QuanTriToiResponses, QuanTriToiErrors, ThrowOnError> => (options?.client ?? client).get<QuanTriToiResponses, QuanTriToiErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/admin/me',
    ...options
});

/**
 * Dat An Moc Endpoint
 *
 * Mod ẩn / gỡ ẩn một mốc. Idempotent — gửi hai lần cho cùng trạng thái.
 *
 * Mốc bị ẩn **vẫn giữ ô trên spine** kèm nhãn "mốc đã bị ẩn" (PLAN 5.2): `seq` bất biến
 * nên `entry_count` không lùi. Đổi lại, `comment_count`, `last_activity_at` và
 * `diem_bai_goc` (khi đây là mốc 1) được tính lại trong cùng transaction.
 */
export const quanTriDatAnMoc = <ThrowOnError extends boolean = false>(options: Options<QuanTriDatAnMocData, ThrowOnError>): RequestResult<QuanTriDatAnMocResponses, QuanTriDatAnMocErrors, ThrowOnError> => (options.client ?? client).post<QuanTriDatAnMocResponses, QuanTriDatAnMocErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/admin/mocs/{moc_id}/an',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Liet Ke Nhat Ky
 *
 * Nhật ký mod, mới nhất trước, cursor keyset `(created_at, id)`.
 *
 * `?action=` lọc theo một hằng hành động (`an_moc`, `ban_user`, …) — so **bằng đúng**
 * chứ không `icontains`: `an_moc` và `go_an_moc` chỉ khác nhau một tiền tố, nên phép so
 * khớp một phần sẽ trả cả hai và mod đọc lịch sử ẩn thành lịch sử gỡ ẩn.
 *
 * Cố ý **không** khai `action` bằng `Literal`: danh sách hằng nằm ở `core/ghi.py` và nó
 * dài thêm mỗi lần có hành động mới, trong khi các dòng log CŨ mang những chuỗi có thể
 * đã bị gỡ khỏi danh sách. Một `enum` ở đây sẽ từ chối lọc đúng những dòng lịch sử mà
 * trang này tồn tại để tra. Giá trị lạ ⇒ trang rỗng, không phải 400.
 */
export const quanTriLietKeNhatKy = <ThrowOnError extends boolean = false>(options?: Options<QuanTriLietKeNhatKyData, ThrowOnError>): RequestResult<QuanTriLietKeNhatKyResponses, QuanTriLietKeNhatKyErrors, ThrowOnError> => (options?.client ?? client).get<QuanTriLietKeNhatKyResponses, QuanTriLietKeNhatKyErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/admin/nhat-ky',
    ...options
});

/**
 * Liet Ke Bao Cao
 *
 * Hàng đợi báo cáo, mới nhất trước, cursor keyset `(created_at, id)`.
 *
 * Mặc định `trang_thai=cho_xu_ly` — đó là việc của mod. `da_xu_ly` và `tat_ca` có mặt để
 * tra lại một quyết định cũ. Giá trị lạ trả **400 `tham_so_khong_hop_le`** (mã mặc định,
 * cố ý — xem `tests/test_hop_dong_openapi.py::CO_Y_DUNG_MA_MAC_DINH`).
 *
 * Mỗi dòng kèm `dich`: loại, mạch chứa nó, tác giả, trích yếu nội dung và đường dẫn công
 * khai. `dich` là `null` khi thứ bị tố không còn tồn tại — báo cáo vẫn ở lại hàng đợi.
 */
export const quanTriLietKeBaoCao = <ThrowOnError extends boolean = false>(options?: Options<QuanTriLietKeBaoCaoData, ThrowOnError>): RequestResult<QuanTriLietKeBaoCaoResponses, QuanTriLietKeBaoCaoErrors, ThrowOnError> => (options?.client ?? client).get<QuanTriLietKeBaoCaoResponses, QuanTriLietKeBaoCaoErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/admin/reports',
    ...options
});

/**
 * Dong Bao Cao Endpoint
 *
 * Đóng một báo cáo, ghi lại mod đã làm gì. Idempotent — đóng lần hai trả `da_doi=false`.
 *
 * **`hanh_dong` chỉ được GHI LẠI, nó không tự thi hành gì.** Đóng với `hanh_dong="an"`
 * mà chưa ai bấm ẩn thì nội dung vẫn hiện; ẩn là một lời gọi riêng tới
 * `POST /mocs/{id}/an`. Gộp hai việc là dựng một đường ghi thứ hai tới `hidden_at` nằm
 * ngoài `core/ghi.py::dat_an_*` — xem docstring `core/ghi.py::dong_bao_cao`.
 */
export const quanTriDongBaoCao = <ThrowOnError extends boolean = false>(options: Options<QuanTriDongBaoCaoData, ThrowOnError>): RequestResult<QuanTriDongBaoCaoResponses, QuanTriDongBaoCaoErrors, ThrowOnError> => (options.client ?? client).post<QuanTriDongBaoCaoResponses, QuanTriDongBaoCaoErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/admin/reports/{report_id}/dong',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Liet Ke Sub
 *
 * Mọi sub, sắp theo `slug`, kèm `so_mach`.
 *
 * Không phân trang: v1 có hai sub và danh sách này là bảng điều khiển, không phải feed.
 * Ngày nào nó dài tới mức cần cursor thì `so_mach` sẽ là thứ vỡ trước (một `COUNT` mỗi
 * hàng), và lúc đó phải sửa cả hai thứ cùng lúc.
 */
export const quanTriLietKeSub = <ThrowOnError extends boolean = false>(options?: Options<QuanTriLietKeSubData, ThrowOnError>): RequestResult<QuanTriLietKeSubResponses, QuanTriLietKeSubErrors, ThrowOnError> => (options?.client ?? client).get<QuanTriLietKeSubResponses, QuanTriLietKeSubErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/admin/subs',
    ...options
});

/**
 * Tao Sub
 *
 * Tạo một chuyên mục mới. 409 `xung_dot` nếu `slug` đã có.
 *
 * `slug` phải đã ở dạng chuẩn — server **không** tự slugify hộ. Tự sửa hộ nghĩa là người
 * gõ `Chứng Khoán` nhận về `/s/chung-khoan` mà không biết, rồi lần sau gõ lại đúng chuỗi
 * ấy và ăn 409 cho một sub họ tưởng chưa tạo.
 */
export const quanTriTaoSub = <ThrowOnError extends boolean = false>(options: Options<QuanTriTaoSubData, ThrowOnError>): RequestResult<QuanTriTaoSubResponses, QuanTriTaoSubErrors, ThrowOnError> => (options.client ?? client).post<QuanTriTaoSubResponses, QuanTriTaoSubErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/admin/subs',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Xoa Sub
 *
 * Xoá một chuyên mục. 409 `xung_dot` nếu nó còn mạch.
 *
 * Xoá THẬT, không xoá mềm: `Sub` không có nội dung của ai và không có URL nào cần giữ
 * bia mộ. Điều kiện "rỗng" là thứ giữ cho việc đó an toàn — và nó được `PROTECT` ở tầng
 * DB canh lần thứ hai (xem docstring module).
 */
export const quanTriXoaSub = <ThrowOnError extends boolean = false>(options: Options<QuanTriXoaSubData, ThrowOnError>): RequestResult<QuanTriXoaSubResponses, QuanTriXoaSubErrors, ThrowOnError> => (options.client ?? client).delete<QuanTriXoaSubResponses, QuanTriXoaSubErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/admin/subs/{slug}',
    ...options
});

/**
 * Sua Sub
 *
 * Sửa `ten` / `mo_ta`. Trường `None` là **không đổi**; `slug` không sửa được.
 *
 * Không có nhánh "không đổi gì thì bỏ qua": `PATCH` rỗng vẫn trả 200 với trạng thái hiện
 * hành, nhưng **không** ghi `AuditLog` — cùng luật với `da_doi` của các endpoint kiểm
 * duyệt, xem `core/ghi.py`.
 */
export const quanTriSuaSub = <ThrowOnError extends boolean = false>(options: Options<QuanTriSuaSubData, ThrowOnError>): RequestResult<QuanTriSuaSubResponses, QuanTriSuaSubErrors, ThrowOnError> => (options.client ?? client).patch<QuanTriSuaSubResponses, QuanTriSuaSubErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/admin/subs/{slug}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Xem Nguoi Dung
 *
 * Hồ sơ một tài khoản dưới góc nhìn mod: trạng thái ban + số mạch + số bình luận.
 *
 * `dang_bi_ban` là **kết quả đã tính** của ba cột ban (`User.dang_bi_ban`), không phải
 * một cột thứ tư. Frontend đọc nó thay vì tự dựng lại điều kiện — bản chép tay thứ hai
 * của điều kiện ấy sẽ quên rằng ban tạm tự hết hạn.
 */
export const quanTriXemNguoiDung = <ThrowOnError extends boolean = false>(options: Options<QuanTriXemNguoiDungData, ThrowOnError>): RequestResult<QuanTriXemNguoiDungResponses, QuanTriXemNguoiDungErrors, ThrowOnError> => (options.client ?? client).get<QuanTriXemNguoiDungResponses, QuanTriXemNguoiDungErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/admin/users/{username}',
    ...options
});

/**
 * Ban Nguoi Dung
 *
 * Ban một tài khoản: vĩnh viễn, hoặc tạm tới `den_khi`. **Đúng một trong hai.**
 *
 * `ly_do` bắt buộc và không được rỗng — PLAN 5.10 nói người bị chặn phải đọc được nó.
 *
 * 409 `xung_dot` khi đích là chính mình hoặc là một mod khác (xem docstring module).
 * 400 `tham_so_khong_hop_le` khi vừa `vinh_vien` vừa có `den_khi`, hoặc không có cái nào.
 */
export const quanTriBanNguoiDung = <ThrowOnError extends boolean = false>(options: Options<QuanTriBanNguoiDungData, ThrowOnError>): RequestResult<QuanTriBanNguoiDungResponses, QuanTriBanNguoiDungErrors, ThrowOnError> => (options.client ?? client).post<QuanTriBanNguoiDungResponses, QuanTriBanNguoiDungErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/admin/users/{username}/ban',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Go Ban Nguoi Dung
 *
 * Gỡ ban. Idempotent — gỡ một tài khoản không bị ban trả `da_doi=false`.
 *
 * Không có hai luật của `ban`: gỡ ban cho chính mình hay cho một mod khác đều vô hại
 * (nó chỉ mở khoá), và chặn nó chỉ tạo ra một trạng thái không ai gỡ được.
 */
export const quanTriGoBanNguoiDung = <ThrowOnError extends boolean = false>(options: Options<QuanTriGoBanNguoiDungData, ThrowOnError>): RequestResult<QuanTriGoBanNguoiDungResponses, QuanTriGoBanNguoiDungErrors, ThrowOnError> => (options.client ?? client).post<QuanTriGoBanNguoiDungResponses, QuanTriGoBanNguoiDungErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/admin/users/{username}/go-ban',
    ...options
});
