// SINH TỰ ĐỘNG bởi `pnpm codegen` từ OpenAPI của Django Ninja.
// KHÔNG SỬA TAY — mọi thay đổi sẽ mất ở lần codegen kế tiếp.
// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

/**
 * BanIn
 *
 * Body của `POST /users/{username}/ban`.
 *
 * `vinh_vien`, `den_khi` và `so_ngay` **loại trừ nhau**: đúng một trong ba.
 * `core/ghi.py::ban_user` là chỗ ném lỗi cho cặp `vinh_vien`/`den_khi`, không phải
 * pydantic — luật ấy thuộc đường ghi, và nó phải đúng cả khi ai đó gọi hàm từ
 * `manage.py shell`. `so_ngay` thì **không** xuống tới đường ghi: nó được quy đổi thành
 * `den_khi` ở tầng API (`api/quan_tri_nguoi_dung.py`), nên `ban_user` vẫn chỉ biết đúng
 * hai kiểu ban và bất biến của nó không rộng ra.
 */
export type BanIn = {
    /**
     * Den Khi
     */
    den_khi?: string | null;
    /**
     * Ly Do
     */
    ly_do: string;
    /**
     * So Ngay
     */
    so_ngay?: number | null;
    /**
     * Vinh Vien
     */
    vinh_vien?: boolean;
};

/**
 * BaoCaoOut
 *
 * Một dòng trong hàng đợi báo cáo (PLAN 5.10).
 */
export type BaoCaoOut = {
    /**
     * Action
     */
    action: string | null;
    /**
     * Created At
     */
    created_at: string;
    dich: NoiDungBiBaoCaoOut | null;
    /**
     * Ghi Chu
     */
    ghi_chu: string;
    /**
     * Id
     */
    id: number;
    /**
     * Ly Do
     */
    ly_do: 'phim_hang' | 'lua_dao' | 'spam' | 'khac';
    reporter: NguoiDungTomTatOut;
    /**
     * Resolved At
     */
    resolved_at: string | null;
    resolved_by: NguoiDungTomTatOut | null;
};

/**
 * DatAnIn
 *
 * Body của mọi endpoint ẩn/gỡ ẩn.
 *
 * **Một endpoint đặt-trạng-thái thay vì hai endpoint `hide`/`unhide`** — hai chiều nhận
 * cùng bộ đầu vào, nên tách ra chỉ nhân đôi số chỗ phải kiểm quyền. Và nó **idempotent**:
 * gửi `an=true` hai lần cho ra cùng một trạng thái.
 */
export type DatAnIn = {
    /**
     * An
     */
    an: boolean;
    /**
     * Ly Do
     */
    ly_do?: string;
};

/**
 * DatKhoaMachIn
 *
 * Body của `POST /machs/{id}/khoa`.
 *
 * `khoa` là **trục riêng, không phải `status`** (PLAN 5.10, docstring `Mach`): mạch bị
 * khoá vẫn đọc được nhưng cấm mọi tương tác, còn `closed` là tác giả tự đóng sổ.
 */
export type DatKhoaMachIn = {
    /**
     * Khoa
     */
    khoa: boolean;
    /**
     * Ly Do
     */
    ly_do?: string;
};

/**
 * DongBaoCaoIn
 *
 * Body của `POST /reports/{id}/dong`.
 */
export type DongBaoCaoIn = {
    /**
     * Hanh Dong
     */
    hanh_dong: 'an' | 'khoa' | 'ban' | 'bo_qua';
};

/**
 * KetQuaDoiTrangThaiOut
 *
 * Kết quả CHUNG của mọi hành động moderation bật/tắt một trạng thái.
 *
 * Hai trường, và cả hai đều cần:
 *
 * - `da_doi` — hành động này có đổi gì không. Bấm "ẩn" lần thứ hai trả `false`, và đó
 * **không** phải lỗi: `core/ghi.py` cố ý không reset `hidden_at` (mất mốc thời gian
 * moderation thật) và không đẻ dòng `AuditLog` thứ hai. UI đọc trường này để không
 * báo "đã ẩn xong" cho một cú bấm chẳng làm gì;
 * - `dang_bat` — trạng thái SAU khi gọi. Đây là thứ UI vẽ, và nó đúng ở cả hai nhánh
 * của `da_doi` — nên hai mod bấm cùng lúc vẫn thấy cùng một màn hình.
 */
export type KetQuaDoiTrangThaiOut = {
    /**
     * Da Doi
     */
    da_doi: boolean;
    /**
     * Dang Bat
     */
    dang_bat: boolean;
};

/**
 * KetQuaXoaSubOut
 *
 * Kết quả `DELETE /subs/{slug}`.
 *
 * Trả một thân JSON thay vì 204 rỗng vì client TS sinh từ OpenAPI: một `204` không thân
 * cho ra kiểu `void`, và lúc đó `slug` vừa xoá — thứ UI cần để gỡ đúng hàng khỏi bảng —
 * phải lấy từ biến cục bộ của lời gọi. Đúng thì đúng, nhưng nó là một lần suy lại.
 */
export type KetQuaXoaSubOut = {
    /**
     * Da Xoa
     */
    da_xoa: boolean;
    /**
     * Slug
     */
    slug: string;
};

/**
 * LoiOut
 *
 * `{detail, code}` — PLAN mục 7.
 */
export type LoiOut = {
    /**
     * Code
     */
    code: string;
    /**
     * Detail
     */
    detail: string;
};

/**
 * MachQuanTriOut
 *
 * Trang chi tiết một mạch cho mod (PLAN 9.3 mục 2) — kèm mọi mốc để bấm ẩn từng ô.
 */
export type MachQuanTriOut = {
    /**
     * Comment Count
     */
    comment_count: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Da Bi An
     */
    da_bi_an: boolean;
    /**
     * Da Khoa
     */
    da_khoa: boolean;
    /**
     * Duong Dan Cong Khai
     */
    duong_dan_cong_khai: string;
    /**
     * Entry Count
     */
    entry_count: number;
    /**
     * Id
     */
    id: number;
    /**
     * Last Activity At
     */
    last_activity_at: string;
    /**
     * Last Entry At
     */
    last_entry_at: string;
    /**
     * Mocs
     */
    mocs: Array<MocQuanTriOut>;
    /**
     * Slug
     */
    slug: string;
    /**
     * Status
     */
    status: string;
    /**
     * Sub Slug
     */
    sub_slug: string;
    tac_gia: NguoiDungTomTatOut;
    /**
     * Title
     */
    title: string;
};

/**
 * MocQuanTriOut
 *
 * Một mốc trong trang chi tiết của khu quản trị.
 *
 * Khác `MocOut` công khai ở đúng chỗ file này tồn tại: `trich_yeu` **không bị che** khi
 * mốc đã bị ẩn hoặc là bia mộ — mod cần đọc để phán xử.
 */
export type MocQuanTriOut = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Da Bi An
     */
    da_bi_an: boolean;
    /**
     * Da Xoa
     */
    da_xoa: boolean;
    /**
     * Id
     */
    id: number;
    /**
     * Occurred At
     */
    occurred_at: string;
    /**
     * Seq
     */
    seq: number;
    tac_gia: NguoiDungTomTatOut;
    /**
     * Trich Yeu
     */
    trich_yeu: string;
};

/**
 * ModOut
 *
 * Danh tính của mod đang đăng nhập — đủ để header admin hiện tên và mở khoá UI.
 */
export type ModOut = {
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Is Superuser
     */
    is_superuser: boolean;
    /**
     * Username
     */
    username: string;
};

/**
 * NguoiDungQuanTriOut
 *
 * Hồ sơ một tài khoản dưới góc nhìn mod — trạng thái ban + vài con số để phán xử.
 */
export type NguoiDungQuanTriOut = {
    /**
     * Ban Permanent
     */
    ban_permanent: boolean;
    /**
     * Ban Reason
     */
    ban_reason: string | null;
    /**
     * Banned Until
     */
    banned_until: string | null;
    /**
     * Dang Bi Ban
     */
    dang_bi_ban: boolean;
    /**
     * Date Joined
     */
    date_joined: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Is Staff
     */
    is_staff: boolean;
    /**
     * So Binh Luan
     */
    so_binh_luan: number;
    /**
     * So Mach
     */
    so_mach: number;
    /**
     * Username
     */
    username: string;
};

/**
 * NguoiDungTomTatOut
 *
 * Tác giả, ở mức đủ để render một dòng chữ ký.
 */
export type NguoiDungTomTatOut = {
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Username
     */
    username: string;
};

/**
 * NhatKyOut
 *
 * Một dòng `AuditLog` (PLAN 5.10: "mọi hành động mod ghi AuditLog").
 */
export type NhatKyOut = {
    /**
     * Action
     */
    action: string;
    actor: NguoiDungTomTatOut;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Id
     */
    id: number;
    /**
     * Meta
     */
    meta: {
        [key: string]: unknown;
    };
    /**
     * Target Id
     */
    target_id: number | null;
    /**
     * Target Type
     */
    target_type: string;
};

/**
 * NoiDungBiBaoCaoOut
 *
 * Ngữ cảnh của thứ bị báo cáo — PLAN 9.3: "bảng, **xem ngữ cảnh**, nút ẩn/khoá/ban".
 *
 * **Trường `trich_yeu` mang nội dung KỂ CẢ khi nó đã bị ẩn**, và đó là chủ đích của cả
 * file này (xem docstring module). Nó chỉ ra được sau `ChiMod`.
 *
 * `None` cho cả object khi đích không còn tồn tại: `Report.target_id` là
 * `BigIntegerField`, không phải FK — cố ý, vì một báo cáo phải sống sót được sau khi
 * thứ bị tố bị xoá cứng. Frontend phải xử được ca đó chứ không giả định luôn có ngữ cảnh.
 */
export type NoiDungBiBaoCaoOut = {
    /**
     * Da Bi An
     */
    da_bi_an: boolean;
    /**
     * Duong Dan Cong Khai
     */
    duong_dan_cong_khai: string;
    /**
     * Id
     */
    id: number;
    /**
     * Loai
     */
    loai: 'mach' | 'moc' | 'comment';
    /**
     * Mach Da Khoa
     */
    mach_da_khoa: boolean;
    /**
     * Mach Id
     */
    mach_id: number | null;
    /**
     * Mach Title
     */
    mach_title: string;
    /**
     * Seq
     */
    seq: number | null;
    tac_gia: NguoiDungTomTatOut | null;
    /**
     * Tac Gia Bi Ban
     */
    tac_gia_bi_ban: boolean | null;
    /**
     * Trich Yeu
     */
    trich_yeu: string;
};

/**
 * SuaSubIn
 *
 * PATCH: trường nào `None` là **không đổi**, không phải "đặt về rỗng".
 *
 * `slug` cố ý KHÔNG sửa được: nó nằm trong URL công khai `/s/<slug>` và trong
 * `sitemap.ts`. Đổi nó là làm chết mọi liên kết đã phát ra ngoài, và đó phải là một việc
 * có kế hoạch (kèm redirect 301) chứ không phải một trường trong form.
 */
export type SuaSubIn = {
    /**
     * Mo Ta
     */
    mo_ta?: string | null;
    /**
     * Ten
     */
    ten?: string | null;
};

/**
 * SubQuanTriOut
 *
 * Một sub trong khu quản trị — kèm `so_mach`, con số quyết định có xoá được hay không.
 */
export type SubQuanTriOut = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Mo Ta
     */
    mo_ta: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * So Mach
     */
    so_mach: number;
    /**
     * Ten
     */
    ten: string;
};

/**
 * TaoSubIn
 */
export type TaoSubIn = {
    /**
     * Mo Ta
     */
    mo_ta?: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Ten
     */
    ten: string;
};

/**
 * TrangBaoCaoOut
 *
 * Một trang hàng đợi, cursor keyset theo `(created_at, id)` giảm dần.
 */
export type TrangBaoCaoOut = {
    /**
     * Cursor Ke Tiep
     */
    cursor_ke_tiep: string | null;
    /**
     * Items
     */
    items: Array<BaoCaoOut>;
};

/**
 * TrangNhatKyOut
 */
export type TrangNhatKyOut = {
    /**
     * Cursor Ke Tiep
     */
    cursor_ke_tiep: string | null;
    /**
     * Items
     */
    items: Array<NhatKyOut>;
};

export type QuanTriDatAnBinhLuanData = {
    body: DatAnIn;
    path: {
        /**
         * Comment Id
         */
        comment_id: number;
    };
    query?: never;
    url: '/api/admin/comments/{comment_id}/an';
};

export type QuanTriDatAnBinhLuanErrors = {
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
};

export type QuanTriDatAnBinhLuanError = QuanTriDatAnBinhLuanErrors[keyof QuanTriDatAnBinhLuanErrors];

export type QuanTriDatAnBinhLuanResponses = {
    /**
     * OK
     */
    200: KetQuaDoiTrangThaiOut;
};

export type QuanTriDatAnBinhLuanResponse = QuanTriDatAnBinhLuanResponses[keyof QuanTriDatAnBinhLuanResponses];

export type QuanTriXemMachData = {
    body?: never;
    path: {
        /**
         * Mach Id
         */
        mach_id: number;
    };
    query?: never;
    url: '/api/admin/machs/{mach_id}';
};

export type QuanTriXemMachErrors = {
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
};

export type QuanTriXemMachError = QuanTriXemMachErrors[keyof QuanTriXemMachErrors];

export type QuanTriXemMachResponses = {
    /**
     * OK
     */
    200: MachQuanTriOut;
};

export type QuanTriXemMachResponse = QuanTriXemMachResponses[keyof QuanTriXemMachResponses];

export type QuanTriDatAnMachData = {
    body: DatAnIn;
    path: {
        /**
         * Mach Id
         */
        mach_id: number;
    };
    query?: never;
    url: '/api/admin/machs/{mach_id}/an';
};

export type QuanTriDatAnMachErrors = {
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
};

export type QuanTriDatAnMachError = QuanTriDatAnMachErrors[keyof QuanTriDatAnMachErrors];

export type QuanTriDatAnMachResponses = {
    /**
     * OK
     */
    200: KetQuaDoiTrangThaiOut;
};

export type QuanTriDatAnMachResponse = QuanTriDatAnMachResponses[keyof QuanTriDatAnMachResponses];

export type QuanTriDatKhoaMachData = {
    body: DatKhoaMachIn;
    path: {
        /**
         * Mach Id
         */
        mach_id: number;
    };
    query?: never;
    url: '/api/admin/machs/{mach_id}/khoa';
};

export type QuanTriDatKhoaMachErrors = {
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
};

export type QuanTriDatKhoaMachError = QuanTriDatKhoaMachErrors[keyof QuanTriDatKhoaMachErrors];

export type QuanTriDatKhoaMachResponses = {
    /**
     * OK
     */
    200: KetQuaDoiTrangThaiOut;
};

export type QuanTriDatKhoaMachResponse = QuanTriDatKhoaMachResponses[keyof QuanTriDatKhoaMachResponses];

export type QuanTriToiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/me';
};

export type QuanTriToiErrors = {
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
};

export type QuanTriToiError = QuanTriToiErrors[keyof QuanTriToiErrors];

export type QuanTriToiResponses = {
    /**
     * OK
     */
    200: ModOut;
};

export type QuanTriToiResponse = QuanTriToiResponses[keyof QuanTriToiResponses];

export type QuanTriDatAnMocData = {
    body: DatAnIn;
    path: {
        /**
         * Moc Id
         */
        moc_id: number;
    };
    query?: never;
    url: '/api/admin/mocs/{moc_id}/an';
};

export type QuanTriDatAnMocErrors = {
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
};

export type QuanTriDatAnMocError = QuanTriDatAnMocErrors[keyof QuanTriDatAnMocErrors];

export type QuanTriDatAnMocResponses = {
    /**
     * OK
     */
    200: KetQuaDoiTrangThaiOut;
};

export type QuanTriDatAnMocResponse = QuanTriDatAnMocResponses[keyof QuanTriDatAnMocResponses];

export type QuanTriLietKeNhatKyData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Action
         */
        action?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Cursor
         */
        cursor?: string | null;
    };
    url: '/api/admin/nhat-ky';
};

export type QuanTriLietKeNhatKyErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
};

export type QuanTriLietKeNhatKyError = QuanTriLietKeNhatKyErrors[keyof QuanTriLietKeNhatKyErrors];

export type QuanTriLietKeNhatKyResponses = {
    /**
     * OK
     */
    200: TrangNhatKyOut;
};

export type QuanTriLietKeNhatKyResponse = QuanTriLietKeNhatKyResponses[keyof QuanTriLietKeNhatKyResponses];

export type QuanTriLietKeBaoCaoData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Trang Thai
         */
        trang_thai?: 'cho_xu_ly' | 'da_xu_ly' | 'tat_ca';
        /**
         * Limit
         */
        limit?: number;
        /**
         * Cursor
         */
        cursor?: string | null;
    };
    url: '/api/admin/reports';
};

export type QuanTriLietKeBaoCaoErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
};

export type QuanTriLietKeBaoCaoError = QuanTriLietKeBaoCaoErrors[keyof QuanTriLietKeBaoCaoErrors];

export type QuanTriLietKeBaoCaoResponses = {
    /**
     * OK
     */
    200: TrangBaoCaoOut;
};

export type QuanTriLietKeBaoCaoResponse = QuanTriLietKeBaoCaoResponses[keyof QuanTriLietKeBaoCaoResponses];

export type QuanTriDongBaoCaoData = {
    body: DongBaoCaoIn;
    path: {
        /**
         * Report Id
         */
        report_id: number;
    };
    query?: never;
    url: '/api/admin/reports/{report_id}/dong';
};

export type QuanTriDongBaoCaoErrors = {
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
};

export type QuanTriDongBaoCaoError = QuanTriDongBaoCaoErrors[keyof QuanTriDongBaoCaoErrors];

export type QuanTriDongBaoCaoResponses = {
    /**
     * OK
     */
    200: KetQuaDoiTrangThaiOut;
};

export type QuanTriDongBaoCaoResponse = QuanTriDongBaoCaoResponses[keyof QuanTriDongBaoCaoResponses];

export type QuanTriLietKeSubData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/subs';
};

export type QuanTriLietKeSubErrors = {
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
};

export type QuanTriLietKeSubError = QuanTriLietKeSubErrors[keyof QuanTriLietKeSubErrors];

export type QuanTriLietKeSubResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<SubQuanTriOut>;
};

export type QuanTriLietKeSubResponse = QuanTriLietKeSubResponses[keyof QuanTriLietKeSubResponses];

export type QuanTriTaoSubData = {
    body: TaoSubIn;
    path?: never;
    query?: never;
    url: '/api/admin/subs';
};

export type QuanTriTaoSubErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Conflict
     */
    409: LoiOut;
};

export type QuanTriTaoSubError = QuanTriTaoSubErrors[keyof QuanTriTaoSubErrors];

export type QuanTriTaoSubResponses = {
    /**
     * Created
     */
    201: SubQuanTriOut;
};

export type QuanTriTaoSubResponse = QuanTriTaoSubResponses[keyof QuanTriTaoSubResponses];

export type QuanTriXoaSubData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/admin/subs/{slug}';
};

export type QuanTriXoaSubErrors = {
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
    /**
     * Conflict
     */
    409: LoiOut;
};

export type QuanTriXoaSubError = QuanTriXoaSubErrors[keyof QuanTriXoaSubErrors];

export type QuanTriXoaSubResponses = {
    /**
     * OK
     */
    200: KetQuaXoaSubOut;
};

export type QuanTriXoaSubResponse = QuanTriXoaSubResponses[keyof QuanTriXoaSubResponses];

export type QuanTriSuaSubData = {
    body: SuaSubIn;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/admin/subs/{slug}';
};

export type QuanTriSuaSubErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
};

export type QuanTriSuaSubError = QuanTriSuaSubErrors[keyof QuanTriSuaSubErrors];

export type QuanTriSuaSubResponses = {
    /**
     * OK
     */
    200: SubQuanTriOut;
};

export type QuanTriSuaSubResponse = QuanTriSuaSubResponses[keyof QuanTriSuaSubResponses];

export type QuanTriXemNguoiDungData = {
    body?: never;
    path: {
        /**
         * Username
         */
        username: string;
    };
    query?: never;
    url: '/api/admin/users/{username}';
};

export type QuanTriXemNguoiDungErrors = {
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
};

export type QuanTriXemNguoiDungError = QuanTriXemNguoiDungErrors[keyof QuanTriXemNguoiDungErrors];

export type QuanTriXemNguoiDungResponses = {
    /**
     * OK
     */
    200: NguoiDungQuanTriOut;
};

export type QuanTriXemNguoiDungResponse = QuanTriXemNguoiDungResponses[keyof QuanTriXemNguoiDungResponses];

export type QuanTriBanNguoiDungData = {
    body: BanIn;
    path: {
        /**
         * Username
         */
        username: string;
    };
    query?: never;
    url: '/api/admin/users/{username}/ban';
};

export type QuanTriBanNguoiDungErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
    /**
     * Conflict
     */
    409: LoiOut;
};

export type QuanTriBanNguoiDungError = QuanTriBanNguoiDungErrors[keyof QuanTriBanNguoiDungErrors];

export type QuanTriBanNguoiDungResponses = {
    /**
     * OK
     */
    200: KetQuaDoiTrangThaiOut;
};

export type QuanTriBanNguoiDungResponse = QuanTriBanNguoiDungResponses[keyof QuanTriBanNguoiDungResponses];

export type QuanTriGoBanNguoiDungData = {
    body?: never;
    path: {
        /**
         * Username
         */
        username: string;
    };
    query?: never;
    url: '/api/admin/users/{username}/go-ban';
};

export type QuanTriGoBanNguoiDungErrors = {
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
};

export type QuanTriGoBanNguoiDungError = QuanTriGoBanNguoiDungErrors[keyof QuanTriGoBanNguoiDungErrors];

export type QuanTriGoBanNguoiDungResponses = {
    /**
     * OK
     */
    200: KetQuaDoiTrangThaiOut;
};

export type QuanTriGoBanNguoiDungResponse = QuanTriGoBanNguoiDungResponses[keyof QuanTriGoBanNguoiDungResponses];
