// SINH TỰ ĐỘNG bởi `pnpm codegen` từ OpenAPI của Django Ninja.
// KHÔNG SỬA TAY — mọi thay đổi sẽ mất ở lần codegen kế tiếp.
// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

/**
 * BanIn
 *
 * Body của `POST /users/{username}/ban`.
 *
 * `vinh_vien`, `den_khi` và `so_ngay` **loại trừ nhau**: đúng một trong ba.
 * `core/ghi.py::ban_user` là chỗ ném lỗi cho cặp `vinh_vien`/`den_khi`, không phải
 * pydantic — luật ấy thuộc đường ghi, và nó phải đúng cả khi ai đó gọi hàm từ
 * `manage.py shell`. `so_ngay` thì **không** xuống tới đường ghi: nó được quy đổi thành
 * `den_khi` ở tầng API (`api/quan_tri_nguoi_dung.py`), nên `ban_user` vẫn chỉ biết đúng
 * hai kiểu ban và bất biến của nó không rộng ra.
 */
export type BanIn = {
    /**
     * Den Khi
     */
    den_khi?: string | null;
    /**
     * Ly Do
     */
    ly_do: string;
    /**
     * So Ngay
     */
    so_ngay?: number | null;
    /**
     * Vinh Vien
     */
    vinh_vien?: boolean;
};

/**
 * BaoCaoOut
 *
 * Một dòng trong hàng đợi báo cáo (PLAN 5.10).
 */
export type BaoCaoOut = {
    /**
     * Action
     */
    action: string | null;
    /**
     * Created At
     */
    created_at: string;
    dich: NoiDungBiBaoCaoOut | null;
    /**
     * Ghi Chu
     */
    ghi_chu: string;
    /**
     * Id
     */
    id: number;
    /**
     * Ly Do
     */
    ly_do: 'phim_hang' | 'cam_ket_loi_nhuan' | 'lua_dao' | 'link_nhom_kin' | 'spam' | 'khac';
    reporter: NguoiDungTomTatOut;
    /**
     * Resolved At
     */
    resolved_at: string | null;
    resolved_by: NguoiDungTomTatOut | null;
};

/**
 * BinhLuanDongOut
 *
 * Một hàng của bảng bình luận.
 *
 * `trich_yeu` **không bị che** kể cả khi bình luận đã bị ẩn hoặc đã thành bia mộ — cùng
 * lý lẽ với `NoiDungBiBaoCaoOut`, và cùng điều kiện an toàn: chỉ ra sau `ChiMod`.
 */
export type BinhLuanDongOut = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Da Bi An
     */
    da_bi_an: boolean;
    /**
     * Da Xoa
     */
    da_xoa: boolean;
    /**
     * Duong Dan Cong Khai
     */
    duong_dan_cong_khai: string;
    /**
     * Id
     */
    id: number;
    /**
     * Mach Id
     */
    mach_id: number;
    /**
     * Mach Title
     */
    mach_title: string;
    /**
     * Score
     */
    score: number;
    tac_gia: NguoiDungTomTatOut;
    /**
     * Trich Yeu
     */
    trich_yeu: string;
};

/**
 * CaiDatGoogleIn
 *
 * Body của `PUT /admin/cai-dat/google`.
 *
 * `secret` **vắng hoặc rỗng ⇒ GIỮ NGUYÊN secret cũ**, không phải xoá. Người ta sửa
 * `client_id` mà không dán lại secret là chuyện thường; coi "trống" là "xoá" thì mỗi
 * lần sửa `client_id` là một lần vô tình gỡ Google khỏi site. Muốn gỡ hẳn thì dùng
 * `DELETE` — một hành động có tên.
 */
export type CaiDatGoogleIn = {
    /**
     * Client Id
     */
    client_id: string;
    /**
     * Secret
     */
    secret?: string | null;
};

/**
 * CaiDatGoogleOut
 *
 * Trạng thái Google OAuth cho trang Cài đặt.
 *
 * ⚠ **KHÔNG có trường secret, và đó là hợp đồng chứ không phải sơ suất.** Chỉ
 * `secret_duoi` — 4 ký tự cuối, đủ để người ta nhận ra mình đã dán đúng chuỗi nào,
 * không đủ để dùng lại. `tests/test_api_quan_tri_cai_dat.py` quét toàn bộ body tìm
 * chuỗi secret và ĐỎ nếu thấy.
 */
export type CaiDatGoogleOut = {
    /**
     * Bat
     */
    bat: boolean;
    /**
     * Client Id
     */
    client_id: string;
    /**
     * Nguon
     */
    nguon: string | null;
    /**
     * Redirect Uri
     */
    redirect_uri: string;
    /**
     * Secret Da Dat
     */
    secret_da_dat: boolean;
    /**
     * Secret Duoi
     */
    secret_duoi: string;
    /**
     * Sua Duoc
     */
    sua_duoc: boolean;
};

/**
 * ChanDoanIndexOut
 *
 * Một index: Meilisearch nói bao nhiêu, Postgres nói bao nhiêu.
 *
 * `so_tai_lieu = null` nghĩa là **không đọc được** (Meili chết, hoặc khoá không có
 * quyền với index này) — khác hẳn `0`, vốn nghĩa là "đọc được, và nó rỗng". Gộp hai
 * trạng thái ấy làm một là để một khoá thiếu quyền trông y hệt một index chưa dựng.
 *
 * `lech` **`True` cả khi không đọc được**: không biết cũng là một câu trả lời cần nhìn.
 */
export type ChanDoanIndexOut = {
    /**
     * Ghi Chu
     */
    ghi_chu: string;
    /**
     * Lech
     */
    lech: boolean;
    /**
     * So Hang Postgres
     */
    so_hang_postgres: number;
    /**
     * So Tai Lieu
     */
    so_tai_lieu: number | null;
    /**
     * Ten
     */
    ten: string;
};

/**
 * ChanDoanTimKiemOut
 *
 * Trạng thái đối soát của cả cụm tìm kiếm.
 */
export type ChanDoanTimKiemOut = {
    /**
     * Cac Index
     */
    cac_index: Array<ChanDoanIndexOut>;
    /**
     * Co Lech
     */
    co_lech: boolean;
    /**
     * Meili Song
     */
    meili_song: boolean;
};

/**
 * DatAnIn
 *
 * Body của mọi endpoint ẩn/gỡ ẩn.
 *
 * **Một endpoint đặt-trạng-thái thay vì hai endpoint `hide`/`unhide`** — hai chiều nhận
 * cùng bộ đầu vào, nên tách ra chỉ nhân đôi số chỗ phải kiểm quyền. Và nó **idempotent**:
 * gửi `an=true` hai lần cho ra cùng một trạng thái.
 */
export type DatAnIn = {
    /**
     * An
     */
    an: boolean;
    /**
     * Ly Do
     */
    ly_do?: string;
};

/**
 * DatKhoaMachIn
 *
 * Body của `POST /machs/{id}/khoa`.
 *
 * `khoa` là **trục riêng, không phải `status`** (PLAN 5.10, docstring `Mach`): mạch bị
 * khoá vẫn đọc được nhưng cấm mọi tương tác, còn `closed` là tác giả tự đóng sổ.
 */
export type DatKhoaMachIn = {
    /**
     * Khoa
     */
    khoa: boolean;
    /**
     * Ly Do
     */
    ly_do?: string;
};

/**
 * DatMatKhauIn
 *
 * Body của `POST /admin/users/{username}/mat-khau`.
 *
 * `mat_khau: null` ⇒ **xoá mật khẩu** (`set_unusable_password`) — vế "set pass rỗng"
 * của đơn hàng. Khác hẳn `SuaNguoiDungIn`, nơi `None` nghĩa là "không đổi": ở đây body
 * chỉ có một trường và mục đích của lời gọi luôn là *đổi mật khẩu*, nên `null` không thể
 * mang nghĩa "không làm gì".
 */
export type DatMatKhauIn = {
    /**
     * Mat Khau
     */
    mat_khau?: string | null;
};

/**
 * DemTheoNgayOut
 *
 * Một ô của biểu đồ 30 ngày. `ngay` là **ngày lịch Việt Nam**, không phải UTC.
 */
export type DemTheoNgayOut = {
    /**
     * Binh Luan Moi
     */
    binh_luan_moi: number;
    /**
     * Mach Moi
     */
    mach_moi: number;
    /**
     * Moc Moi
     */
    moc_moi: number;
    /**
     * Ngay
     */
    ngay: string;
    /**
     * Nguoi Dung Moi
     */
    nguoi_dung_moi: number;
};

/**
 * DoiQuyenModIn
 *
 * Body của `POST /admin/users/{username}/quyen-mod` — công tắc `is_staff`.
 *
 * ⚠ **Chỉ có `bat`.** Không khai `is_staff` cũng không khai `is_superuser`.
 * `is_superuser` **không** cấp được từ khu quản trị ở bất kỳ cửa nào — Django admin vẫn
 * là nơi duy nhất phong superuser.
 *
 * Hàng rào cho luật ấy là một dòng chấm **thẳng lên hình dạng schema**:
 * `test_api_quyen_mod.py::test_B9_…` khẳng định `set(model_fields) == {"bat"}`.
 * Đừng thay nó bằng bài "gửi kèm khoá lạ rồi đòi cờ không đổi" — bài ấy XANH kể cả khi
 * schema mọc thêm trường, vì handler chỉ đọc `du_lieu.bat`. Bản đầu của lượt này mắc
 * đúng lỗi đó và lượt phản biện bắt được.
 */
export type DoiQuyenModIn = {
    /**
     * Bat
     */
    bat: boolean;
};

/**
 * DongBaoCaoIn
 *
 * Body của `POST /reports/{id}/dong`.
 */
export type DongBaoCaoIn = {
    /**
     * Hanh Dong
     */
    hanh_dong: 'an' | 'khoa' | 'ban' | 'bo_qua';
};

/**
 * GanModSubIn
 *
 * Body của `POST /admin/subs/{slug}/mods`.
 *
 * Nhận `username` chứ không `id`: id của `User` không hiện ở đâu trên giao diện quản
 * trị, nên một body mang id là một body không ai dựng lại được bằng tay để thử.
 */
export type GanModSubIn = {
    /**
     * Username
     */
    username: string;
};

/**
 * KetQuaDoiTrangThaiOut
 *
 * Kết quả CHUNG của mọi hành động moderation bật/tắt một trạng thái.
 *
 * Hai trường, và cả hai đều cần:
 *
 * - `da_doi` — hành động này có đổi gì không. Bấm "ẩn" lần thứ hai trả `false`, và đó
 * **không** phải lỗi: `core/ghi.py` cố ý không reset `hidden_at` (mất mốc thời gian
 * moderation thật) và không đẻ dòng `AuditLog` thứ hai. UI đọc trường này để không
 * báo "đã ẩn xong" cho một cú bấm chẳng làm gì;
 * - `dang_bat` — trạng thái SAU khi gọi. Đây là thứ UI vẽ, và nó đúng ở cả hai nhánh
 * của `da_doi` — nên hai mod bấm cùng lúc vẫn thấy cùng một màn hình.
 */
export type KetQuaDoiTrangThaiOut = {
    /**
     * Da Doi
     */
    da_doi: boolean;
    /**
     * Dang Bat
     */
    dang_bat: boolean;
};

/**
 * KetQuaXoaSubOut
 *
 * Kết quả `DELETE /subs/{slug}`.
 *
 * Trả một thân JSON thay vì 204 rỗng vì client TS sinh từ OpenAPI: một `204` không thân
 * cho ra kiểu `void`, và lúc đó `slug` vừa xoá — thứ UI cần để gỡ đúng hàng khỏi bảng —
 * phải lấy từ biến cục bộ của lời gọi. Đúng thì đúng, nhưng nó là một lần suy lại.
 */
export type KetQuaXoaSubOut = {
    /**
     * Da Xoa
     */
    da_xoa: boolean;
    /**
     * Slug
     */
    slug: string;
};

/**
 * LoiOut
 *
 * `{detail, code}` — PLAN mục 7.
 */
export type LoiOut = {
    /**
     * Code
     */
    code: string;
    /**
     * Detail
     */
    detail: string;
};

/**
 * LuotXemNgayOut
 *
 * Một ô của biểu đồ cột. Ngày KHÔNG có lượt xem nào vẫn có mặt, với hai số 0.
 */
export type LuotXemNgayOut = {
    /**
     * Ngay
     */
    ngay: string;
    /**
     * So Khach
     */
    so_khach: number | null;
    /**
     * So Luot Bot
     */
    so_luot_bot: number;
    /**
     * So Luot Nguoi
     */
    so_luot_nguoi: number;
};

/**
 * LuotXemOut
 *
 * Toàn bộ số liệu của trang `/luot-xem` cho MỘT khoảng.
 */
export type LuotXemOut = {
    /**
     * Chi Tiet Chi 90 Ngay
     */
    chi_tiet_chi_90_ngay: boolean;
    /**
     * Chuoi Ngay
     */
    chuoi_ngay: Array<LuotXemNgayOut>;
    /**
     * Khoang
     */
    khoang: string;
    /**
     * So Truc Tiep
     */
    so_truc_tiep: number;
    /**
     * Theo Nhom Bot
     */
    theo_nhom_bot: Array<NhomBotOut>;
    /**
     * Thiet Bi
     */
    thiet_bi: Array<MucSoLuotOut>;
    tong: LuotXemTongOut;
    /**
     * Top Bot
     */
    top_bot: Array<TenBotOut>;
    /**
     * Top Duong Dan
     */
    top_duong_dan: Array<TopDuongDanOut>;
    /**
     * Top Nguon
     */
    top_nguon: Array<NguonOut>;
    /**
     * Trinh Duyet
     */
    trinh_duyet: Array<MucSoLuotOut>;
};

/**
 * LuotXemTongOut
 *
 * Sáu con số lớn. `so_luot` = `so_luot_nguoi + so_luot_bot`, không hơn.
 *
 * Server trả cả tổng lẫn hai vế thay vì để frontend cộng: ba chỗ trên màn hình (các ô
 * KPI, biểu đồ, dòng "% bot") phải nói cùng một chuyện, và cách chắc chắn nhất là
 * chúng cùng đọc một phép cộng.
 *
 * ⚠ Năm con số đầu đọc theo `?khoang=`; `so_online` thì **không** — nó luôn là 5 phút
 * gần nhất. Chúng ở chung một khối vì chúng là chung một hàng ô KPI trên màn hình, chứ
 * không phải vì chúng cùng một khoảng.
 */
export type LuotXemTongOut = {
    /**
     * So Khach
     */
    so_khach: number;
    /**
     * So Luot
     */
    so_luot: number;
    /**
     * So Luot Bot
     */
    so_luot_bot: number;
    /**
     * So Luot Nguoi
     */
    so_luot_nguoi: number;
    /**
     * So Online
     */
    so_online: number;
};

/**
 * MachDongOut
 *
 * Một hàng của bảng mạch trong khu quản trị.
 */
export type MachDongOut = {
    /**
     * Comment Count
     */
    comment_count: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Da Bi An
     */
    da_bi_an: boolean;
    /**
     * Da Khoa
     */
    da_khoa: boolean;
    /**
     * Diem
     */
    diem: number;
    /**
     * Duong Dan Cong Khai
     */
    duong_dan_cong_khai: string;
    /**
     * Entry Count
     */
    entry_count: number;
    /**
     * Id
     */
    id: number;
    /**
     * Last Activity At
     */
    last_activity_at: string;
    /**
     * Status
     */
    status: string;
    /**
     * Sub Slug
     */
    sub_slug: string;
    tac_gia: NguoiDungTomTatOut;
    /**
     * Title
     */
    title: string;
};

/**
 * MachQuanTriOut
 *
 * Trang chi tiết một mạch cho mod (PLAN 9.3 mục 2) — kèm mọi mốc để bấm ẩn từng ô.
 */
export type MachQuanTriOut = {
    /**
     * Comment Count
     */
    comment_count: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Da Bi An
     */
    da_bi_an: boolean;
    /**
     * Da Khoa
     */
    da_khoa: boolean;
    /**
     * Duong Dan Cong Khai
     */
    duong_dan_cong_khai: string;
    /**
     * Entry Count
     */
    entry_count: number;
    /**
     * Id
     */
    id: number;
    /**
     * Last Activity At
     */
    last_activity_at: string;
    /**
     * Last Entry At
     */
    last_entry_at: string;
    /**
     * Mocs
     */
    mocs: Array<MocQuanTriOut>;
    /**
     * Slug
     */
    slug: string;
    /**
     * Status
     */
    status: string;
    /**
     * Sub Slug
     */
    sub_slug: string;
    tac_gia: NguoiDungTomTatOut;
    /**
     * Title
     */
    title: string;
};

/**
 * MocQuanTriOut
 *
 * Một mốc trong trang chi tiết của khu quản trị.
 *
 * Khác `MocOut` công khai ở đúng chỗ file này tồn tại: `trich_yeu` **không bị che** khi
 * mốc đã bị ẩn hoặc là bia mộ — mod cần đọc để phán xử.
 */
export type MocQuanTriOut = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Da Bi An
     */
    da_bi_an: boolean;
    /**
     * Da Xoa
     */
    da_xoa: boolean;
    /**
     * Id
     */
    id: number;
    /**
     * Occurred At
     */
    occurred_at: string;
    /**
     * Seq
     */
    seq: number;
    tac_gia: NguoiDungTomTatOut;
    /**
     * Trich Yeu
     */
    trich_yeu: string;
};

/**
 * ModOut
 *
 * Danh tính của mod đang đăng nhập — đủ để header admin hiện tên và mở khoá UI.
 */
export type ModOut = {
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Is Superuser
     */
    is_superuser: boolean;
    /**
     * Username
     */
    username: string;
};

/**
 * MucSoLuotOut
 *
 * Một dòng của hai bảng nhỏ "Trình duyệt" và "Thiết bị".
 *
 * `ten` là **khoá ascii** (`chrome`, `di_dong`, …), không phải nhãn hiển thị: nhãn tiếng
 * Việt do frontend map. Trả nhãn từ server là khoá dữ liệu và chữ trên màn hình dính vào
 * nhau — đổi một chữ hoa thành một breaking change của API.
 */
export type MucSoLuotOut = {
    /**
     * So Luot
     */
    so_luot: number;
    /**
     * Ten
     */
    ten: string;
};

/**
 * NguoiDungQuanTriOut
 *
 * Hồ sơ một tài khoản dưới góc nhìn mod — trạng thái ban + vài con số để phán xử.
 */
export type NguoiDungQuanTriOut = {
    /**
     * Ban Permanent
     */
    ban_permanent: boolean;
    /**
     * Ban Reason
     */
    ban_reason: string | null;
    /**
     * Banned Until
     */
    banned_until: string | null;
    /**
     * Co Mat Khau
     */
    co_mat_khau: boolean;
    /**
     * Dang Bi Ban
     */
    dang_bi_ban: boolean;
    /**
     * Date Joined
     */
    date_joined: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Is Staff
     */
    is_staff: boolean;
    /**
     * Is Superuser
     */
    is_superuser: boolean;
    /**
     * So Binh Luan
     */
    so_binh_luan: number;
    /**
     * So Mach
     */
    so_mach: number;
    /**
     * Subs Mod
     */
    subs_mod: Array<string>;
    /**
     * Username
     */
    username: string;
    /**
     * Vai Tro
     */
    vai_tro: string;
};

/**
 * NguoiDungTomTatOut
 *
 * Tác giả, ở mức đủ để render một dòng chữ ký.
 */
export type NguoiDungTomTatOut = {
    /**
     * Avatar Url
     */
    avatar_url: string | null;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Username
     */
    username: string;
};

/**
 * NguonOut
 *
 * Một dòng bảng "Nguồn truy cập". `nguon` là **tên miền**, không bao giờ là URL.
 *
 * Chỉ hàng NGƯỜI, và chỉ `nguon != ""`. Phần rỗng (trực tiếp / nội bộ / rác) đi vào
 * `LuotXemOut.so_truc_tiep` — gộp chung vào bảng thì nó chiếm dòng đầu ở mọi site và
 * đẩy hết nguồn thật xuống dưới.
 */
export type NguonOut = {
    /**
     * Nguon
     */
    nguon: string;
    /**
     * So Luot
     */
    so_luot: number;
};

/**
 * NhatKyOut
 *
 * Một dòng `AuditLog` (PLAN 5.10: "mọi hành động mod ghi AuditLog").
 */
export type NhatKyOut = {
    /**
     * Action
     */
    action: string;
    actor: NguoiDungTomTatOut;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Id
     */
    id: number;
    /**
     * Meta
     */
    meta: {
        [key: string]: unknown;
    };
    /**
     * Target Id
     */
    target_id: number | null;
    /**
     * Target Type
     */
    target_type: string;
};

/**
 * NhomBotOut
 *
 * Một dòng bảng "Bot theo nhóm". Sáu khoá của `core/bot.py::NHOM_HOP_LE`.
 */
export type NhomBotOut = {
    /**
     * Nhom
     */
    nhom: string;
    /**
     * So Luot
     */
    so_luot: number;
};

/**
 * NoiDungBiBaoCaoOut
 *
 * Ngữ cảnh của thứ bị báo cáo — PLAN 9.3: "bảng, **xem ngữ cảnh**, nút ẩn/khoá/ban".
 *
 * **Trường `trich_yeu` mang nội dung KỂ CẢ khi nó đã bị ẩn**, và đó là chủ đích của cả
 * file này (xem docstring module). Nó chỉ ra được sau `ChiMod`.
 *
 * `None` cho cả object khi đích không còn tồn tại: `Report.target_id` là
 * `BigIntegerField`, không phải FK — cố ý, vì một báo cáo phải sống sót được sau khi
 * thứ bị tố bị xoá cứng. Frontend phải xử được ca đó chứ không giả định luôn có ngữ cảnh.
 */
export type NoiDungBiBaoCaoOut = {
    /**
     * Da Bi An
     */
    da_bi_an: boolean;
    /**
     * Duong Dan Cong Khai
     */
    duong_dan_cong_khai: string;
    /**
     * Id
     */
    id: number;
    /**
     * Loai
     */
    loai: 'mach' | 'moc' | 'comment';
    /**
     * Mach Da Khoa
     */
    mach_da_khoa: boolean;
    /**
     * Mach Id
     */
    mach_id: number | null;
    /**
     * Mach Title
     */
    mach_title: string;
    /**
     * Seq
     */
    seq: number | null;
    tac_gia: NguoiDungTomTatOut | null;
    /**
     * Tac Gia Bi Ban
     */
    tac_gia_bi_ban: boolean | null;
    /**
     * Trich Yeu
     */
    trich_yeu: string;
};

/**
 * SuaNguoiDungIn
 *
 * Body của `PATCH /admin/users/{username}`. Trường `None` = **không đổi**.
 *
 * `username` **không có mặt** — nó nằm trong URL công khai `/u/<username>` và trong mọi
 * trích dẫn `u/…`; đổi nó là làm chết liên kết đã phát ra ngoài, cùng lý lẽ `Sub.slug`.
 *
 * `is_staff`/`is_superuser` cũng **không có mặt** — xem `TaoNguoiDungIn`.
 */
export type SuaNguoiDungIn = {
    /**
     * Display Name
     */
    display_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * SuaSubIn
 *
 * PATCH: trường nào `None` là **không đổi**, không phải "đặt về rỗng".
 *
 * `slug` cố ý KHÔNG sửa được: nó nằm trong URL công khai `/s/<slug>` và trong
 * `sitemap.ts`. Đổi nó là làm chết mọi liên kết đã phát ra ngoài, và đó phải là một việc
 * có kế hoạch (kèm redirect 301) chứ không phải một trường trong form.
 */
export type SuaSubIn = {
    /**
     * Mo Ta
     */
    mo_ta?: string | null;
    /**
     * Ten
     */
    ten?: string | null;
};

/**
 * SubQuanTriOut
 *
 * Một sub trong khu quản trị — kèm `so_mach`, con số quyết định có xoá được hay không.
 *
 * `mods` — người được phân công phụ trách chuyên mục (2026-08-24).
 *
 * ⚠ **Danh sách này CHƯA cấp quyền gì cho ai.** Không endpoint kiểm duyệt nào hỏi tới
 * nó; `ChiMod` vẫn chỉ nhìn `is_staff`. Xem `core/models/dien_dan.py::ModSub` và
 * `plans/2026-08-24-mod-chuyen-muc.md` §0. Đọc nó thành "những người này đang moderate
 * được" là hiểu sai theo hướng nguy hiểm.
 */
export type SubQuanTriOut = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Mo Ta
     */
    mo_ta: string;
    /**
     * Mods
     */
    mods: Array<NguoiDungTomTatOut>;
    /**
     * Slug
     */
    slug: string;
    /**
     * So Mach
     */
    so_mach: number;
    /**
     * Ten
     */
    ten: string;
};

/**
 * SubTomTatOut
 */
export type SubTomTatOut = {
    /**
     * Slug
     */
    slug: string;
    /**
     * So Mach
     */
    so_mach: number;
    /**
     * So Mach 30 Ngay
     */
    so_mach_30_ngay: number;
    /**
     * Ten
     */
    ten: string;
};

/**
 * TaoNguoiDungIn
 *
 * Body của `POST /admin/users` — superuser tạo tài khoản hộ.
 *
 * **Không có `is_staff`/`is_superuser`**, và đó là hợp đồng: cấp quyền mod vẫn nằm
 * ngoài khu quản trị (PLAN mục 7). Xem `plans/2026-08-25-crud-nguoi-dung.md` §0.
 */
export type TaoNguoiDungIn = {
    /**
     * Display Name
     */
    display_name?: string;
    /**
     * Email
     */
    email: string;
    /**
     * Mat Khau
     */
    mat_khau?: string | null;
    /**
     * Username
     */
    username: string;
};

/**
 * TaoSubIn
 */
export type TaoSubIn = {
    /**
     * Mo Ta
     */
    mo_ta?: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Ten
     */
    ten: string;
};

/**
 * TenBotOut
 *
 * Một dòng bảng "Bot nào vào nhiều nhất".
 *
 * `ten` là tên CHUẨN HOÁ của `core/bot.py`, hoặc `"khác"` — không phải User-Agent thô.
 * UA thô không được lưu ở bất kỳ đâu.
 */
export type TenBotOut = {
    /**
     * Nhom
     */
    nhom: string;
    /**
     * So Luot
     */
    so_luot: number;
    /**
     * Ten
     */
    ten: string;
};

/**
 * ThongKeOut
 *
 * Số liệu cho bảng điều khiển. Không cache — xem `Cache-Control` ở endpoint.
 */
export type ThongKeOut = {
    bay_ngay: DemTheoNgayOut;
    /**
     * Cho Xu Ly
     */
    cho_xu_ly: number;
    /**
     * Chuoi Ngay
     */
    chuoi_ngay: Array<DemTheoNgayOut>;
    hom_nay: DemTheoNgayOut;
    theo_trang_thai: TrangThaiMachOut;
    tong: TongOut;
    /**
     * Top Sub
     */
    top_sub: Array<SubTomTatOut>;
};

/**
 * TongOut
 *
 * Bốn con số lớn của hàng thẻ KPI.
 */
export type TongOut = {
    /**
     * Binh Luan
     */
    binh_luan: number;
    /**
     * Mach
     */
    mach: number;
    /**
     * Moc
     */
    moc: number;
    /**
     * Nguoi Dung
     */
    nguoi_dung: number;
    /**
     * Sub
     */
    sub: number;
};

/**
 * TopDuongDanOut
 *
 * Một dòng bảng "Xem nhiều nhất". `duong_dan` **không mang query string**.
 */
export type TopDuongDanOut = {
    /**
     * Duong Dan
     */
    duong_dan: string;
    /**
     * So Luot Bot
     */
    so_luot_bot: number;
    /**
     * So Luot Nguoi
     */
    so_luot_nguoi: number;
};

/**
 * TrangBaoCaoOut
 *
 * Một trang hàng đợi, cursor keyset theo `(created_at, id)` giảm dần.
 */
export type TrangBaoCaoOut = {
    /**
     * Cursor Ke Tiep
     */
    cursor_ke_tiep: string | null;
    /**
     * Items
     */
    items: Array<BaoCaoOut>;
    /**
     * Tong
     */
    tong: number;
};

/**
 * TrangBinhLuanOut
 */
export type TrangBinhLuanOut = {
    /**
     * Cursor Ke Tiep
     */
    cursor_ke_tiep: string | null;
    /**
     * Items
     */
    items: Array<BinhLuanDongOut>;
    /**
     * Tong
     */
    tong: number;
};

/**
 * TrangMachOut
 */
export type TrangMachOut = {
    /**
     * Cursor Ke Tiep
     */
    cursor_ke_tiep: string | null;
    /**
     * Items
     */
    items: Array<MachDongOut>;
    /**
     * Tong
     */
    tong: number;
};

/**
 * TrangNguoiDungOut
 */
export type TrangNguoiDungOut = {
    /**
     * Cursor Ke Tiep
     */
    cursor_ke_tiep: string | null;
    /**
     * Items
     */
    items: Array<NguoiDungQuanTriOut>;
    /**
     * So Staff An
     */
    so_staff_an: number;
    /**
     * Tong
     */
    tong: number;
};

/**
 * TrangNhatKyOut
 */
export type TrangNhatKyOut = {
    /**
     * Cursor Ke Tiep
     */
    cursor_ke_tiep: string | null;
    /**
     * Items
     */
    items: Array<NhatKyOut>;
    /**
     * Tong
     */
    tong: number;
};

/**
 * TrangThaiMachOut
 *
 * Bốn nhóm **LOẠI TRỪ NHAU**, cộng lại đúng bằng tổng số mạch.
 *
 * Chồng lấn là chuyện có thật trong dữ liệu — một mạch bị ẩn cũng có `status`, một mạch
 * bị khoá cũng đang mở hoặc đã đóng. Một biểu đồ vành khuyên vẽ bằng bốn con số chồng
 * nhau thì tổng các lát lớn hơn 100%, và không ai nhìn ra điều đó; nó chỉ trông hơi lệch.
 *
 * Thứ tự phân loại, xét từ trên xuống, dừng ở nhánh đầu tiên khớp:
 * ẩn → khoá → đã đóng sổ → đang mở.
 */
export type TrangThaiMachOut = {
    /**
     * Bi An
     */
    bi_an: number;
    /**
     * Bi Khoa
     */
    bi_khoa: number;
    /**
     * Dong
     */
    dong: number;
    /**
     * Mo
     */
    mo: number;
};

export type QuanTriXoaCaiDatGoogleData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/cai-dat/google';
};

export type QuanTriXoaCaiDatGoogleErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
};

export type QuanTriXoaCaiDatGoogleError = QuanTriXoaCaiDatGoogleErrors[keyof QuanTriXoaCaiDatGoogleErrors];

export type QuanTriXoaCaiDatGoogleResponses = {
    /**
     * OK
     */
    200: CaiDatGoogleOut;
};

export type QuanTriXoaCaiDatGoogleResponse = QuanTriXoaCaiDatGoogleResponses[keyof QuanTriXoaCaiDatGoogleResponses];

export type QuanTriXemCaiDatGoogleData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/cai-dat/google';
};

export type QuanTriXemCaiDatGoogleErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
};

export type QuanTriXemCaiDatGoogleError = QuanTriXemCaiDatGoogleErrors[keyof QuanTriXemCaiDatGoogleErrors];

export type QuanTriXemCaiDatGoogleResponses = {
    /**
     * OK
     */
    200: CaiDatGoogleOut;
};

export type QuanTriXemCaiDatGoogleResponse = QuanTriXemCaiDatGoogleResponses[keyof QuanTriXemCaiDatGoogleResponses];

export type QuanTriLuuCaiDatGoogleData = {
    body: CaiDatGoogleIn;
    path?: never;
    query?: never;
    url: '/api/admin/cai-dat/google';
};

export type QuanTriLuuCaiDatGoogleErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
};

export type QuanTriLuuCaiDatGoogleError = QuanTriLuuCaiDatGoogleErrors[keyof QuanTriLuuCaiDatGoogleErrors];

export type QuanTriLuuCaiDatGoogleResponses = {
    /**
     * OK
     */
    200: CaiDatGoogleOut;
};

export type QuanTriLuuCaiDatGoogleResponse = QuanTriLuuCaiDatGoogleResponses[keyof QuanTriLuuCaiDatGoogleResponses];

export type QuanTriChanDoanTimKiemData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/chan-doan/tim-kiem';
};

export type QuanTriChanDoanTimKiemErrors = {
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
};

export type QuanTriChanDoanTimKiemError = QuanTriChanDoanTimKiemErrors[keyof QuanTriChanDoanTimKiemErrors];

export type QuanTriChanDoanTimKiemResponses = {
    /**
     * OK
     */
    200: ChanDoanTimKiemOut;
};

export type QuanTriChanDoanTimKiemResponse = QuanTriChanDoanTimKiemResponses[keyof QuanTriChanDoanTimKiemResponses];

export type QuanTriLietKeBinhLuanData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Q
         */
        q?: string;
        /**
         * Tac Gia
         */
        tac_gia?: string | null;
        /**
         * Mach Id
         */
        mach_id?: number | null;
        /**
         * Trang Thai
         */
        trang_thai?: 'tat_ca' | 'hien' | 'bi_an' | 'bia_mo';
        /**
         * Limit
         */
        limit?: number;
        /**
         * Cursor
         */
        cursor?: string | null;
    };
    url: '/api/admin/comments';
};

export type QuanTriLietKeBinhLuanErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
};

export type QuanTriLietKeBinhLuanError = QuanTriLietKeBinhLuanErrors[keyof QuanTriLietKeBinhLuanErrors];

export type QuanTriLietKeBinhLuanResponses = {
    /**
     * OK
     */
    200: TrangBinhLuanOut;
};

export type QuanTriLietKeBinhLuanResponse = QuanTriLietKeBinhLuanResponses[keyof QuanTriLietKeBinhLuanResponses];

export type QuanTriDatAnBinhLuanData = {
    body: DatAnIn;
    path: {
        /**
         * Comment Id
         */
        comment_id: number;
    };
    query?: never;
    url: '/api/admin/comments/{comment_id}/an';
};

export type QuanTriDatAnBinhLuanErrors = {
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
};

export type QuanTriDatAnBinhLuanError = QuanTriDatAnBinhLuanErrors[keyof QuanTriDatAnBinhLuanErrors];

export type QuanTriDatAnBinhLuanResponses = {
    /**
     * OK
     */
    200: KetQuaDoiTrangThaiOut;
};

export type QuanTriDatAnBinhLuanResponse = QuanTriDatAnBinhLuanResponses[keyof QuanTriDatAnBinhLuanResponses];

export type QuanTriLuotXemData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Khoang
         */
        khoang?: string;
    };
    url: '/api/admin/luot-xem';
};

export type QuanTriLuotXemErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
};

export type QuanTriLuotXemError = QuanTriLuotXemErrors[keyof QuanTriLuotXemErrors];

export type QuanTriLuotXemResponses = {
    /**
     * OK
     */
    200: LuotXemOut;
};

export type QuanTriLuotXemResponse = QuanTriLuotXemResponses[keyof QuanTriLuotXemResponses];

export type QuanTriLietKeMachData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Q
         */
        q?: string;
        /**
         * Sub
         */
        sub?: string | null;
        /**
         * Tac Gia
         */
        tac_gia?: string | null;
        /**
         * Trang Thai
         */
        trang_thai?: 'tat_ca' | 'chua_go' | 'mo' | 'dong' | 'bi_khoa' | 'bi_an';
        /**
         * Limit
         */
        limit?: number;
        /**
         * Cursor
         */
        cursor?: string | null;
    };
    url: '/api/admin/machs';
};

export type QuanTriLietKeMachErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
};

export type QuanTriLietKeMachError = QuanTriLietKeMachErrors[keyof QuanTriLietKeMachErrors];

export type QuanTriLietKeMachResponses = {
    /**
     * OK
     */
    200: TrangMachOut;
};

export type QuanTriLietKeMachResponse = QuanTriLietKeMachResponses[keyof QuanTriLietKeMachResponses];

export type QuanTriXemMachData = {
    body?: never;
    path: {
        /**
         * Mach Id
         */
        mach_id: number;
    };
    query?: never;
    url: '/api/admin/machs/{mach_id}';
};

export type QuanTriXemMachErrors = {
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
};

export type QuanTriXemMachError = QuanTriXemMachErrors[keyof QuanTriXemMachErrors];

export type QuanTriXemMachResponses = {
    /**
     * OK
     */
    200: MachQuanTriOut;
};

export type QuanTriXemMachResponse = QuanTriXemMachResponses[keyof QuanTriXemMachResponses];

export type QuanTriDatAnMachData = {
    body: DatAnIn;
    path: {
        /**
         * Mach Id
         */
        mach_id: number;
    };
    query?: never;
    url: '/api/admin/machs/{mach_id}/an';
};

export type QuanTriDatAnMachErrors = {
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
};

export type QuanTriDatAnMachError = QuanTriDatAnMachErrors[keyof QuanTriDatAnMachErrors];

export type QuanTriDatAnMachResponses = {
    /**
     * OK
     */
    200: KetQuaDoiTrangThaiOut;
};

export type QuanTriDatAnMachResponse = QuanTriDatAnMachResponses[keyof QuanTriDatAnMachResponses];

export type QuanTriDatKhoaMachData = {
    body: DatKhoaMachIn;
    path: {
        /**
         * Mach Id
         */
        mach_id: number;
    };
    query?: never;
    url: '/api/admin/machs/{mach_id}/khoa';
};

export type QuanTriDatKhoaMachErrors = {
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
};

export type QuanTriDatKhoaMachError = QuanTriDatKhoaMachErrors[keyof QuanTriDatKhoaMachErrors];

export type QuanTriDatKhoaMachResponses = {
    /**
     * OK
     */
    200: KetQuaDoiTrangThaiOut;
};

export type QuanTriDatKhoaMachResponse = QuanTriDatKhoaMachResponses[keyof QuanTriDatKhoaMachResponses];

export type QuanTriToiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/me';
};

export type QuanTriToiErrors = {
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
};

export type QuanTriToiError = QuanTriToiErrors[keyof QuanTriToiErrors];

export type QuanTriToiResponses = {
    /**
     * OK
     */
    200: ModOut;
};

export type QuanTriToiResponse = QuanTriToiResponses[keyof QuanTriToiResponses];

export type QuanTriDatAnMocData = {
    body: DatAnIn;
    path: {
        /**
         * Moc Id
         */
        moc_id: number;
    };
    query?: never;
    url: '/api/admin/mocs/{moc_id}/an';
};

export type QuanTriDatAnMocErrors = {
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
};

export type QuanTriDatAnMocError = QuanTriDatAnMocErrors[keyof QuanTriDatAnMocErrors];

export type QuanTriDatAnMocResponses = {
    /**
     * OK
     */
    200: KetQuaDoiTrangThaiOut;
};

export type QuanTriDatAnMocResponse = QuanTriDatAnMocResponses[keyof QuanTriDatAnMocResponses];

export type QuanTriTaoNguoiDungData = {
    body: TaoNguoiDungIn;
    path?: never;
    query?: never;
    url: '/api/admin/nguoi-dung';
};

export type QuanTriTaoNguoiDungErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Conflict
     */
    409: LoiOut;
};

export type QuanTriTaoNguoiDungError = QuanTriTaoNguoiDungErrors[keyof QuanTriTaoNguoiDungErrors];

export type QuanTriTaoNguoiDungResponses = {
    /**
     * Created
     */
    201: NguoiDungQuanTriOut;
};

export type QuanTriTaoNguoiDungResponse = QuanTriTaoNguoiDungResponses[keyof QuanTriTaoNguoiDungResponses];

export type QuanTriLietKeNhatKyData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Action
         */
        action?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Cursor
         */
        cursor?: string | null;
    };
    url: '/api/admin/nhat-ky';
};

export type QuanTriLietKeNhatKyErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
};

export type QuanTriLietKeNhatKyError = QuanTriLietKeNhatKyErrors[keyof QuanTriLietKeNhatKyErrors];

export type QuanTriLietKeNhatKyResponses = {
    /**
     * OK
     */
    200: TrangNhatKyOut;
};

export type QuanTriLietKeNhatKyResponse = QuanTriLietKeNhatKyResponses[keyof QuanTriLietKeNhatKyResponses];

export type QuanTriLietKeBaoCaoData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Trang Thai
         */
        trang_thai?: 'cho_xu_ly' | 'da_xu_ly' | 'tat_ca';
        /**
         * Limit
         */
        limit?: number;
        /**
         * Cursor
         */
        cursor?: string | null;
    };
    url: '/api/admin/reports';
};

export type QuanTriLietKeBaoCaoErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
};

export type QuanTriLietKeBaoCaoError = QuanTriLietKeBaoCaoErrors[keyof QuanTriLietKeBaoCaoErrors];

export type QuanTriLietKeBaoCaoResponses = {
    /**
     * OK
     */
    200: TrangBaoCaoOut;
};

export type QuanTriLietKeBaoCaoResponse = QuanTriLietKeBaoCaoResponses[keyof QuanTriLietKeBaoCaoResponses];

export type QuanTriDongBaoCaoData = {
    body: DongBaoCaoIn;
    path: {
        /**
         * Report Id
         */
        report_id: number;
    };
    query?: never;
    url: '/api/admin/reports/{report_id}/dong';
};

export type QuanTriDongBaoCaoErrors = {
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
};

export type QuanTriDongBaoCaoError = QuanTriDongBaoCaoErrors[keyof QuanTriDongBaoCaoErrors];

export type QuanTriDongBaoCaoResponses = {
    /**
     * OK
     */
    200: KetQuaDoiTrangThaiOut;
};

export type QuanTriDongBaoCaoResponse = QuanTriDongBaoCaoResponses[keyof QuanTriDongBaoCaoResponses];

export type QuanTriLietKeSubData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/subs';
};

export type QuanTriLietKeSubErrors = {
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
};

export type QuanTriLietKeSubError = QuanTriLietKeSubErrors[keyof QuanTriLietKeSubErrors];

export type QuanTriLietKeSubResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<SubQuanTriOut>;
};

export type QuanTriLietKeSubResponse = QuanTriLietKeSubResponses[keyof QuanTriLietKeSubResponses];

export type QuanTriTaoSubData = {
    body: TaoSubIn;
    path?: never;
    query?: never;
    url: '/api/admin/subs';
};

export type QuanTriTaoSubErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Conflict
     */
    409: LoiOut;
};

export type QuanTriTaoSubError = QuanTriTaoSubErrors[keyof QuanTriTaoSubErrors];

export type QuanTriTaoSubResponses = {
    /**
     * Created
     */
    201: SubQuanTriOut;
};

export type QuanTriTaoSubResponse = QuanTriTaoSubResponses[keyof QuanTriTaoSubResponses];

export type QuanTriXoaSubData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/admin/subs/{slug}';
};

export type QuanTriXoaSubErrors = {
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
    /**
     * Conflict
     */
    409: LoiOut;
};

export type QuanTriXoaSubError = QuanTriXoaSubErrors[keyof QuanTriXoaSubErrors];

export type QuanTriXoaSubResponses = {
    /**
     * OK
     */
    200: KetQuaXoaSubOut;
};

export type QuanTriXoaSubResponse = QuanTriXoaSubResponses[keyof QuanTriXoaSubResponses];

export type QuanTriSuaSubData = {
    body: SuaSubIn;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/admin/subs/{slug}';
};

export type QuanTriSuaSubErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
};

export type QuanTriSuaSubError = QuanTriSuaSubErrors[keyof QuanTriSuaSubErrors];

export type QuanTriSuaSubResponses = {
    /**
     * OK
     */
    200: SubQuanTriOut;
};

export type QuanTriSuaSubResponse = QuanTriSuaSubResponses[keyof QuanTriSuaSubResponses];

export type QuanTriGanModSubData = {
    body: GanModSubIn;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/admin/subs/{slug}/mods';
};

export type QuanTriGanModSubErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
    /**
     * Conflict
     */
    409: LoiOut;
};

export type QuanTriGanModSubError = QuanTriGanModSubErrors[keyof QuanTriGanModSubErrors];

export type QuanTriGanModSubResponses = {
    /**
     * OK
     */
    200: SubQuanTriOut;
};

export type QuanTriGanModSubResponse = QuanTriGanModSubResponses[keyof QuanTriGanModSubResponses];

export type QuanTriGoModSubData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
        /**
         * Username
         */
        username: string;
    };
    query?: never;
    url: '/api/admin/subs/{slug}/mods/{username}';
};

export type QuanTriGoModSubErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
    /**
     * Conflict
     */
    409: LoiOut;
};

export type QuanTriGoModSubError = QuanTriGoModSubErrors[keyof QuanTriGoModSubErrors];

export type QuanTriGoModSubResponses = {
    /**
     * OK
     */
    200: SubQuanTriOut;
};

export type QuanTriGoModSubResponse = QuanTriGoModSubResponses[keyof QuanTriGoModSubResponses];

export type QuanTriThongKeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/thong-ke';
};

export type QuanTriThongKeErrors = {
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
};

export type QuanTriThongKeError = QuanTriThongKeErrors[keyof QuanTriThongKeErrors];

export type QuanTriThongKeResponses = {
    /**
     * OK
     */
    200: ThongKeOut;
};

export type QuanTriThongKeResponse = QuanTriThongKeResponses[keyof QuanTriThongKeResponses];

export type QuanTriLietKeNguoiDungData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Q
         */
        q?: string;
        /**
         * Trang Thai
         */
        trang_thai?: 'tat_ca' | 'moi_nguoi' | 'bi_ban' | 'staff' | 'moi';
        /**
         * Limit
         */
        limit?: number;
        /**
         * Cursor
         */
        cursor?: string | null;
    };
    url: '/api/admin/users';
};

export type QuanTriLietKeNguoiDungErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
};

export type QuanTriLietKeNguoiDungError = QuanTriLietKeNguoiDungErrors[keyof QuanTriLietKeNguoiDungErrors];

export type QuanTriLietKeNguoiDungResponses = {
    /**
     * OK
     */
    200: TrangNguoiDungOut;
};

export type QuanTriLietKeNguoiDungResponse = QuanTriLietKeNguoiDungResponses[keyof QuanTriLietKeNguoiDungResponses];

export type QuanTriXemNguoiDungData = {
    body?: never;
    path: {
        /**
         * Username
         */
        username: string;
    };
    query?: never;
    url: '/api/admin/users/{username}';
};

export type QuanTriXemNguoiDungErrors = {
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
};

export type QuanTriXemNguoiDungError = QuanTriXemNguoiDungErrors[keyof QuanTriXemNguoiDungErrors];

export type QuanTriXemNguoiDungResponses = {
    /**
     * OK
     */
    200: NguoiDungQuanTriOut;
};

export type QuanTriXemNguoiDungResponse = QuanTriXemNguoiDungResponses[keyof QuanTriXemNguoiDungResponses];

export type QuanTriSuaNguoiDungData = {
    body: SuaNguoiDungIn;
    path: {
        /**
         * Username
         */
        username: string;
    };
    query?: never;
    url: '/api/admin/users/{username}';
};

export type QuanTriSuaNguoiDungErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
    /**
     * Conflict
     */
    409: LoiOut;
};

export type QuanTriSuaNguoiDungError = QuanTriSuaNguoiDungErrors[keyof QuanTriSuaNguoiDungErrors];

export type QuanTriSuaNguoiDungResponses = {
    /**
     * OK
     */
    200: NguoiDungQuanTriOut;
};

export type QuanTriSuaNguoiDungResponse = QuanTriSuaNguoiDungResponses[keyof QuanTriSuaNguoiDungResponses];

export type QuanTriBanNguoiDungData = {
    body: BanIn;
    path: {
        /**
         * Username
         */
        username: string;
    };
    query?: never;
    url: '/api/admin/users/{username}/ban';
};

export type QuanTriBanNguoiDungErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
    /**
     * Conflict
     */
    409: LoiOut;
};

export type QuanTriBanNguoiDungError = QuanTriBanNguoiDungErrors[keyof QuanTriBanNguoiDungErrors];

export type QuanTriBanNguoiDungResponses = {
    /**
     * OK
     */
    200: KetQuaDoiTrangThaiOut;
};

export type QuanTriBanNguoiDungResponse = QuanTriBanNguoiDungResponses[keyof QuanTriBanNguoiDungResponses];

export type QuanTriGoBanNguoiDungData = {
    body?: never;
    path: {
        /**
         * Username
         */
        username: string;
    };
    query?: never;
    url: '/api/admin/users/{username}/go-ban';
};

export type QuanTriGoBanNguoiDungErrors = {
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
};

export type QuanTriGoBanNguoiDungError = QuanTriGoBanNguoiDungErrors[keyof QuanTriGoBanNguoiDungErrors];

export type QuanTriGoBanNguoiDungResponses = {
    /**
     * OK
     */
    200: KetQuaDoiTrangThaiOut;
};

export type QuanTriGoBanNguoiDungResponse = QuanTriGoBanNguoiDungResponses[keyof QuanTriGoBanNguoiDungResponses];

export type QuanTriDatMatKhauData = {
    body: DatMatKhauIn;
    path: {
        /**
         * Username
         */
        username: string;
    };
    query?: never;
    url: '/api/admin/users/{username}/mat-khau';
};

export type QuanTriDatMatKhauErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
    /**
     * Conflict
     */
    409: LoiOut;
};

export type QuanTriDatMatKhauError = QuanTriDatMatKhauErrors[keyof QuanTriDatMatKhauErrors];

export type QuanTriDatMatKhauResponses = {
    /**
     * OK
     */
    200: NguoiDungQuanTriOut;
};

export type QuanTriDatMatKhauResponse = QuanTriDatMatKhauResponses[keyof QuanTriDatMatKhauResponses];

export type QuanTriDoiQuyenModData = {
    body: DoiQuyenModIn;
    path: {
        /**
         * Username
         */
        username: string;
    };
    query?: never;
    url: '/api/admin/users/{username}/quyen-mod';
};

export type QuanTriDoiQuyenModErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
    /**
     * Conflict
     */
    409: LoiOut;
};

export type QuanTriDoiQuyenModError = QuanTriDoiQuyenModErrors[keyof QuanTriDoiQuyenModErrors];

export type QuanTriDoiQuyenModResponses = {
    /**
     * OK
     */
    200: NguoiDungQuanTriOut;
};

export type QuanTriDoiQuyenModResponse = QuanTriDoiQuyenModResponses[keyof QuanTriDoiQuyenModResponses];
