// SINH TỰ ĐỘNG bởi `pnpm codegen` từ OpenAPI của Django Ninja.
// KHÔNG SỬA TAY — mọi thay đổi sẽ mất ở lần codegen kế tiếp.
// This file is auto-generated by @hey-api/openapi-ts

export { getHealth, type Options } from './sdk.gen';
export type { ClientOptions, GetHealthData, GetHealthError, GetHealthErrors, GetHealthResponse, GetHealthResponses, HealthOut } from './types.gen';
