// SINH TỰ ĐỘNG bởi `pnpm codegen` từ OpenAPI của Django Ninja.
// KHÔNG SỬA TAY — mọi thay đổi sẽ mất ở lần codegen kế tiếp.
// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { BoTheoMachData, BoTheoMachErrors, BoTheoMachResponses, DanhDauDaDocData, DanhDauDaDocErrors, DanhDauDaDocResponses, DanhDauDaXemData, DanhDauDaXemErrors, DanhDauDaXemResponses, DatReactionData, DatReactionErrors, DatReactionResponses, DatVoteData, DatVoteErrors, DatVoteResponses, DongSoMachData, DongSoMachErrors, DongSoMachResponses, GetHealthData, GetHealthErrors, GetHealthResponses, GoTrichData, GoTrichErrors, GoTrichResponses, LietKeBanCuMocData, LietKeBanCuMocErrors, LietKeBanCuMocResponses, LietKeBinhLuanMachData, LietKeBinhLuanMachErrors, LietKeBinhLuanMachResponses, LietKeBinhLuanMocData, LietKeBinhLuanMocErrors, LietKeBinhLuanMocResponses, LietKeFeedDangDienRaData, LietKeFeedDangDienRaErrors, LietKeFeedDangDienRaResponses, LietKeFeedMoiData, LietKeFeedMoiErrors, LietKeFeedMoiResponses, LietKeSubData, LietKeSubResponses, LietKeThongBaoData, LietKeThongBaoErrors, LietKeThongBaoResponses, MoLaiMachData, MoLaiMachErrors, MoLaiMachResponses, NoiMocData, NoiMocErrors, NoiMocResponses, SuaBinhLuanData, SuaBinhLuanErrors, SuaBinhLuanResponses, SuaMocData, SuaMocErrors, SuaMocResponses, TaoMachData, TaoMachErrors, TaoMachResponses, TheoMachData, TheoMachErrors, TheoMachResponses, TrichVaoSoData, TrichVaoSoErrors, TrichVaoSoResponses, VietBinhLuanData, VietBinhLuanErrors, VietBinhLuanResponses, XemHoSoData, XemHoSoErrors, XemHoSoResponses, XemMachCuaToiData, XemMachCuaToiErrors, XemMachCuaToiResponses, XemMachData, XemMachErrors, XemMachResponses, XemSubData, XemSubErrors, XemSubResponses, XemToiData, XemToiResponses, XoaBinhLuanData, XoaBinhLuanErrors, XoaBinhLuanResponses, XoaMocData, XoaMocErrors, XoaMocResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Xoa Binh Luan Api
 *
 * Xoá bình luận theo **luật hai vế** của PLAN 5.3 — nợ 1a bàn giao, trả ở đây.
 *
 * **Quyền: CHỈ tác giả của bình luận.** Mạch bị mod khoá ⇒ 403; đã xoá rồi ⇒ 409.
 *
 * Luật, nguyên văn: giữ chỗ "[đã xoá]" nếu **có reply con** HOẶC **đã TỪNG được trích
 * vào sổ (kể cả trích đã gỡ)**; xoá thật chỉ khi không dính cả hai. Chữ "đã TỪNG" khớp
 * đúng `Trich.comment = PROTECT` — `PROTECT` chặn theo hàng, nó không biết `removed_at`
 * là gì. Đọc thành "đang được trích" là tiền-kiểm `removed_at IS NULL`, quyết "xoá
 * thật", rồi ăn `ProtectedError` ⇒ 500 trên một thao tác hợp lệ của chính chủ.
 *
 * **Xoá thật thì dọn `Vote` mồ côi trong cùng transaction** — `Vote` cố ý không có FK
 * tới đích nên không có `ON DELETE` nào; nợ này ghi sẵn trong docstring của model từ 1a.
 *
 * `xoa_that = false` nghĩa là nút ở lại làm bia mộ: UI phải **render lại** nó chứ không
 * gỡ khỏi cây, nếu không cả nhánh con mất chỗ bám.
 */
export const xoaBinhLuan = <ThrowOnError extends boolean = false>(options: Options<XoaBinhLuanData, ThrowOnError>): RequestResult<XoaBinhLuanResponses, XoaBinhLuanErrors, ThrowOnError> => (options.client ?? client).delete<XoaBinhLuanResponses, XoaBinhLuanErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/v1/comments/{comment_id}',
    ...options
});

/**
 * Sua Binh Luan Api
 *
 * Sửa bình luận: đổi `body`, hiện dấu `*đã sửa*` (PLAN 5.3).
 *
 * **Quyền: CHỈ tác giả của bình luận** — 403 `khong_phai_chu` cho mọi người khác, kể cả
 * chủ mạch. Chủ mạch có quyền trên *cuốn sổ*, không có quyền trên *lời của người khác*.
 * Mạch bị mod khoá ⇒ 403; bình luận đã là bia mộ hoặc bị ẩn ⇒ 409.
 *
 * **Không có cửa sổ sửa im lặng 15 phút** như mốc, và đó là chủ đích: mốc là *bằng
 * chứng* nên nó cần lịch sử bản cũ, bình luận là *tán gẫu* nên nó chỉ cần nói ra rằng đã
 * sửa. `anchor_moc_seq` **không** sửa được — đổi neo sau khi thread đã có reply là dời
 * cả thread sang một ngăn kéo khác dưới chân người đang đọc.
 *
 * Trả về nút bình luận **không kèm `replies`** (mảng rỗng): endpoint này sửa đúng một
 * dòng, và trả cả nhánh con là mời UI thay nguyên nhánh bằng dữ liệu nó không hỏi.
 */
export const suaBinhLuan = <ThrowOnError extends boolean = false>(options: Options<SuaBinhLuanData, ThrowOnError>): RequestResult<SuaBinhLuanResponses, SuaBinhLuanErrors, ThrowOnError> => (options.client ?? client).patch<SuaBinhLuanResponses, SuaBinhLuanErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/v1/comments/{comment_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Feed Dang Dien Ra
 *
 * Feed **Đang diễn ra**: mạch còn mở, mốc mới nhất trước
 * (`last_entry_at` giảm dần).
 *
 * Feed đặc sản của gikky, **không phải** Hot: mốc mới không "bump" bài, nó chỉ cập nhật
 * khoá sort của riêng feed này.
 *
 * `last_entry_at` đo **cấu trúc** — mọi mốc đều tính, kể cả mốc bị mod ẩn. Vì thế một
 * mạch có thể đứng đầu feed này mà mở ra là **mặt CẶN** (`face` tính theo
 * `last_activity_at`, vốn chỉ đo nội dung đọc được). Đó là hành vi đúng theo luật đếm
 * hiện hành, đã ghi ở PLAN mục 6 "hệ quả cố ý 2" — đừng chữa bằng cách đổi khoá sort.
 *
 * `?sub=<slug>` lọc theo chuyên mục; sub không tồn tại trả 404 `sub_khong_ton_tai`.
 * `?cursor=` là cursor keyset lấy từ `cursor_ke_tiep` của trang trước; `null` là hết.
 * `?limit=` tối đa 50.
 *
 * `?sort=tu_nhien` (mặc định) giữ khoá sort riêng của feed này. `?sort=nhieu_diem` sắp
 * theo điểm bài gốc giảm dần, cursor keyset trên `(diem, id)`. **Cursor của sort này
 * KHÔNG dùng được cho sort kia** — đem nhầm là 400 `cursor_khong_hop_le`.
 *
 * `?khoang=ngay|tuan|thang|tat_ca` (mặc định `tat_ca`) lọc theo `created_at`, ranh giới
 * là nửa đêm **giờ VN**; `tuan` = 7 ngày lịch gần nhất kể cả hôm nay, `thang` = 30 ngày.
 * Khoảng áp cho **mọi** sort, không riêng `nhieu_diem`. Giá trị lạ trả 400
 * `tham_so_khong_hop_le` — không bao giờ lặng lẽ quy về `tat_ca`.
 *
 * Mạch bị mod ẩn không xuất hiện.
 *
 */
export const lietKeFeedDangDienRa = <ThrowOnError extends boolean = false>(options?: Options<LietKeFeedDangDienRaData, ThrowOnError>): RequestResult<LietKeFeedDangDienRaResponses, LietKeFeedDangDienRaErrors, ThrowOnError> => (options?.client ?? client).get<LietKeFeedDangDienRaResponses, LietKeFeedDangDienRaErrors, ThrowOnError>({ url: '/api/v1/feeds/dang-dien-ra', ...options });

/**
 * Feed Moi
 *
 * Feed **Mới**: mọi bài, mới đăng trước (`created_at` giảm dần).
 *
 * Mạch đã đóng sổ **vẫn xuất hiện** — feed này sắp theo lúc bài ra đời, không theo
 * trạng thái sổ.
 *
 * `?sub=<slug>` lọc theo chuyên mục; sub không tồn tại trả 404 `sub_khong_ton_tai`.
 * `?cursor=` là cursor keyset lấy từ `cursor_ke_tiep` của trang trước; `null` là hết.
 * `?limit=` tối đa 50.
 *
 * `?sort=tu_nhien` (mặc định) giữ khoá sort riêng của feed này. `?sort=nhieu_diem` sắp
 * theo điểm bài gốc giảm dần, cursor keyset trên `(diem, id)`. **Cursor của sort này
 * KHÔNG dùng được cho sort kia** — đem nhầm là 400 `cursor_khong_hop_le`.
 *
 * `?khoang=ngay|tuan|thang|tat_ca` (mặc định `tat_ca`) lọc theo `created_at`, ranh giới
 * là nửa đêm **giờ VN**; `tuan` = 7 ngày lịch gần nhất kể cả hôm nay, `thang` = 30 ngày.
 * Khoảng áp cho **mọi** sort, không riêng `nhieu_diem`. Giá trị lạ trả 400
 * `tham_so_khong_hop_le` — không bao giờ lặng lẽ quy về `tat_ca`.
 *
 * Mạch bị mod ẩn không xuất hiện.
 *
 */
export const lietKeFeedMoi = <ThrowOnError extends boolean = false>(options?: Options<LietKeFeedMoiData, ThrowOnError>): RequestResult<LietKeFeedMoiResponses, LietKeFeedMoiErrors, ThrowOnError> => (options?.client ?? client).get<LietKeFeedMoiResponses, LietKeFeedMoiErrors, ThrowOnError>({ url: '/api/v1/feeds/moi', ...options });

/**
 * Health
 *
 * `SELECT 1` thật xuống DB.
 *
 * DB sống → 200 `{"status":"ok","db":"ok"}`; DB hỏng hoặc trả kết quả sai → 503
 * `{"status":"fail","db":"fail"}`.
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>): RequestResult<GetHealthResponses, GetHealthErrors, ThrowOnError> => (options?.client ?? client).get<GetHealthResponses, GetHealthErrors, ThrowOnError>({ url: '/api/v1/health', ...options });

/**
 * Tao Mach Api
 *
 * Đăng bài = tạo `Mach` + `Moc(seq=1)` trong MỘT giao dịch (PLAN 5.1).
 *
 * **Quyền: bất kỳ ai đã đăng nhập và không bị khoá.** Không có "chủ" để đối chiếu —
 * người gọi *trở thành* chủ. Tài khoản bị ban bị chặn ở lớp auth (`api/quyen.py`).
 *
 * Không có nút "tạo mạch" riêng (PLAN nguyên tắc 1): mọi post sinh ra là post thường,
 * UI mạch tự bật từ mốc 2. Vì thế endpoint này và `POST /machs/{id}/mocs` nhận **cùng
 * một bộ trường nội dung** — `MachMoiIn` kế thừa thẳng `MocMoiIn`.
 *
 * Tác giả nhận **+1 phiếu của chính mình** ngay lúc đăng (PLAN 5.7) — để `0` trên cột
 * vote có nghĩa là "đã có người vote xuống", không phải "chưa ai đụng tới".
 */
export const taoMach = <ThrowOnError extends boolean = false>(options: Options<TaoMachData, ThrowOnError>): RequestResult<TaoMachResponses, TaoMachErrors, ThrowOnError> => (options.client ?? client).post<TaoMachResponses, TaoMachErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/v1/machs',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Xem Mach
 *
 * Trang mạch: thông tin mạch + **toàn bộ** mốc + `face` + spine.
 *
 * `id` là khoá bền của mạch (PLAN 5.9). Endpoint **không nhận slug** — URL
 * `/m/<slug>-<id>` có slug cũ hay slug sai vẫn ra đúng mạch này, còn chuyện redirect
 * 301 về slug chuẩn là việc của tầng web, dựa vào trường `slug` trong response.
 *
 * Response **không chứa trường nào phụ thuộc người xem** nên cache được (PLAN 8.4);
 * vote của tôi / đã theo chưa / đọc tới đâu nằm ở `GET /machs/{id}/me` (Phase 3).
 *
 * Mốc đã xoá hoặc bị mod ẩn vẫn có mặt trong `mocs` và `spine` dưới dạng **bia mộ giữ
 * chỗ**, không kèm nội dung: `seq` bất biến, giấu hẳn một ô là thủng dãy số và phá bất
 * biến `entry_count == số ô trên spine` (PLAN 5.2).
 */
export const xemMach = <ThrowOnError extends boolean = false>(options: Options<XemMachData, ThrowOnError>): RequestResult<XemMachResponses, XemMachErrors, ThrowOnError> => (options.client ?? client).get<XemMachResponses, XemMachErrors, ThrowOnError>({ url: '/api/v1/machs/{mach_id}', ...options });

/**
 * Dong So Mach
 *
 * Đóng sổ — PLAN 5.1. **Quyền: CHỈ tác giả mạch** (403 cho người khác).
 *
 * `ket_qua` là một dòng tự do ≤40 ký tự ("+18.2% · 163 ngày"), hiện ở banner mặt CẶN và
 * OG card. **Thuần hiển thị** — server không validate ngữ nghĩa, cùng triết lý với
 * `figures`. Không nhập ⇒ `null`, banner ẩn phần đó.
 *
 * Mạch đã đóng rồi thì 409 `mach_da_dong` chứ không phải "đóng lại lần nữa": đóng sổ
 * lần hai sẽ ghi đè `closed_at`, và cái đó **dời hạn 7 ngày mở lại** — tức một cách vô
 * hạn hoá cái hạn đó bằng cách bấm hai lần.
 */
export const dongSoMach = <ThrowOnError extends boolean = false>(options: Options<DongSoMachData, ThrowOnError>): RequestResult<DongSoMachResponses, DongSoMachErrors, ThrowOnError> => (options.client ?? client).post<DongSoMachResponses, DongSoMachErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/v1/machs/{mach_id}/close',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Liet Ke Binh Luan Mach
 *
 * Khán đài: **cây bình luận đã dựng sẵn**, server sắp xếp (PLAN mục 7).
 *
 * `?sort=hay_nhat|moi_nhat|cu_nhat`, mặc định `hay_nhat`. Sort không thuộc ba giá trị
 * đó trả 400 `sort_khong_hop_le` — API **không bao giờ tự đổi sort ngầm** dưới tay
 * người dùng (PLAN nguyên tắc 7).
 *
 * - `hay_nhat`: wilson (z = 1.281) cộng hệ số tươi 0.15 cho bình luận **gốc** ra đời
 * sau mốc mới nhất và còn trong 48 giờ đầu đời của nó. Sibling trong thread sắp theo
 * wilson **thuần** — hệ số tươi không áp cho reply. Phân trang bằng `?offset=`,
 * `?limit=` tối đa 50.
 * - `moi_nhat` / `cu_nhat`: `?cursor=` keyset trên `(created_at, id)`.
 *
 * **Hai kiểu phân trang KHÔNG dùng lẫn nhau, dùng nhầm trả 400** với
 * `code = "tham_so_khong_hop_le"`: `?cursor=` kèm `sort=hay_nhat`, hoặc `?offset=` khác
 * 0 kèm hai sort thời gian. Nuốt im lặng tham số sai chỗ là hành vi mà chính
 * `api/phan_trang.py` cấm cho cursor rác: người ở trang 3 của `moi_nhat` bấm đổi sang
 * `hay_nhat`, router giữ nguyên query string, API trả **trang 1** kèm HTTP 200 — UI
 * tưởng mình vẫn ở trang 3 và append tiếp ⇒ lặp dòng hoặc mất dòng, không lần ra được.
 *
 * Bình luận bị mod ẩn, hoặc tác giả tự xoá, chỉ còn lại **bia mộ giữ chỗ** khi nó còn
 * con sống sót trong `replies` — và riêng ca tác giả tự xoá thì cả khi bình luận **đã
 * từng được trích vào sổ**, kể cả trích đã gỡ (PLAN 5.3). Không dính vế nào thì nó biến
 * mất hẳn. "Con sống sót" không có nghĩa "con đọc được": con ấy có thể tự nó là bia mộ,
 * nên một thread trong `threads` có thể **toàn bia mộ, không một chữ nội dung nào**, mà
 * vẫn chiếm một chỗ trong `tong_thread` và một slot của trang này.
 * Bia mộ không được tính vào `comment_count` của mạch, nên số bình luận **đọc được** có
 * thể nhỏ hơn số dòng trả về.
 *
 * ### `?dang_doc=1` — "câu đáng đọc" (PLAN 5.5)
 *
 * Trả **phép hợp `đã trích ∪ top-10 theo wilson`** trên các thread GỐC, sắp theo wilson
 * **thuần** giảm dần. Đây là khối gắn nhãn "Câu đáng đọc" nằm trên cùng khi chân trang
 * mặt CẶN bung khán đài; cây đầy đủ vẫn lấy bằng một lời gọi thường (không có tham số
 * này).
 *
 * Phép hợp là hợp THẬT: một bình luận được trích nhưng xếp hạng thấp **vẫn có mặt**.
 * Không có phân trang ở chế độ này — tập tối đa là `10 + số mốc có trích`, và
 * `offset_ke_tiep`/`cursor_ke_tiep` luôn `null`, `tong_thread` là kích thước của tập.
 *
 * Chế độ này (và **chỉ** chế độ này) trả thêm `so_ung_vien_bo_lai`: số thread gốc đọc
 * được nằm ngoài tập. `0` nghĩa là khối không lọc được gì và UI phải ẩn nó đi (PLAN 5.5,
 * ngoại lệ "tập = cả khán đài"). Đừng suy con số ấy bằng cách so `tong_thread` của hai
 * lời gọi — hai đầu đếm bia mộ khác nhau, xem `KhanDaiOut` (Y1, lượt vá 4).
 *
 * Vì tập này có thứ tự riêng, `?dang_doc=1` **chỉ đi cùng `sort=hay_nhat`** (mặc định)
 * và **không nhận `offset`/`cursor`/`limit`** — dùng lẫn trả 400
 * `tham_so_khong_hop_le` thay vì lặng lẽ bỏ qua tham số, đúng luật đang áp cho hai kiểu
 * phân trang ở trên. `limit` là **cửa thứ tư của cùng cái luật ấy** (vá V7,
 * 2026-08-22): nhánh này không đọc `limit` ở đâu cả, nên `?dang_doc=1&limit=5` trước đó
 * trả 200 kèm 11 thread — người gọi tưởng mình đã cắt còn 5.
 *
 * `limit` mặc định là `None` chứ không phải `GIOI_HAN_TOI_DA`, và đó là cả cách phép
 * kiểm trên đứng được: với mặc định là một con số thì "không truyền" và "truyền đúng 50"
 * trông y hệt nhau ở trong hàm, nên hoặc là bỏ qua im lặng, hoặc là 400 cho một lời gọi
 * không sai gì.
 */
export const lietKeBinhLuanMach = <ThrowOnError extends boolean = false>(options: Options<LietKeBinhLuanMachData, ThrowOnError>): RequestResult<LietKeBinhLuanMachResponses, LietKeBinhLuanMachErrors, ThrowOnError> => (options.client ?? client).get<LietKeBinhLuanMachResponses, LietKeBinhLuanMachErrors, ThrowOnError>({ url: '/api/v1/machs/{mach_id}/comments', ...options });

/**
 * Viet Binh Luan
 *
 * Viết bình luận vào khán đài hoặc ngăn kéo — PLAN 5.4, nguyên tắc 4 và 6.
 *
 * **Quyền: bất kỳ ai đã đăng nhập.** Không phải chỉ tác giả — khán đài là chỗ của đám
 * đông. Chặn duy nhất là mạch bị mod **khoá** (403 `mach_bi_khoa`).
 * **Mạch đã đóng sổ VẪN bình luận được** (PLAN 5.1) — đó là khác biệt cố ý so với
 * `POST /machs/{id}/mocs`, đừng "dọn dẹp" hai đường này thành một phép kiểm.
 *
 * `anchor_moc_seq` **chỉ đặt được trên bình luận gốc**; gửi kèm `parent_id` là 400. Neo
 * trỏ vào một `seq` không tồn tại trong mạch cũng là 400 — chip `‹mốc 12›` trên một mạch
 * 9 mốc mở ra một ngăn kéo không có thật.
 *
 * `parent_id` phải thuộc **cùng mạch**: reply xuyên mạch sẽ dựng một nhánh mà cả hai
 * trang đều không hiển thị đúng.
 *
 * Người viết nhận +1 phiếu của chính mình (PLAN 5.7).
 */
export const vietBinhLuan = <ThrowOnError extends boolean = false>(options: Options<VietBinhLuanData, ThrowOnError>): RequestResult<VietBinhLuanResponses, VietBinhLuanErrors, ThrowOnError> => (options.client ?? client).post<VietBinhLuanResponses, VietBinhLuanErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/v1/machs/{mach_id}/comments',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Bo Theo Mach
 *
 * Bỏ theo mạch — PLAN 5.7. **Idempotent**: bỏ theo thứ vốn không theo vẫn là 200.
 *
 * **Quyền: bất kỳ ai đã đăng nhập**, và chỉ xoá được hàng của chính họ.
 *
 * Trả `following: false` và `last_seen_entry_seq: 0`. Con số `0` ở đây nói đúng sự thật:
 * hàng `Follow` bị xoá nên vị trí đọc mất theo, và theo lại là bắt đầu từ `entry_count`
 * lúc đó (xem `core.ghi.bo_follow`).
 *
 * Mạch bị mod **khoá** vẫn bỏ theo được, và cửa này là lý do chính của quyết định ấy —
 * xem docstring module.
 */
export const boTheoMach = <ThrowOnError extends boolean = false>(options: Options<BoTheoMachData, ThrowOnError>): RequestResult<BoTheoMachResponses, BoTheoMachErrors, ThrowOnError> => (options.client ?? client).delete<BoTheoMachResponses, BoTheoMachErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/v1/machs/{mach_id}/follow',
    ...options
});

/**
 * Theo Mach
 *
 * Theo mạch — "Theo mạch", PLAN 5.7. Follower nhận thông báo khi có mốc mới.
 *
 * **Quyền: bất kỳ ai đã đăng nhập**, kể cả tác giả trên mạch của chính mình (vô hại:
 * `core/thong_bao.py::bao_moc_moi` loại người viết ra khỏi danh sách nhận, nên tự theo
 * không sinh chuông nào). Chỉ ghi vào hàng của chính người gọi.
 *
 * **Idempotent**: bấm lần thứ hai trả về đúng trạng thái cũ, và **không** đụng
 * `last_seen_entry_seq` — hàng đã có nghĩa là vị trí đọc đã có, ghi đè nó là xoá dấu đọc
 * dở của chính người đang bấm.
 *
 * Lượt theo ĐẦU TIÊN đặt `last_seen_entry_seq = entry_count`, không phải `0`: người ta
 * theo để biết chuyện **sắp** xảy ra (xem `core.ghi.dat_follow`).
 *
 * Mạch bị mod **khoá** vẫn theo được — xem docstring module.
 */
export const theoMach = <ThrowOnError extends boolean = false>(options: Options<TheoMachData, ThrowOnError>): RequestResult<TheoMachResponses, TheoMachErrors, ThrowOnError> => (options.client ?? client).post<TheoMachResponses, TheoMachErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/v1/machs/{mach_id}/follow',
    ...options
});

/**
 * Xem Mach Cua Toi
 *
 * Trạng thái của **người đang xem** trên mạch này — PLAN mục 7, 8.4 điểm 4.
 *
 * **Không bao giờ cache được.** Đây là nửa per-user của trang mạch: phiếu của tôi,
 * reaction của tôi, tôi có theo mạch không, tôi đọc tới mốc nào. Client component gọi nó
 * **sau khi** trang đã render từ cache; tuyệt đối không nướng nội dung này vào HTML.
 *
 * **Khách chưa đăng nhập nhận 200**, không phải 401 — hai danh sách rỗng,
 * `following = false`, `last_seen_entry_seq = 0`. Cùng lý lẽ `GET /me` (PLAN mục 7):
 * endpoint này chạy trên MỌI lượt tải trang mạch, kể cả của bot, nên trả lỗi cho trạng
 * thái bình thường nhất của hệ thống là dạy frontend coi lỗi là chuyện thường. `face` của
 * khách vì thế bằng đúng `face` của `GET /machs/{id}`.
 *
 * `face` ở đây áp **đủ hai vế** của PLAN 5.5: vế thời gian, HOẶC "user đăng nhập VÀ đã
 * follow hoặc từng bình luận mạch này". Vì là phép HOẶC nên nó chỉ kéo được CẶN → BÃO.
 * Server quyết, frontend không tính lại (PLAN nguyên tắc 10).
 *
 * Mạch bị mod ẩn ⇒ **404**, cùng mã với mọi cửa công khai khác: trả trạng thái viewer cho
 * một mạch đã bị gỡ là xác nhận nó tồn tại.
 *
 * Không cần đăng nhập nên **không khai `auth=`** — nó là endpoint GET, không có gì để
 * CSRF bảo vệ, và luật "mọi operation không-GET phải có auth"
 * (`tests/test_quyen_ghi.py`) vì thế không đụng tới nó.
 */
export const xemMachCuaToi = <ThrowOnError extends boolean = false>(options: Options<XemMachCuaToiData, ThrowOnError>): RequestResult<XemMachCuaToiResponses, XemMachCuaToiErrors, ThrowOnError> => (options.client ?? client).get<XemMachCuaToiResponses, XemMachCuaToiErrors, ThrowOnError>({ url: '/api/v1/machs/{mach_id}/me', ...options });

/**
 * Noi Moc
 *
 * Nối một mốc vào mạch — PLAN 5.1.
 *
 * **Quyền: CHỈ tác giả mạch.** Người khác nhận 403 `khong_phai_chu`. Mạch là nhật ký
 * của một người; nếu ai cũng nối được thì "dấu thời gian máy chủ bất biến" chẳng chứng
 * minh được ai đã ghi cái gì.
 *
 * Ba điều kiện nữa, mỗi cái một mã riêng để UI nói đúng chuyện:
 * - mạch bị mod **khoá** ⇒ 403 `mach_bi_khoa` (đọc được, cấm tương tác — PLAN 5.10);
 * - mạch **đã đóng sổ** ⇒ 409 `mach_da_dong` (đóng sổ vẫn bình luận được, chỉ không nối
 * mốc — PLAN 5.1);
 * - quá **3 mốc trong ngày lịch VN** ⇒ 429 `qua_han_muc_moc`. Hạn mức đếm theo
 * `created_at` (dấu server) và tính **mọi** mốc kể cả bia mộ — xoá rồi viết lại là
 * cách lách ngắn nhất. Ranh giới là nửa đêm giờ VN, không phải 24 giờ trượt.
 *
 * `occurred_at` nhập lùi thoải mái, cấm tương lai (PLAN 5.2). Tác giả nhận +1 phiếu của
 * chính mình (PLAN 5.7).
 */
export const noiMoc = <ThrowOnError extends boolean = false>(options: Options<NoiMocData, ThrowOnError>): RequestResult<NoiMocResponses, NoiMocErrors, ThrowOnError> => (options.client ?? client).post<NoiMocResponses, NoiMocErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/v1/machs/{mach_id}/mocs',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Mo Lai Mach
 *
 * Mở lại mạch đã đóng sổ — **trong 7 ngày**, sau đó nút biến mất (PLAN 5.1).
 *
 * **Quyền: CHỈ tác giả mạch.** Quá hạn ⇒ 409 `het_han_mo_lai`; mạch đang mở ⇒ 409
 * `mach_dang_mo`.
 *
 * Hạn tính từ `closed_at`, và nó là hạn THẬT chứ không phải gợi ý UI: một cuốn sổ mở
 * lại được vô thời hạn thì "đã đóng sổ" không còn nghĩa gì, mà đó là nhãn cả mặt CẶN
 * lẫn OG card đang dựa vào.
 *
 * `ket_qua` **bị xoá theo** — xem `core/ghi.py::mo_lai`.
 */
export const moLaiMach = <ThrowOnError extends boolean = false>(options: Options<MoLaiMachData, ThrowOnError>): RequestResult<MoLaiMachResponses, MoLaiMachErrors, ThrowOnError> => (options.client ?? client).post<MoLaiMachResponses, MoLaiMachErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/v1/machs/{mach_id}/reopen',
    ...options
});

/**
 * Danh Dau Da Xem
 *
 * Ghi vị trí đọc — nền của **vạch mới** ở mặt BÃO (PLAN 5.5).
 *
 * **Quyền: bất kỳ ai đã đăng nhập, và chỉ ghi vào hàng `Follow` của CHÍNH HỌ.** Không có
 * tham số nào chỉ ra người khác, nên không có đường nào đặt vị trí đọc hộ ai.
 *
 * `entry_seq` vắng mặt ⇒ "đã xem tới mốc mới nhất", đúng ca PLAN 5.5 mô tả (thẻ mốc mới
 * nhất mở sẵn khi trang mở). Con số **chỉ tiến không lùi** và bị kẹp trần ở `entry_count`
 * — mở lại một mốc cũ trên spine không được kéo vạch mới về sau.
 *
 * **Chưa theo mạch ⇒ 200 kèm `following: false`, và KHÔNG ghi gì.**
 * `last_seen_entry_seq` sống trên hàng `Follow` (PLAN mục 6) nên người chưa theo không có
 * chỗ nào để lưu. Không tạo `Follow` hộ: đó là âm thầm bắt người ta theo mạch vì họ mở
 * một trang. Không trả 404: client sẽ phải hỏi trước xem mình có theo không, tức thêm một
 * round-trip cho một cái bookmark. Response nói thẳng là không lưu gì.
 *
 * Mạch bị mod **khoá** vẫn gọi được — xem docstring module.
 */
export const danhDauDaXem = <ThrowOnError extends boolean = false>(options: Options<DanhDauDaXemData, ThrowOnError>): RequestResult<DanhDauDaXemResponses, DanhDauDaXemErrors, ThrowOnError> => (options.client ?? client).post<DanhDauDaXemResponses, DanhDauDaXemErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/v1/machs/{mach_id}/seen',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Xem Toi
 *
 * Danh tính của phiên hiện tại. **Per-user tuyệt đối — không cache** (PLAN 8.4).
 *
 * Khách chưa đăng nhập nhận 200 kèm `dang_nhap: false` và mọi trường danh tính `null`.
 *
 * `email_da_xac_thuc` có mặt vì xác thực email là **bắt buộc** ở gikky: tài khoản chưa
 * xác thực thì đăng nhập được nhưng chưa nên được mời viết bài, và UI cần phân biệt hai
 * trạng thái đó thay vì để người dùng bấm rồi ăn lỗi.
 *
 * `google_bat` là cấu hình server, không phải trạng thái người dùng: `false` ⇒ trang
 * đăng nhập **không render** nút Google (PLAN mục 4 — không nút vĩnh viễn không bấm
 * được), chứ không render một nút `disabled`.
 *
 * Endpoint này **không** trả trạng thái ban, quyền chi tiết, hay bất cứ thứ gì của người
 * khác — nó chỉ nói về chính phiên đang gọi.
 */
export const xemToi = <ThrowOnError extends boolean = false>(options?: Options<XemToiData, ThrowOnError>): RequestResult<XemToiResponses, unknown, ThrowOnError> => (options?.client ?? client).get<XemToiResponses, unknown, ThrowOnError>({ url: '/api/v1/me', ...options });

/**
 * Xoa Moc Api
 *
 * Xoá mốc = **bia mộ** giữ chỗ, không bao giờ `DELETE` thật (PLAN nguyên tắc 2).
 *
 * **Quyền: CHỈ tác giả của mốc.** Mạch bị mod khoá ⇒ 403. Mốc đã bị gỡ rồi ⇒ 409.
 *
 * Trả về chính thẻ mốc ở trạng thái bia mộ (`trang_thai = "da_xoa"`, nội dung `null`)
 * chứ không trả 204: UI phải **render lại ô đó** chứ không gỡ nó khỏi timeline — `seq`
 * bất biến và spine phải đủ số ô, giấu hẳn một ô là thủng dãy số (PLAN 5.2).
 *
 * Xoá mốc **không** làm `entry_count`/`last_entry_at` lùi (chúng đo *cấu trúc*), nhưng
 * **có** làm `comment_count`/`last_activity_at` đổi (chúng đo *nội dung đọc được*) —
 * PLAN mục 6, luật đếm 4 cột.
 */
export const xoaMoc = <ThrowOnError extends boolean = false>(options: Options<XoaMocData, ThrowOnError>): RequestResult<XoaMocResponses, XoaMocErrors, ThrowOnError> => (options.client ?? client).delete<XoaMocResponses, XoaMocErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/v1/mocs/{moc_id}',
    ...options
});

/**
 * Sua Moc Api
 *
 * Sửa mốc — **đúng 5 trường** của PLAN 5.2, không gì khác.
 *
 * **Quyền: CHỈ tác giả của mốc** (`Moc.author`, không phải `Mach.author` — hai thứ đó
 * trùng nhau hôm nay vì chỉ tác giả nối được mốc, nhưng hỏi đúng cột là điều kiện để
 * chúng vẫn đúng khi đồng tác giả mở ra). Người khác nhận 403 `khong_phai_chu`.
 * Mạch bị mod khoá ⇒ 403; mốc đã là bia mộ hoặc bị ẩn ⇒ 409 `noi_dung_da_go`.
 *
 * **PATCH thật**: trường không gửi thì không đổi, trường gửi `null` thì xoá. `body`
 * không nhận `null` (mốc phải có thân) — schema chặn trước khi vào đây.
 *
 * Sửa **im lặng trong 15 phút** kể từ `created_at`; sau đó mỗi lần sửa tạo một
 * `MocRevision` lưu **đủ cả 5 trường bản trước** và tăng "đã sửa N lần". Có
 * `occurred_at` trong revision là bắt buộc: sửa lùi ngày sự việc mà không để vết là phá
 * đúng giá trị lõi "ghi-trước-khi-biết-kết-quả" của sản phẩm.
 *
 * `occurred_at` mới vẫn **cấm ngày tương lai** (theo giờ VN).
 */
export const suaMoc = <ThrowOnError extends boolean = false>(options: Options<SuaMocData, ThrowOnError>): RequestResult<SuaMocResponses, SuaMocErrors, ThrowOnError> => (options.client ?? client).patch<SuaMocResponses, SuaMocErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/v1/mocs/{moc_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Liet Ke Binh Luan Moc
 *
 * Ngăn kéo của một mốc: lát cắt bình luận neo vào mốc đó, **cũ → mới**.
 *
 * Lấy các thread có bình luận **gốc** mang `anchor_moc_seq` bằng `seq` của mốc này, và
 * lấy **cả thread** — reply viết ở thời điểm mốc nào cũng thuộc về thread của gốc
 * (PLAN nguyên tắc 6). Nhờ vậy ngăn kéo của mốc 2 kể được cả lời tiên tri lẫn cái kết.
 *
 * Không có tham số sắp xếp: ngăn kéo là cửa sổ chiếu vào khán đài, không phải một
 * phòng riêng (PLAN 5.4 luật 2). Anchor dùng để CHIẾU, không bao giờ để chia khán đài
 * thành nhiều phòng (PLAN nguyên tắc 4).
 *
 * Mốc chưa có bình luận nào trả `threads: []`, `so_binh_luan: 0` cùng
 * `question_for_crowd` nếu mốc có câu mồi — UI hiện lời mời chứ **không** hiện "💬 0"
 * (PLAN 5.4 luật 4, nguyên tắc 9).
 *
 * Ngăn kéo của một mốc đã thành **bia mộ vẫn mở được** (bình luận không biến mất theo
 * mốc), nhưng `question_for_crowd` khi đó là `null`: đó là nội dung của mốc, mà nội
 * dung của bia mộ thì không trả ra.
 */
export const lietKeBinhLuanMoc = <ThrowOnError extends boolean = false>(options: Options<LietKeBinhLuanMocData, ThrowOnError>): RequestResult<LietKeBinhLuanMocResponses, LietKeBinhLuanMocErrors, ThrowOnError> => (options.client ?? client).get<LietKeBinhLuanMocResponses, LietKeBinhLuanMocErrors, ThrowOnError>({ url: '/api/v1/mocs/{moc_id}/comments', ...options });

/**
 * Dat Reaction Api
 *
 * Reaction 1 chạm trên mốc — bộ **CỐ ĐỊNH** 📈📉🔥🧊🎯 (PLAN 5.7).
 *
 * **Quyền: bất kỳ ai đã đăng nhập**, kể cả trên mốc của chính mình. Mạch bị mod khoá ⇒
 * 403; mốc đã bị gỡ ⇒ 409.
 *
 * Một user **một** reaction mỗi mốc (`UNIQUE (user, moc)`) — đổi là `UPDATE`, không phải
 * thêm hàng: đây là "bậc thang tham gia rẻ hơn viết", không phải phiếu bầu nhiều lựa
 * chọn. `emoji = null` nghĩa là **rút**.
 *
 * Trả về **đủ 5 khoá kể cả khoá đang bằng 0**: UI vẽ nguyên bộ, và một khoá vắng mặt
 * trong response sẽ thành một icon nhấp nháy xuất hiện/biến mất theo lượt bấm.
 * Lưu khoá không dấu (`len`/`xuong`/…) chứ không lưu emoji — đổi bộ icon sau này không
 * phải migrate dữ liệu.
 */
export const datReaction = <ThrowOnError extends boolean = false>(options: Options<DatReactionData, ThrowOnError>): RequestResult<DatReactionResponses, DatReactionErrors, ThrowOnError> => (options.client ?? client).post<DatReactionResponses, DatReactionErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/v1/mocs/{moc_id}/reactions',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Liet Ke Ban Cu Moc
 *
 * Các bản TRƯỚC của một mốc, cho UI diff "đã sửa N lần" (PLAN 5.2).
 *
 * Mỗi bản lưu **đủ cả 5 trường sửa được** (`body`, `figures`, `occurred_at`, `loai`,
 * `question_for_crowd`), nên diff hiện được cả thay đổi ngày sự việc ("10/06 → 04/06")
 * — sửa lùi `occurred_at` mà không để vết là phá đúng giá trị lõi của sản phẩm.
 *
 * Mốc **đã xoá hoặc bị mod ẩn trả 404**: các bản cũ chứa nguyên văn nội dung, mở đường
 * này ra là gỡ mốc ở cửa trước còn đọc được ở cửa sau.
 *
 * Mốc chưa sửa lần nào trả `items: []`, không phải 404.
 */
export const lietKeBanCuMoc = <ThrowOnError extends boolean = false>(options: Options<LietKeBanCuMocData, ThrowOnError>): RequestResult<LietKeBanCuMocResponses, LietKeBanCuMocErrors, ThrowOnError> => (options.client ?? client).get<LietKeBanCuMocResponses, LietKeBanCuMocErrors, ThrowOnError>({ url: '/api/v1/mocs/{moc_id}/revisions', ...options });

/**
 * Go Trich Api
 *
 * Gỡ trích khỏi sổ — **trong 24 giờ**, sau đó không gỡ được nữa (PLAN 5.6 rào 1).
 *
 * **Quyền: CHỈ chủ mạch**, đối xứng với đường trích.
 *
 * Hàng `Trich` **ở lại** với `removed_at` — nó tự nó là log, và nó là thứ giữ cho chữ
 * "đã TỪNG được trích" của PLAN 5.3 còn đúng (`Trich.comment = PROTECT` chặn xoá THẬT
 * một bình luận đã vào sổ, kể cả sau khi trích bị gỡ). Vì unique là **partial**, gỡ xong
 * thì trích câu khác vào đúng mốc đó được ngay.
 *
 * Hạn 24 giờ là hạn THẬT chứ không phải gợi ý UI: rào 1 dựng nó lên để sổ không thành
 * một cái bảng chủ mạch xoay hằng ngày theo việc câu nào "hoá ra đúng" — đúng thứ rào 2
 * (hai dấu thời gian) cũng đang chống.
 *
 * Mốc chưa có trích nào đang hiệu lực ⇒ 404 `chua_co_trich`; quá hạn ⇒ 409
 * `het_han_go_trich`. Không idempotent về phía "gỡ cái đã gỡ": trả 404 chứ không 200, vì
 * một lượt gỡ thành công và một lượt gỡ vào chỗ trống là hai chuyện khác nhau, và cái
 * thứ hai gần như luôn nghĩa là UI đang hiển thị một trạng thái cũ.
 */
export const goTrich = <ThrowOnError extends boolean = false>(options: Options<GoTrichData, ThrowOnError>): RequestResult<GoTrichResponses, GoTrichErrors, ThrowOnError> => (options.client ?? client).delete<GoTrichResponses, GoTrichErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/v1/mocs/{moc_id}/trich',
    ...options
});

/**
 * Trich Vao So Api
 *
 * Ghi một câu khán đài vào sổ — "trích vào sổ", PLAN 5.6.
 *
 * **Quyền: CHỈ chủ mạch** (`Mach.author`, không phải `Moc.author`). Người khác nhận 403
 * `khong_phai_chu`. Rào 4 của PLAN 5.6 nói rõ blockquote ghi *"trích từ khán đài, **bởi
 * chủ mạch**"* — nó là cơ chế thưởng mà chủ cuốn sổ trao đi, nên nó chỉ có nghĩa khi
 * đúng một người trao được.
 *
 * Bốn ca từ chối, mỗi ca một mã để UI nói đúng chuyện:
 *
 * - mạch bị mod **khoá** ⇒ 403 `mach_bi_khoa`. Khác với follow/seen (sổ tay riêng của
 * người đọc, xem `api/theo_doi.py`), trích **ghi vào nội dung công khai** của mạch —
 * nó đúng nghĩa "tương tác" mà PLAN 5.10 cấm trên mạch bị khoá;
 * - mốc đã thành **bia mộ** hoặc bị mod ẩn ⇒ 409 `noi_dung_da_go`. Trích là chú thích
 * gắn vào thân mốc (rào 4), mà bia mộ thì không còn thân nào để gắn — `trinh_bay.moc_ra`
 * cũng đã bỏ khối trích của mốc bị gỡ, nên ghi vào đó là ghi một hàng không cửa nào hiện;
 * - bình luận **không thuộc mạch này**, hoặc đã bị gỡ ⇒ 400 `du_lieu_khong_hop_le`;
 * - mốc **đã có trích đang hiệu lực** ⇒ 409 `da_co_trich` (rào 1). Gỡ trước rồi trích lại.
 *
 * **Trích bình luận của CHÍNH MÌNH thì được**, và blockquote hiện đầy đủ — nhưng chỉ số
 * "Được trích ×N" trên hồ sơ **không cộng** (rào 3, `api/users.py`), và không có thông
 * báo nào được gửi (`core/thong_bao.py::bao_duoc_trich`). Ba cửa, một luật: tự trích
 * không phải một sự kiện xã hội.
 *
 * Người được trích nhận thông báo (PLAN 5.6 dòng cuối), sinh **trong cùng transaction**.
 */
export const trichVaoSo = <ThrowOnError extends boolean = false>(options: Options<TrichVaoSoData, ThrowOnError>): RequestResult<TrichVaoSoResponses, TrichVaoSoErrors, ThrowOnError> => (options.client ?? client).post<TrichVaoSoResponses, TrichVaoSoErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/v1/mocs/{moc_id}/trich',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Liet Ke Thong Bao
 *
 * Chuông poll 60 giây — PLAN 5.8. **Per-user tuyệt đối, KHÔNG BAO GIỜ cache.**
 *
 * **Quyền: chỉ thông báo của chính người gọi.** Không có tham số nào chỉ ra người khác;
 * `user = request.user` nằm ngay trong queryset gốc.
 *
 * Sắp **mới nhất trước**, cursor keyset trên `(created_at, id)` — khoá BẤT BIẾN, nên nó
 * hưởng đủ bảo đảm "không trùng, không sót" của `api/phan_trang.py`. Một thông báo
 * `moc_moi` được gộp lại (mốc thứ hai trong ngày) sẽ **bump `created_at`** và vì thế
 * nhảy lên đầu — đúng ý muốn, và nó không phá keyset: hàng ấy chuyển sang trang 1, đúng
 * ca "hàng mới chèn vào đầu" mà keyset sinh ra để xử.
 *
 * `so_chua_doc` đếm **toàn bộ hộp thư**, không phải trang đang xem: con số trên chấm đỏ
 * nói "bạn có 23 thứ chưa đọc", tính nó trên một trang 20 dòng thì nó kẹt ở `20` mãi mãi
 * — một con số trông hợp lý và luôn sai.
 *
 * **Không có bộ lọc `?chua_doc=`** ở bản này. Chuông hiện cả đã đọc lẫn chưa đọc trong
 * một dòng thời gian; thêm một chế độ lọc là thêm một trạng thái UI phải nhớ, mà PLAN
 * 5.8 không đòi.
 */
export const lietKeThongBao = <ThrowOnError extends boolean = false>(options?: Options<LietKeThongBaoData, ThrowOnError>): RequestResult<LietKeThongBaoResponses, LietKeThongBaoErrors, ThrowOnError> => (options?.client ?? client).get<LietKeThongBaoResponses, LietKeThongBaoErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/v1/notifications',
    ...options
});

/**
 * Danh Dau Da Doc
 *
 * Đánh dấu thông báo đã đọc — PLAN 5.8.
 *
 * **Quyền: chỉ thông báo của chính người gọi.** `ids` của người khác **bị bỏ qua im
 * lặng**, không phải 403: truy vấn luôn kèm `user = request.user`, nên chuyện tệ nhất
 * một id lạ gây ra là `so_da_danh_dau` nhỏ hơn số id đã gửi. Trả 403 thì ngược lại — nó
 * **xác nhận** id đó có thật và thuộc về ai đó, tức một cửa dò id qua mã lỗi.
 *
 * `ids = null` là "đọc hết"; một danh sách là đánh dấu đúng từng dòng. `[]` đánh dấu
 * **không dòng nào** — khác `null` một cách cố ý, để một mảng rỗng do client dựng hụt
 * không lặng lẽ thành lệnh xoá sạch chấm đỏ.
 *
 * **Chỉ chạm hàng đang `read_at IS NULL`.** Hai hệ quả, cả hai đều là chủ đích:
 * `so_da_danh_dau` đếm đúng số dòng **vừa đổi trạng thái** (bấm "đọc hết" lần thứ hai ra
 * `0`), và `read_at` cũ không bị dời — nó là mốc "tôi đã xem cái này lúc nào", không phải
 * một cờ boolean viết lại được mỗi lần bấm.
 */
export const danhDauDaDoc = <ThrowOnError extends boolean = false>(options: Options<DanhDauDaDocData, ThrowOnError>): RequestResult<DanhDauDaDocResponses, DanhDauDaDocErrors, ThrowOnError> => (options.client ?? client).post<DanhDauDaDocResponses, DanhDauDaDocErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/v1/notifications/read',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Liet Ke Sub
 *
 * MỌI chuyên mục, sắp theo `slug` — PLAN mục 7 *(thêm ở lượt vá Phase 1d)*.
 *
 * **Frontend CẤM ghi cứng danh sách slug** (PLAN mục 7 nói thẳng). Trước endpoint này,
 * `apps/web` giữ một hằng `SUB_KHOI_DIEM = ["chung-khoan", "crypto"]` nuôi cả sidebar
 * lẫn `sitemap.ts`: mở sub thứ ba qua admin thì **cả hai chỗ cùng bỏ sót nó, im lặng**,
 * và chiều ngược cũng im — đổi slug trong admin thì sidebar âm thầm bỏ mục đó (404 →
 * lọc khỏi danh sách) trong khi `sitemap.xml` vẫn khai `/s/<slug cũ>` là URL sống.
 *
 * **Không phân trang, và đó là một chốt chứ không phải một thiếu sót.** v1 tạo sub bằng
 * tay qua admin (PLAN mục 1), nên tập này là hàng chục chứ không phải hàng nghìn; thêm
 * cursor bây giờ là bắt hai chỗ gọi (sidebar, sitemap) tự lật trang cho một danh sách
 * chưa bao giờ dài. Ngày nó dài ra thì đổi ở đây, kèm cursor keyset trên `slug`.
 *
 * Sắp theo `slug` chứ không theo `so_mach`: sidebar là một **bản đồ**, và một bản đồ
 * tự sắp lại theo độ đông mỗi lần có bài mới thì không ai nhớ được chỗ nào ở đâu.
 */
export const lietKeSub = <ThrowOnError extends boolean = false>(options?: Options<LietKeSubData, ThrowOnError>): RequestResult<LietKeSubResponses, unknown, ThrowOnError> => (options?.client ?? client).get<LietKeSubResponses, unknown, ThrowOnError>({ url: '/api/v1/subs', ...options });

/**
 * Xem Sub
 *
 * Header của trang chuyên mục `/s/<slug>` — tên, mô tả, số mạch, ngày lập.
 *
 * Endpoint **đọc, không per-user**, tách khỏi feed vì nó đổi theo nhịp hoàn toàn khác:
 * tên và mô tả sub gần như bất động, còn feed đổi mỗi lần có bài mới. Nhét header vào
 * `FeedOut` là bắt mọi trang phân trang phải chở lại cùng một khối chữ.
 *
 * Slug không tồn tại trả 404 `khong_tim_thay`.
 */
export const xemSub = <ThrowOnError extends boolean = false>(options: Options<XemSubData, ThrowOnError>): RequestResult<XemSubResponses, XemSubErrors, ThrowOnError> => (options.client ?? client).get<XemSubResponses, XemSubErrors, ThrowOnError>({ url: '/api/v1/subs/{slug}', ...options });

/**
 * Xem Ho So
 *
 * Hồ sơ công khai: mạch của họ, "Được trích ×N", tổng mốc, tổng bình luận.
 *
 * Ba con số đếm **nội dung đọc được**: mốc/bình luận đã xoá hoặc bị ẩn không tính, và
 * nội dung nằm trong một mạch đã bị mod ẩn cũng không tính.
 *
 * `duoc_trich` đếm theo **số chủ mạch khác nhau** đã trích bình luận của người này, chỉ
 * tính trích còn hiệu lực — rào 3 của PLAN 5.6, chống hai nick trích qua lại để tự nâng
 * chỉ số cho nhau. Nó **soi gương đúng cái blockquote** trên thẻ mốc: đếm khi khối trích
 * còn hiện, không đếm khi khối trích biến mất. Mạch bị mod ẩn, mốc nhận trích bị ẩn hoặc
 * xoá, hay chính bình luận bị **mod ẩn** đều làm khối trích biến mất ⇒ không đếm. Thiếu
 * bốn bộ lọc ấy thì mod ẩn cả một mạch làm `so_mach`/`so_moc`/`so_binh_luan` về 0 trong
 * khi "Được trích ×1" vẫn sáng trên hồ sơ — đúng cái "máy in địa vị" mà rào 3 dựng lên
 * để chặn. Bộ lọc ấy là `core.doc_noi_dung.TRICH_CON_HIEN`, dùng chung với "câu đáng
 * đọc" của PLAN 5.5.
 *
 * **TỰ TRÍCH KHÔNG TÍNH** *(rào 3, chốt 2026-08-22)*: chủ mạch trích bình luận của
 * chính mình thì chỉ số của họ không nhúc nhích. Chỉ số này đo *"có bao nhiêu người
 * KHÁC thấy chữ của bạn đáng ghi vào sổ"*; tự trích trả lời câu hỏi khác hẳn, và nó là
 * đường ngắn nhất tới cùng con số — không cần nick thứ hai, không cần ai đồng ý. Khối
 * blockquote vẫn hiện đầy đủ trên thẻ mốc, chỉ có chỉ số hồ sơ là không cộng.
 *
 * **Tác giả TỰ xoá bình luận thì `duoc_trich` KHÔNG tụt**, và đó là chỗ con số này cố ý
 * lệch khỏi ba con số trên. `trinh_bay.trich_ra` giữ nguyên body của blockquote trong ca
 * ấy, vì PLAN 5.6 dựng "cuốn sổ không-xoá-được" để chống *tác giả* rút chữ, không phải
 * để chống *mod* gỡ nội dung. Đếm tụt ở đây là hai cửa nói hai chuyện về cùng một sự
 * kiện: khối trích còn nguyên chữ trên trang mạch mà chỉ số trên hồ sơ đã giảm thì không
 * con số nào giải thích được nữa.
 *
 * `?limit=` cắt số mạch trả kèm, mặc định 20, tối đa 50. Hồ sơ **chưa có cursor** ở
 * bản này: quá `limit` mạch thì phần dôi ra không có đường nào lấy tiếp.
 *
 * Endpoint này **không** trả email, trạng thái ban hay bất cứ thứ gì chỉ chủ tài khoản
 * được thấy.
 */
export const xemHoSo = <ThrowOnError extends boolean = false>(options: Options<XemHoSoData, ThrowOnError>): RequestResult<XemHoSoResponses, XemHoSoErrors, ThrowOnError> => (options.client ?? client).get<XemHoSoResponses, XemHoSoErrors, ThrowOnError>({ url: '/api/v1/users/{username}', ...options });

/**
 * Dat Vote Api
 *
 * Vote ±1 trên **mốc hoặc bình luận**, hai trục riêng rẽ (PLAN 5.7).
 *
 * **Quyền: bất kỳ ai đã đăng nhập** — kể cả trên nội dung của chính mình (PLAN 5.7 chốt
 * tác giả có sẵn +1 của mình, và rút được như mọi phiếu khác). Chặn duy nhất: mạch bị
 * mod **khoá** ⇒ 403 `mach_bi_khoa`; đích đã bị gỡ ⇒ 409 `noi_dung_da_go` — số phiếu
 * của bia mộ không được trả ra (`trinh_bay.nut_ra` zero hoá nó), nên nhận thêm phiếu vào
 * đó là ghi vào một con số không ai đọc được.
 *
 * `value ∈ {-1, 0, 1}`; **`0` nghĩa là RÚT** — hàng `Vote` bị xoá, không lưu `0`.
 * Vote lại cùng giá trị là no-op (idempotent), không cộng dồn.
 *
 * Trả về **con số mới của đích**, không chỉ "ok": UI vote lạc quan cần một nguồn sự thật
 * để đối chiếu, nếu không hai cú bấm nhanh để lại một con số client tự cộng.
 *
 * Mạch **đã đóng sổ vẫn vote được** — đóng sổ chỉ chặn nối mốc (PLAN 5.1).
 */
export const datVote = <ThrowOnError extends boolean = false>(options: Options<DatVoteData, ThrowOnError>): RequestResult<DatVoteResponses, DatVoteErrors, ThrowOnError> => (options.client ?? client).post<DatVoteResponses, DatVoteErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/v1/votes',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
