// SINH TỰ ĐỘNG bởi `pnpm codegen` từ OpenAPI của Django Ninja.
// KHÔNG SỬA TAY — mọi thay đổi sẽ mất ở lần codegen kế tiếp.
// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

/**
 * HealthOut
 *
 * Kết quả healthcheck. `db` = "ok" chỉ khi truy vấn thật xuống Postgres thành công.
 */
export type HealthOut = {
    /**
     * Db
     */
    db: string;
    /**
     * Status
     */
    status: string;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type GetHealthErrors = {
    /**
     * Service Unavailable
     */
    503: HealthOut;
};

export type GetHealthError = GetHealthErrors[keyof GetHealthErrors];

export type GetHealthResponses = {
    /**
     * OK
     */
    200: HealthOut;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];
