// SINH TỰ ĐỘNG bởi `pnpm codegen` từ OpenAPI của Django Ninja.
// KHÔNG SỬA TAY — mọi thay đổi sẽ mất ở lần codegen kế tiếp.
// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

/**
 * AnhOut
 *
 * Một ảnh trong gallery của mốc — Phase 5.
 *
 * **Không trả `khoa_luu_tru` ra ngoài.** Client cần URL, và URL là thứ `STORAGES` sinh
 * ra; trả thêm khoá thô là mời frontend tự ghép đường dẫn, rồi ngày đổi sang R2 (nơi
 * URL có chữ ký và hạn dùng) thì bản ghép tay ấy vẫn "chạy" ở dev và chết trên prod.
 *
 * `w`/`h` là kích thước ảnh **đã lưu**, không phải file gốc — chúng dùng để đặt
 * `width`/`height` trên thẻ `<img>` chống layout shift, nên phải khớp đúng file đang
 * được phục vụ. `null` chỉ xảy ra với hàng cũ ghi trước Phase 5 (không có hàng nào).
 *
 * `exif_taken_at` là ngày chụp **server** đọc từ file gốc trước khi tái mã hoá xoá sạch
 * EXIF. Nó là *gợi ý* cho `occurred_at`, không phải nguồn của nó: PLAN nguyên tắc 3 nói
 * `occurred_at` do người dùng đặt, và một tấm ảnh chụp lại màn hình cũ có ngày chụp
 * chẳng liên quan gì tới ngày sự việc.
 */
export type AnhOut = {
    /**
     * Exif Taken At
     */
    exif_taken_at: string | null;
    /**
     * H
     */
    h: number | null;
    /**
     * Id
     */
    id: number;
    /**
     * Position
     */
    position: number;
    /**
     * Url
     */
    url: string;
    /**
     * Url Thumb
     */
    url_thumb: string;
    /**
     * W
     */
    w: number | null;
};

/**
 * BaoCaoDaGuiOut
 *
 * Biên nhận của `POST /reports` — PLAN 5.10 (L03, lượt vá V1).
 *
 * **Cố ý không trả trạng thái xử lý.** Người tố không được biết mod đã làm gì với báo
 * cáo của mình, và endpoint này không được biến thành một cửa dò xem hàng đợi có gì:
 * `resolved_at`/`resolved_by`/`action` chỉ sống ở `/api/admin`.
 *
 * Trả `id` vì UI cần một khoá để không hiện hai lần biên nhận cho cùng một lượt bấm;
 * trả `created_at` vì đó là dấu thời gian **của server**, thứ duy nhất trả lời được
 * "mình đã tố lúc nào".
 */
export type BaoCaoDaGuiOut = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Id
     */
    id: number;
    /**
     * Ly Do
     */
    ly_do: 'phim_hang' | 'lua_dao' | 'spam' | 'khac';
    /**
     * Target Id
     */
    target_id: number;
    /**
     * Target Type
     */
    target_type: 'mach' | 'moc' | 'comment';
};

/**
 * BaoCaoMoiIn
 *
 * Gửi báo cáo — `POST /reports` (PLAN 5.10).
 *
 * `ly_do` là **enum**, đúng bốn giá trị PLAN liệt kê: *phím hàng · lừa đảo, mời uỷ thác,
 * room VIP · spam · khác*. Khai bằng `Literal` chứ không `str` để `openapi.json` ra
 * `enum` và TS client nhận một union — một chuỗi tự do ở đây là hàng đợi kiểm duyệt đầy
 * những lý do không nhóm lại được, và mod thì phải đọc từng dòng.
 *
 * `ghi_chu` tuỳ chọn: chỗ người tố nói thêm. Server **không** validate ngữ nghĩa (cùng
 * triết lý với `ket_qua`/`figures`), chỉ chặn độ dài.
 */
export type BaoCaoMoiIn = {
    /**
     * Ghi Chu
     */
    ghi_chu?: string;
    /**
     * Ly Do
     */
    ly_do: 'phim_hang' | 'lua_dao' | 'spam' | 'khac';
    /**
     * Target Id
     */
    target_id: number;
    /**
     * Target Type
     */
    target_type: 'mach' | 'moc' | 'comment';
};

/**
 * BinhLuanMoiIn
 *
 * Viết bình luận — `POST /machs/{id}/comments` (PLAN 5.4, nguyên tắc 4 và 6).
 *
 * `anchor_moc_seq` **chỉ đặt được trên bình luận gốc**: reply kế thừa neo của gốc, nên
 * gửi kèm `parent_id` là 400 chứ không phải bỏ qua im lặng — bỏ qua im lặng là cách một
 * bình luận biến mất khỏi ngăn kéo mà không ai hiểu tại sao.
 *
 * Gốc mang `anchor_moc_seq = null` nghĩa là người viết **đã gỡ chip** — không thuộc ngăn
 * kéo nào. Đó là một lựa chọn, không phải dữ liệu thiếu.
 */
export type BinhLuanMoiIn = {
    /**
     * Anchor Moc Seq
     */
    anchor_moc_seq?: number | null;
    /**
     * Body
     */
    body: string;
    /**
     * Parent Id
     */
    parent_id?: number | null;
};

/**
 * BinhLuanOut
 *
 * Một nút trong cây bình luận. Server dựng cây và sắp sibling (PLAN mục 7).
 *
 * Khi `trang_thai != "binh_thuong"` thì đây là **bia mộ giữ chỗ**: `author`, `body`,
 * `edited_at` là `null`; `up_count`, `down_count`, `score` về `0`; còn `la_chu_mach` và
 * `tu_gap` về `false`. **`id`, `parent_id`, `depth`, `anchor_moc_seq`, `created_at` vẫn
 * là giá trị THẬT** — đó là cách 1c dựng được nút "nhảy tới khán đài" từ
 * `TrichOut.comment_id`. Nút như vậy xuất hiện khi nó còn **con sống
 * sót** trong `replies`, **hoặc** khi `trang_thai = "da_xoa"` và bình luận đã TỪNG được
 * chủ mạch trích vào sổ — kể cả trích đã gỡ (PLAN 5.3). Không dính vế nào thì nó biến
 * mất hẳn.
 *
 * "Con sống sót" **không** đồng nghĩa "con đọc được": con ấy có thể tự nó là bia mộ,
 * được giữ nhờ vế thứ hai. Hệ quả, và đây là hành vi đúng chứ không phải lỗi: một thread
 * có thể trả về **toàn bia mộ, không một chữ nội dung nào**, và nó vẫn chiếm một chỗ
 * trong `tong_thread` lẫn một slot trong trang của khán đài. Đừng đọc "thread" thành
 * "thread có nội dung".
 *
 * Vế thứ hai chỉ áp cho `"da_xoa"`. Bình luận bị **mod ẩn** mà không còn con sống sót
 * thì biến mất kể cả khi từng được trích: `MocOut.trich` cũng biến mất trong ca đó, nên
 * giữ lại bia mộ là giữ chỗ cho một liên kết không còn đầu kia.
 *
 * `depth` 1-based: bình luận gốc là 1. UI render tối đa 6 tầng rồi "tiếp tục thread →",
 * nhưng API trả đủ cây (PLAN 5.3).
 */
export type BinhLuanOut = {
    /**
     * Anchor Moc Seq
     */
    anchor_moc_seq: number | null;
    author: NguoiDungTomTatOut | null;
    /**
     * Body
     */
    body: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Depth
     */
    depth: number;
    /**
     * Down Count
     */
    down_count: number;
    /**
     * Edited At
     */
    edited_at: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * La Chu Mach
     */
    la_chu_mach: boolean;
    /**
     * Parent Id
     */
    parent_id: number | null;
    /**
     * Replies
     */
    replies: Array<BinhLuanOut>;
    /**
     * Score
     */
    score: number;
    /**
     * Trang Thai
     */
    trang_thai: 'binh_thuong' | 'da_xoa' | 'da_an';
    /**
     * Tu Gap
     */
    tu_gap: boolean;
    /**
     * Up Count
     */
    up_count: number;
};

/**
 * BinhLuanSuaIn
 *
 * Sửa bình luận — `PATCH /comments/{id}`. Chỉ `body` (PLAN 5.3).
 */
export type BinhLuanSuaIn = {
    /**
     * Body
     */
    body: string;
};

/**
 * ChuongOut
 *
 * `GET /notifications` — chuông poll 60 giây (PLAN 5.8). **Per-user, cấm cache.**
 *
 * Trả kèm `so_chua_doc` của **toàn bộ** hộp thư chứ không phải của trang đang xem: con
 * số trên chấm đỏ nói "bạn có 23 thứ chưa đọc", và tính nó trên một trang 20 dòng sẽ cho
 * ra `20` mãi mãi — một con số trông hợp lý và luôn sai.
 */
export type ChuongOut = {
    /**
     * Cursor Ke Tiep
     */
    cursor_ke_tiep: string | null;
    /**
     * Items
     */
    items: Array<ThongBaoOut>;
    /**
     * So Chua Doc
     */
    so_chua_doc: number;
};

/**
 * DaDocOut
 *
 * Kết quả `POST /notifications/read`. `so_da_danh_dau` là số dòng **vừa đổi trạng thái**.
 *
 * Đánh dấu lại một thông báo đã đọc **không** được tính vào con số đó, và không được dời
 * `read_at` cũ: hai lần bấm "đọc hết" phải ra `so_da_danh_dau = 0` ở lần thứ hai, nếu
 * không thì con số này không nói được gì.
 */
export type DaDocOut = {
    /**
     * So Chua Doc
     */
    so_chua_doc: number;
    /**
     * So Da Danh Dau
     */
    so_da_danh_dau: number;
};

/**
 * DaXemIn
 *
 * `POST /machs/{id}/seen` — client báo đã đọc tới đâu (PLAN 5.5).
 *
 * `entry_seq = null` (mặc định) nghĩa là **"đã xem tới mốc mới nhất"**, đúng ca PLAN 5.5
 * mô tả: thẻ mốc mới nhất mở sẵn khi trang mở, nên client gọi endpoint này không kèm gì.
 * Truyền một `seq` cụ thể là ca người ta bung timeline đầy đủ rồi đọc tới một chỗ nào đó.
 *
 * Con số **chỉ tiến, không lùi** ở phía server (`core.ghi.dat_da_xem`), nên gửi một
 * `entry_seq` nhỏ hơn vị trí đã ghi là no-op chứ không phải một cách reset vạch mới —
 * peek một mốc cũ trên spine không được đánh dấu 6 mốc cuối thành chưa đọc.
 *
 * `ge=0` chứ không `ge=1`: `0` là "chưa xem mốc nào", giá trị khởi điểm hợp lệ của cột.
 */
export type DaXemIn = {
    /**
     * Entry Seq
     */
    entry_seq?: number | null;
};

/**
 * DaXemOut
 *
 * Kết quả `POST /machs/{id}/seen` — PLAN 5.5.
 *
 * **`following = false` nghĩa là KHÔNG GHI GÌ**, và đó là câu trả lời trung thực chứ
 * không phải một lỗi: `last_seen_entry_seq` sống trên hàng `Follow` (PLAN mục 6), nên
 * người chưa theo mạch không có chỗ nào để lưu vị trí đọc. Endpoint nhận request (200)
 * thay vì 404 — client không phải biết trước mình có theo hay không mới dám đặt một cái
 * bookmark — nhưng nó **nói ra** rằng không có gì được lưu, thay vì trả một `{ok: true}`
 * rỗng nghĩa.
 *
 * Con số trả về là giá trị **sau** lượt ghi, và nó chỉ tiến không lùi: mở lại một mốc cũ
 * trên spine không được kéo vạch mới về sau (xem `core.ghi.dat_da_xem`).
 */
export type DaXemOut = {
    /**
     * Following
     */
    following: boolean;
    /**
     * Last Seen Entry Seq
     */
    last_seen_entry_seq: number;
};

/**
 * DanhDauDaDocIn
 *
 * `POST /notifications/read` — đánh dấu đã đọc (PLAN 5.8).
 *
 * `ids = null` (mặc định) nghĩa là **đánh dấu HẾT** — nút "đọc hết" của chuông. Truyền
 * một danh sách là đánh dấu đúng từng dòng, cho lượt bấm vào một thông báo lẻ.
 *
 * Id của **người khác** trong danh sách bị bỏ qua chứ không làm cả request hỏng: truy vấn
 * luôn kèm `user = người đang gọi` (xem endpoint), nên chuyện tệ nhất một id lạ gây ra là
 * `so_da_danh_dau` nhỏ hơn số id đã gửi. Trả 403 ở đây thì ngược lại: nó **xác nhận** id
 * đó có thật và thuộc về ai đó — một cửa dò id qua mã lỗi.
 *
 * Danh sách rỗng `[]` khác `null`: nó đánh dấu **không dòng nào**. Cố ý giữ khác nhau —
 * một mảng rỗng do client dựng hụt không được biến thành "đọc hết".
 *
 * `ids` có **trần độ dài** (L27, vá V1): thiếu nó thì một request đơn lẻ đẩy được một
 * triệu phần tử vào `pk__in`, tức một câu SQL vài megabyte trên một endpoint chỉ cần
 * đăng nhập. Trần rộng hơn hẳn mọi lượt bấm thật — chuông trả tối đa một trang — nên nó
 * không chặn ai, nó chỉ chặn cái không phải lượt bấm.
 */
export type DanhDauDaDocIn = {
    /**
     * Ids
     */
    ids?: Array<number> | null;
};

/**
 * DongSoIn
 *
 * Đóng sổ — `POST /machs/{id}/close`. `ket_qua` tuỳ chọn, ≤40 ký tự (PLAN 5.1).
 *
 * Thuần hiển thị, không validate ngữ nghĩa — cùng triết lý với `figures`.
 */
export type DongSoIn = {
    /**
     * Ket Qua
     */
    ket_qua?: string | null;
};

/**
 * FeedOut
 *
 * Một trang feed. `cursor_ke_tiep = null` nghĩa là hết.
 *
 * **Cursor mang khoá của ĐÚNG sort đã sinh ra nó** (plan con 1d §2.1): `sort=nhieu_diem`
 * trả cursor `(diem, id)`, hai sort thời gian trả cursor `(thời điểm, id)`. Đem cursor
 * của sort này sang sort kia là 400 `cursor_khong_hop_le`, không phải trang 1 im lặng.
 */
export type FeedOut = {
    /**
     * Cursor Ke Tiep
     */
    cursor_ke_tiep: string | null;
    /**
     * Items
     */
    items: Array<MachTomTatOut>;
};

/**
 * FigureIn
 *
 * Một cặp trong dải số của mốc. Thuần hiển thị — server không validate ngữ nghĩa.
 */
export type FigureIn = {
    /**
     * Label
     */
    label: string;
    /**
     * Value
     */
    value: string;
};

/**
 * FigureOut
 *
 * Một cặp trong dải số của mốc, vd `{label: "GIÁ VÀO", value: "27.80"}`.
 *
 * Thuần hiển thị — server không validate ngữ nghĩa (PLAN 5.2).
 */
export type FigureOut = {
    /**
     * Label
     */
    label: string;
    /**
     * Value
     */
    value: string;
};

/**
 * HealthOut
 *
 * Kết quả healthcheck. `db` = "ok" chỉ khi truy vấn thật xuống Postgres thành công.
 */
export type HealthOut = {
    /**
     * Db
     */
    db: string;
    /**
     * Status
     */
    status: string;
};

/**
 * HoSoOut
 *
 * Hồ sơ công khai `/u/<username>` — PLAN 5.9.
 *
 * **`machs` bị CẮT ở `?limit=` (mặc định 20, tối đa 50) và hồ sơ KHÔNG có cursor.**
 * Người có nhiều mạch hơn thế thì phần dôi ra không lấy tiếp được bằng đường nào — đừng
 * đọc `machs` như "toàn bộ mạch của người này", và đừng suy `so_mach` từ `len(machs)`:
 * `so_mach` đếm cả phần bị cắt.
 *
 * Cảnh báo đó nằm ở docstring CLASS chứ không ở comment `#:` của trường là có lý do:
 * `tests/test_hop_dong_openapi.py` chứng minh comment `#:` **không ra tới**
 * `openapi.json`, nên chỉ docstring class mới tới được tay người dùng API.
 *
 * `so_mach`, `so_moc`, `so_binh_luan` đếm **nội dung đọc được**: nội dung đã xoá, bị mod
 * ẩn, hoặc nằm trong một mạch đã bị mod ẩn đều không tính.
 *
 * **`duoc_trich` KHÔNG cùng luật đó**, và khác biệt là chủ đích: nó soi gương đúng khối
 * trích trên thẻ mốc. Mạch bị mod ẩn, mốc nhận trích bị ẩn hoặc xoá, hay bình luận bị
 * **mod ẩn** đều làm khối trích biến mất ⇒ không đếm. Nhưng tác giả **tự xoá** bình luận
 * thì blockquote giữ nguyên body (PLAN 5.6, "sổ không-xoá-được" chống tác giả rút chữ)
 * ⇒ `duoc_trich` **không đổi**.
 */
export type HoSoOut = {
    /**
     * Bio
     */
    bio: string;
    /**
     * Date Joined
     */
    date_joined: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Duoc Trich
     */
    duoc_trich: number;
    /**
     * Machs
     */
    machs: Array<MachTomTatOut>;
    /**
     * So Binh Luan
     */
    so_binh_luan: number;
    /**
     * So Mach
     */
    so_mach: number;
    /**
     * So Moc
     */
    so_moc: number;
    /**
     * Username
     */
    username: string;
};

/**
 * KetQuaTimKiemOut
 *
 * Một dòng kết quả tìm kiếm — Phase 7.
 *
 * `mach` là **đúng thẻ mà feed dùng** (`MachTomTatOut`), không phải một hình dạng thứ
 * hai: trang kết quả vẽ lại cùng loại thẻ với trang chủ, nên hai schema khác nhau chỉ
 * tạo hai đường trôi.
 *
 * Hai trường tô đậm dùng dấu **`[[` `]]`**, không phải HTML. Trả `<mark>` về đây là mời
 * `dangerouslySetInnerHTML` vào một đường dữ liệu do người dùng viết; frontend tự dựng
 * thẻ từ cặp dấu (`apps/web/lib/tim-kiem.ts`). Chữ trong hai trường này đến từ
 * **Postgres**, không phải từ chỉ mục — xem docstring `api/tim_kiem.py`.
 */
export type KetQuaTimKiemOut = {
    /**
     * Doan Trich
     */
    doan_trich: string;
    mach: MachTomTatOut;
    /**
     * Title To Dam
     */
    title_to_dam: string;
};

/**
 * KetQuaXoaOut
 *
 * Kết quả `DELETE /comments/{id}` — PLAN 5.3.
 *
 * `xoa_that = false` nghĩa là bình luận **ở lại làm bia mộ** "[đã xoá]" vì nó còn reply
 * con **hoặc đã TỪNG được trích vào sổ** (kể cả trích đã gỡ). UI phải render lại nút đó
 * thành bia mộ chứ không gỡ nó khỏi cây — gỡ đi là làm mồ côi cả nhánh con.
 */
export type KetQuaXoaOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Xoa That
     */
    xoa_that: boolean;
};

/**
 * KhanDaiOut
 *
 * Khán đài: MỘT phòng chứa toàn bộ cây bình luận của mạch (PLAN mục 2, 5.3).
 *
 * Phân trang khác nhau theo `sort`, đúng PLAN 5.3:
 *
 * - `hay_nhat` — MỘT trang 50 thread gốc, "xem thêm" gọi lại bằng `?offset=`. Rank động
 * theo `now` nên trang sau có thể trôi nhẹ; đó là đánh đổi đã chốt. `cursor_ke_tiep`
 * luôn `null` ở sort này.
 * - `moi_nhat` / `cu_nhat` — cursor keyset thật trên `(created_at, id)`.
 * `offset_ke_tiep` luôn `null` ở hai sort này.
 *
 * **Chế độ `?dang_doc=1`** (PLAN 5.5 — "câu đáng đọc") dùng lại đúng schema này nhưng
 * đổi nghĩa hai trường: `threads` là phép hợp `đã trích ∪ top-10 wilson` sắp theo wilson
 * **thuần**, và `tong_thread` là kích thước của tập ấy chứ không phải tổng thread của
 * mạch. Cả hai con trỏ trang luôn `null` — chế độ đó không phân trang. Chỉ chế độ này
 * mang `so_ung_vien_bo_lai`.
 */
export type KhanDaiOut = {
    /**
     * Cursor Ke Tiep
     */
    cursor_ke_tiep: string | null;
    /**
     * Offset Ke Tiep
     */
    offset_ke_tiep: number | null;
    /**
     * So Ung Vien Bo Lai
     */
    so_ung_vien_bo_lai: number | null;
    /**
     * Sort
     */
    sort: 'hay_nhat' | 'moi_nhat' | 'cu_nhat';
    /**
     * Threads
     */
    threads: Array<BinhLuanOut>;
    /**
     * Tong Thread
     */
    tong_thread: number;
};

/**
 * LoiOut
 *
 * `{detail, code}` — PLAN mục 7.
 */
export type LoiOut = {
    /**
     * Code
     */
    code: string;
    /**
     * Detail
     */
    detail: string;
};

/**
 * LoiThoiGianOut
 *
 * Lời từ chối **vì thời gian**: `{detail, code, thu_lai_tu}` — PLAN mục 7.
 *
 * Hôm nay đúng một cửa dùng nó: 429 `qua_han_muc_moc` của `POST /machs/{id}/mocs`.
 * `detail` của mã ấy dừng ở *"mai nối tiếp nhé"* — đúng, nhưng thiếu con số, và "mai"
 * lúc 23:50 nghĩa là mười phút nữa. Để frontend tự tính là bắt nó dựng lại luật "nửa
 * đêm giờ VN" ở phía client: đó chính là nợ `API-THIEU-MOC-THOI-GIAN`, trả 2026-08-23.
 *
 * **Kế thừa chứ không phải hình dạng lỗi thứ hai.** Hợp đồng "mọi lỗi có `detail` +
 * `code`" giữ nguyên; ai chỉ đọc hai trường ấy không phải biết lớp này tồn tại. Và nó
 * **không** được gộp vào `LoiOut`: một `thu_lai_tu: null` gắn vào mọi 404 của cả hai
 * `NinjaAPI` là một trường vô nghĩa ở 99% số lời từ chối, và hai bài đo hình dạng lỗi
 * của khu quản trị ghim đúng chuyện đó.
 *
 * ⚠ **Không ném qua `LoiGhi` được** (`api/quyen.py`): exception handler chỉ dựng được
 * `LoiOut`. Cửa nào cần trường này thì `return` thẳng `Status(...)` — phép kiểm của nó
 * vì thế phải nằm ở tầng handler, trước `transaction.atomic()`.
 */
export type LoiThoiGianOut = {
    /**
     * Code
     */
    code: string;
    /**
     * Detail
     */
    detail: string;
    /**
     * Thu Lai Tu
     */
    thu_lai_tu: string;
};

/**
 * MachChiTietOut
 *
 * Trang mạch: mạch + toàn bộ mốc + `face` server đã tính + spine (PLAN mục 7).
 *
 * **Response này KHÔNG chứa trường nào phụ thuộc người xem** và vì thế cache được
 * (PLAN 8.4). Vote của tôi, đã theo chưa, đọc tới đâu — tất cả nằm ở
 * `GET /machs/{id}/me`.
 *
 * `face` ở bản này tính THUẦN theo luật thời gian: mạch đang mở · chưa bị mod khoá ·
 * `now − last_activity_at ≤ 72h`. Vế "user đã follow hoặc từng bình luận" của PLAN 5.5
 * **chưa được áp** vì nó phụ thuộc người xem.
 *
 * `comment_count` là số bình luận ĐỌC ĐƯỢC, và `last_activity_at` có thể nhỏ hơn
 * `last_entry_at` — xem `MachTomTatOut`.
 */
export type MachChiTietOut = {
    author: NguoiDungTomTatOut;
    /**
     * Closed At
     */
    closed_at: string | null;
    /**
     * Comment Count
     */
    comment_count: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Entry Count
     */
    entry_count: number;
    /**
     * Face
     */
    face: 'bao' | 'can';
    /**
     * Id
     */
    id: number;
    /**
     * Ket Qua
     */
    ket_qua: string | null;
    /**
     * Last Activity At
     */
    last_activity_at: string;
    /**
     * Last Entry At
     */
    last_entry_at: string;
    /**
     * Locked
     */
    locked: boolean;
    /**
     * Mo Lai Den
     */
    mo_lai_den: string | null;
    /**
     * Mocs
     */
    mocs: Array<MocOut>;
    /**
     * Slug
     */
    slug: string;
    /**
     * Spine
     */
    spine: Array<SpineOut>;
    /**
     * Status
     */
    status: string;
    sub: SubTomTatOut;
    /**
     * Title
     */
    title: string;
    /**
     * Tran Moc Moi Ngay
     */
    tran_moc_moi_ngay: number;
};

/**
 * MachCuaToiOut
 *
 * `GET /machs/{id}/me` — trạng thái của NGƯỜI XEM trên một mạch (PLAN mục 7, 8.4).
 *
 * **Response này KHÔNG BAO GIỜ được cache.** Nó là nửa còn lại của cặp mà PLAN 8.4 dựng
 * lên: `GET /machs/{id}` không chứa gì per-user nên trang cache được, còn mọi thứ phụ
 * thuộc người xem đi qua đây, sau khi trang đã render. Một `Cache-Control` lỏng hay một
 * lượt nướng nội dung này vào HTML tĩnh là phục vụ phiếu bầu của người này cho người kia.
 *
 * Khách chưa đăng nhập nhận **200** với `dang_nhap = false`, hai danh sách rỗng và
 * `following = false` — cùng lý lẽ `ToiOut`: đây là lời gọi chạy trên mọi lượt tải trang
 * mạch, kể cả của bot, nên 401 ở trạng thái bình thường nhất của hệ thống là dạy frontend
 * coi lỗi là chuyện thường.
 *
 * `face` ở đây **có thể khác** `face` của `GET /machs/{id}`, và đó là toàn bộ lý do
 * trường này tồn tại ở cả hai chỗ. Bên kia tính vế thời gian của PLAN 5.5 (cache được);
 * bên này áp thêm vế thứ hai — *"user đăng nhập VÀ đã follow hoặc từng bình luận mạch
 * này"*. Vì vế 2 là một phép HOẶC, `face` ở đây chỉ có thể **CẶN → BÃO**, không bao giờ
 * ngược lại. Frontend lấy `face` của endpoint này khi có, và rơi về bên kia khi khách.
 */
export type MachCuaToiOut = {
    /**
     * Dang Nhap
     */
    dang_nhap: boolean;
    /**
     * Face
     */
    face: 'bao' | 'can';
    /**
     * Following
     */
    following: boolean;
    /**
     * Last Seen Entry Seq
     */
    last_seen_entry_seq: number;
    /**
     * My Reactions
     */
    my_reactions: Array<ReactionCuaToiOut>;
    /**
     * My Votes
     */
    my_votes: Array<VoteCuaToiOut>;
    /**
     * Noi Dung Cua Toi
     */
    noi_dung_cua_toi: Array<NoiDungCuaToiOut>;
    /**
     * Tung Binh Luan
     */
    tung_binh_luan: boolean;
};

/**
 * MachMoiIn
 *
 * Đăng bài — `POST /machs`. Bài gốc **chính là mốc 1**, nên nó kế thừa `MocMoiIn`.
 *
 * Không có trường `body` trên `Mach` (PLAN 5.1): `body` ở đây là thân của mốc 1.
 */
export type MachMoiIn = {
    /**
     * Body
     */
    body: string;
    /**
     * Figures
     */
    figures?: Array<FigureIn> | null;
    /**
     * Loai
     */
    loai?: string | null;
    /**
     * Occurred At
     */
    occurred_at?: string | null;
    /**
     * Question For Crowd
     */
    question_for_crowd?: string | null;
    /**
     * Sub
     *
     * slug của chuyên mục
     */
    sub: string;
    /**
     * Title
     */
    title: string;
};

/**
 * MachTomTatOut
 *
 * Một mạch ở mức thẻ feed / danh sách hồ sơ.
 *
 * **`comment_count` là số bình luận ĐỌC ĐƯỢC, không phải số dòng khán đài sẽ render.**
 * Bình luận đã xoá hoặc bị ẩn không được đếm, nhưng vẫn để lại bia mộ giữ chỗ khi chúng
 * còn reply — nên khán đài có thể hiện 24 dòng trong khi con số này nói 22. Đó là chủ
 * đích, đừng "sửa" cho khớp.
 *
 * **`last_activity_at` có thể NHỎ HƠN `last_entry_at`.** Hai cột đo hai thứ khác nhau:
 * `last_entry_at` đo cấu trúc (mọi mốc, kể cả mốc bị ẩn), `last_activity_at` đo nội
 * dung đọc được. Hệ quả nhìn thấy được: một mạch đứng đầu feed "Đang diễn ra" mà mở ra
 * là mặt CẶN.
 *
 * **`diem` là điểm của MỐC 1, không phải tổng điểm của mạch.** PLAN 5.7 chốt vote nằm
 * trên từng mốc riêng rẽ ("mốc 9 được 412 dù bài gốc 89"), nên không tồn tại con số
 * "điểm của mạch"; cột vote trên thẻ feed chiếu đúng điểm bài gốc. Mốc 1 đã xoá hoặc bị
 * mod ẩn ⇒ `0`, cùng chuẩn với `MocOut.score` của bia mộ.
 */
export type MachTomTatOut = {
    author: NguoiDungTomTatOut;
    /**
     * Comment Count
     */
    comment_count: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Diem
     */
    diem: number;
    /**
     * Entry Count
     */
    entry_count: number;
    /**
     * Id
     */
    id: number;
    /**
     * Ket Qua
     */
    ket_qua: string | null;
    /**
     * Last Activity At
     */
    last_activity_at: string;
    /**
     * Last Entry At
     */
    last_entry_at: string;
    /**
     * Moc 1 Id
     */
    moc_1_id: number | null;
    /**
     * Slug
     */
    slug: string;
    /**
     * Status
     */
    status: string;
    sub: SubTomTatOut;
    /**
     * Title
     */
    title: string;
    xem_truoc: XemTruocOut | null;
};

/**
 * MocMoiIn
 *
 * Nối một mốc vào mạch — `POST /machs/{id}/mocs` (PLAN 5.1, 5.2).
 *
 * `occurred_at` là ngày **sự việc xảy ra**: nhập lùi thoải mái, **cấm tương lai**, và
 * "tương lai" tính theo **ngày lịch VN** (PLAN mục 1). Không gửi ⇒ server lấy hôm nay
 * giờ VN.
 */
export type MocMoiIn = {
    /**
     * Body
     */
    body: string;
    /**
     * Figures
     */
    figures?: Array<FigureIn> | null;
    /**
     * Loai
     */
    loai?: string | null;
    /**
     * Occurred At
     */
    occurred_at?: string | null;
    /**
     * Question For Crowd
     */
    question_for_crowd?: string | null;
};

/**
 * MocOut
 *
 * Một mốc trong mạch. Bài gốc là `seq = 1`, không có ngoại lệ (PLAN mục 2).
 *
 * Khi `trang_thai != "binh_thuong"` thì đây là **bia mộ**: `body`, `loai`, `figures`,
 * `question_for_crowd`, `edited_at`, **`author`** đều `null`, còn `edit_count` và
 * `score` về `0` — số phiếu của nội dung đã gỡ không được trả ra, cùng chuẩn với
 * `BinhLuanOut`. `seq`, `occurred_at`, `so_binh_luan` và chỗ đứng trên spine vẫn còn:
 * `seq` bất biến, giấu hẳn một ô là thủng dãy số, và ngăn kéo của bia mộ vẫn mở được
 * (PLAN 5.2).
 */
export type MocOut = {
    /**
     * Anhs
     */
    anhs: Array<AnhOut>;
    author: NguoiDungTomTatOut | null;
    /**
     * Body
     */
    body: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Edit Count
     */
    edit_count: number;
    /**
     * Edited At
     */
    edited_at: string | null;
    /**
     * Figures
     */
    figures: Array<FigureOut> | null;
    /**
     * Id
     */
    id: number;
    /**
     * Loai
     */
    loai: string | null;
    /**
     * Occurred At
     */
    occurred_at: string;
    /**
     * Question For Crowd
     */
    question_for_crowd: string | null;
    /**
     * Reactions
     */
    reactions: {
        [key: string]: number;
    };
    /**
     * Score
     */
    score: number;
    /**
     * Seq
     */
    seq: number;
    /**
     * So Binh Luan
     */
    so_binh_luan: number;
    /**
     * Sua Im Lang Den
     */
    sua_im_lang_den: string;
    /**
     * Trang Thai
     */
    trang_thai: 'binh_thuong' | 'da_xoa' | 'da_an';
    trich: TrichOut | null;
};

/**
 * MocRevisionOut
 *
 * Một bản TRƯỚC của mốc — đủ cả 5 trường sửa được, cho UI diff (PLAN 5.2).
 *
 * Có `occurred_at` là bắt buộc: sửa lùi ngày sự việc mà không để vết là phá đúng giá
 * trị lõi của sản phẩm, nên diff phải hiện được cả thay đổi ngày.
 */
export type MocRevisionOut = {
    /**
     * Body
     */
    body: string;
    /**
     * Figures
     */
    figures: Array<FigureOut> | null;
    /**
     * Id
     */
    id: number;
    /**
     * Loai
     */
    loai: string | null;
    /**
     * Occurred At
     */
    occurred_at: string;
    /**
     * Question For Crowd
     */
    question_for_crowd: string | null;
    /**
     * Revised At
     */
    revised_at: string;
};

/**
 * MocRevisionsOut
 */
export type MocRevisionsOut = {
    /**
     * Items
     */
    items: Array<MocRevisionOut>;
    /**
     * Moc Id
     */
    moc_id: number;
    /**
     * Moc Seq
     */
    moc_seq: number;
};

/**
 * MocSuaIn
 *
 * Sửa mốc — `PATCH /mocs/{id}`. **Đúng 5 trường của PLAN 5.2, không gì khác.**
 *
 * Đây là PATCH thật: trường **không gửi** thì không đổi, trường gửi `null` thì xoá.
 * Phân biệt hai ca đó bằng `model_fields_set` của pydantic, nên đừng đổi `None` mặc
 * định thành một sentinel khác — `api/mocs.py` đọc đúng cơ chế ấy.
 */
export type MocSuaIn = {
    /**
     * Body
     */
    body?: string | null;
    /**
     * Figures
     */
    figures?: Array<FigureIn> | null;
    /**
     * Loai
     */
    loai?: string | null;
    /**
     * Occurred At
     */
    occurred_at?: string | null;
    /**
     * Question For Crowd
     */
    question_for_crowd?: string | null;
};

/**
 * NganKeoOut
 *
 * Lát cắt bình luận neo vào một mốc — PLAN 5.4.
 *
 * Chứa các thread có bình luận **gốc** neo mốc này, **cả thread**, gồm reply viết ở bất
 * kỳ thời điểm nào. Sắp cũ → mới và **không cho chỉnh** — ngăn kéo là cửa sổ, không
 * phải phòng (luật 2).
 *
 * Mốc chưa có bình luận nào trả `threads: []` và `so_binh_luan: 0`; UI **không** hiện
 * "💬 0" mà hiện lời mời cùng `question_for_crowd` nếu có (luật 4).
 */
export type NganKeoOut = {
    /**
     * Moc Id
     */
    moc_id: number;
    /**
     * Moc Seq
     */
    moc_seq: number;
    /**
     * Question For Crowd
     */
    question_for_crowd: string | null;
    /**
     * So Binh Luan
     */
    so_binh_luan: number;
    /**
     * Threads
     */
    threads: Array<BinhLuanOut>;
};

/**
 * NguoiDungTomTatOut
 *
 * Tác giả, ở mức đủ để render một dòng chữ ký.
 */
export type NguoiDungTomTatOut = {
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Username
     */
    username: string;
};

/**
 * NoiDungCuaToiOut
 *
 * Một mảnh nội dung **của chính người gọi** đang bị che ở cửa công khai — PLAN 5.2 + 5.10.
 *
 * PLAN 5.10 chốt moderation là *"ẩn (soft-hide — **tác giả vẫn thấy kèm nhãn**)"*, và
 * PLAN 5.2 nhắc lại: *"tác giả thấy **nội dung**, người khác thấy nhãn"*. Vế ấy không cài
 * được ở `GET /machs/{id}` — cửa đó bị ép **không chứa gì per-user** vì cả trang cache
 * theo URL (PLAN 8.4), nên nhét nội dung của tác giả vào là phục vụ nó cho mọi người mở
 * cùng URL. Vì thế nó sống ở đây: `GET /machs/{id}/me` vốn đã per-user, đã `no-store`,
 * và đã chạy trên mọi lượt tải trang mạch.
 *
 * Client vá `body` này vào đúng ô trống mà `GET /machs/{id}` để lại, kèm nhãn của
 * `trang_thai` — **không** xoá nhãn đi. Tác giả phải biết là người khác KHÔNG đọc được.
 *
 * ⚠ **Chỉ có mặt khi người gọi là `author` của chính mảnh đó.** Đây là chỗ nguy hiểm
 * nhất của cả cửa này: trả nhầm của người khác biến một bản vá minh bạch thành một lỗ
 * rò nội dung đã bị mod gỡ, trên một endpoint không ai soi vì nó "chỉ trả trạng thái".
 * `tests/test_api_noi_dung_cua_toi.py` đo **cả hai chiều**.
 */
export type NoiDungCuaToiOut = {
    /**
     * Body
     */
    body: string;
    /**
     * Id
     */
    id: number;
    /**
     * Loai
     */
    loai: 'moc' | 'comment';
    /**
     * Seq
     */
    seq: number | null;
    /**
     * Trang Thai
     */
    trang_thai: 'binh_thuong' | 'da_xoa' | 'da_an';
};

/**
 * ReactionCuaToiOut
 *
 * Reaction của **người đang xem** trên một mốc. Một user tối đa một reaction mỗi mốc.
 */
export type ReactionCuaToiOut = {
    /**
     * Emoji
     */
    emoji: string;
    /**
     * Moc Id
     */
    moc_id: number;
};

/**
 * ReactionIn
 *
 * React / đổi / rút — `POST /mocs/{id}/reactions` (PLAN 5.7).
 *
 * Bộ CỐ ĐỊNH `len · xuong · lua · bang · trung` (📈📉🔥🧊🎯). `emoji = null` là **rút**.
 */
export type ReactionIn = {
    /**
     * Emoji
     */
    emoji?: string | null;
};

/**
 * ReactionOut
 *
 * Kết quả một lượt reaction — `POST /mocs/{id}/reactions`. `emoji = null` là đã rút.
 */
export type ReactionOut = {
    /**
     * Dem
     */
    dem: {
        [key: string]: number;
    };
    /**
     * Emoji
     */
    emoji: string | null;
    /**
     * Moc Id
     */
    moc_id: number;
};

/**
 * SpineOut
 *
 * Một ô trên dải xương sống `①──②──…──◉⑨` (PLAN 9.2).
 *
 * `da_xoa` và `da_an` đều giữ chỗ: bất biến `entry_count == số ô trên spine` là thứ dải
 * gập của mặt CẶN suy ra (PLAN 5.2, 5.5).
 */
export type SpineOut = {
    /**
     * Da An
     */
    da_an: boolean;
    /**
     * Da Xoa
     */
    da_xoa: boolean;
    /**
     * Occurred At
     */
    occurred_at: string;
    /**
     * Seq
     */
    seq: number;
    /**
     * So Binh Luan
     */
    so_binh_luan: number;
};

/**
 * SubChiTietOut
 *
 * Header của trang `/s/<slug>` — plan con 1d §2.3.
 *
 * `so_mach` đếm mạch **hiện được**: chỉ loại mạch bị mod ẩn (`hidden_at`), đúng bộ lọc
 * của `api/feeds.py::_mach_hien`.
 *
 * ⚠ **Không phải "đúng bộ lọc mà hai feed dùng"** *(sửa ở W12, lượt vá 2 — câu cũ nói
 * quá)*: `/feeds/dang-dien-ra` lọc THÊM `status=MO`, nên với một chuyên mục có mạch đã
 * đóng sổ thì `so_mach` lớn hơn tổng số thẻ của feed đó kể cả khi không cắt trang. Con
 * số này khớp tập của `/feeds/moi`, không khớp tập của `/feeds/dang-dien-ra`.
 *
 * Và ngay cả với `/feeds/moi` thì đừng suy con số này ra số thẻ trên màn hình: feed cắt
 * trang, còn `?khoang=` cắt thêm theo `created_at`.
 */
export type SubChiTietOut = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Mo Ta
     */
    mo_ta: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * So Mach
     */
    so_mach: number;
    /**
     * Ten
     */
    ten: string;
};

/**
 * SubTomTatOut
 */
export type SubTomTatOut = {
    /**
     * Slug
     */
    slug: string;
    /**
     * Ten
     */
    ten: string;
};

/**
 * TheoMachOut
 *
 * Kết quả `POST`/`DELETE /machs/{id}/follow` — PLAN 5.7. Cả hai đều idempotent.
 *
 * `last_seen_entry_seq` có mặt vì lượt theo ĐẦU TIÊN đặt nó bằng `entry_count` hiện tại,
 * không phải `0`: người ta theo để biết chuyện **sắp** xảy ra, không phải để bị giao lại
 * toàn bộ quá khứ (xem `core.ghi.dat_follow`). Bỏ theo ⇒ `false` và `0`.
 */
export type TheoMachOut = {
    /**
     * Following
     */
    following: boolean;
    /**
     * Last Seen Entry Seq
     */
    last_seen_entry_seq: number;
    /**
     * Mach Id
     */
    mach_id: number;
};

/**
 * ThongBaoOut
 *
 * Một dòng chuông — PLAN 5.8.
 *
 * `payload` là **JSON tự do có chủ đích**: ba loại thông báo mang ba bộ trường khác nhau,
 * và ép chúng vào một schema chung sẽ ra một object mà 2/3 số trường luôn `null`. Các
 * khoá chung cho cả ba loại: `mach_id`, `mach_title`, `mach_slug` — đủ để render một
 * dòng có link mà **không phải join** sang bảng nào, điều kiện để chuông poll 60 giây
 * một lần không thành một câu truy vấn nặng.
 *
 * Cái giá của việc chép sẵn tiêu đề vào payload: đổi tiêu đề mạch thì dòng chuông cũ giữ
 * tiêu đề tại thời điểm báo. Đó là hành vi ĐÚNG cho một thông báo — nó kể lại một sự
 * kiện đã xảy ra — không phải một chỗ dữ liệu trôi.
 *
 * `type`: `"moc_moi"` | `"trich"` | `"reply"`.
 */
export type ThongBaoOut = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Id
     */
    id: number;
    /**
     * Payload
     */
    payload: {
        [key: string]: unknown;
    };
    /**
     * Read At
     */
    read_at: string | null;
    /**
     * Type
     */
    type: string;
};

/**
 * TimKiemOut
 *
 * Một trang kết quả tìm kiếm.
 *
 * `co_the_tim = false` là **xuống thang**, không phải lỗi: Meilisearch chưa cấu hình
 * hoặc đang hỏng. Endpoint vẫn trả 200 để trang gọi vẽ được một câu nói bằng tiếng
 * người thay vì xử một mã lỗi như xử sự cố (plan con Phase 7 §5).
 *
 * `tong` là **ước lượng** của Meilisearch (`estimatedTotalHits`), đếm trước khi lớp lọc
 * Postgres chạy — nên `len(items)` có thể nhỏ hơn `tong` chia trang. Nói ra ở đây để
 * frontend không dựng bộ đếm trang chính xác trên một con số không chính xác.
 */
export type TimKiemOut = {
    /**
     * Co The Tim
     */
    co_the_tim: boolean;
    /**
     * Items
     */
    items: Array<KetQuaTimKiemOut>;
    /**
     * Q
     */
    q: string;
    /**
     * Tong
     */
    tong: number;
};

/**
 * ToiOut
 *
 * `GET /me` — người đang đăng nhập là ai (thêm ở Phase 2, PLAN mục 7).
 *
 * **Không cache được, và không được nướng vào page cache** (PLAN 8.4 điểm 4): đây là
 * response per-user thuần tuý. Khác `GET /machs/{id}/me` ở chỗ nó không phụ thuộc mạch
 * nào — header cần biết "ai đang đăng nhập" trên MỌI trang.
 *
 * Khách chưa đăng nhập nhận **200** kèm `dang_nhap = false`, không phải 401: header là
 * thứ render trên mọi trang, và một endpoint trả lỗi cho trạng thái bình thường nhất của
 * hệ thống sẽ đẩy frontend vào chỗ phải coi lỗi là chuyện thường.
 *
 * `google_bat` là **cấu hình server**, không phải trạng thái người dùng, và nó nằm ở đây
 * vì đúng một lý do: PLAN mục 4 cấm nút vĩnh viễn không bấm được, nên trang đăng nhập
 * phải biết có nên **render** nút Google hay không — `false` ⇒ nút **vắng mặt**, không
 * phải `disabled`.
 */
export type ToiOut = {
    /**
     * Dang Nhap
     */
    dang_nhap: boolean;
    /**
     * Display Name
     */
    display_name: string | null;
    /**
     * Email
     */
    email: string | null;
    /**
     * Email Da Xac Thuc
     */
    email_da_xac_thuc: boolean;
    /**
     * Google Bat
     */
    google_bat: boolean;
    /**
     * La Staff
     */
    la_staff: boolean;
    /**
     * Nhan Digest
     */
    nhan_digest: boolean;
    /**
     * Tran Anh Moi Moc
     */
    tran_anh_moi_moc: number;
    /**
     * Username
     */
    username: string | null;
};

/**
 * ToiSuaIn
 *
 * `PATCH /me` — tuỳ chọn của chính người đang đăng nhập (PLAN 5.8).
 *
 * **PATCH thật**: trường vắng mặt nghĩa là không đổi, nên `{}` là một request hợp lệ
 * không ghi gì. Tách khỏi `ToiOut` chứ không dùng chung một schema hai chiều: `ToiOut`
 * mang `username`, `email`, `la_staff`, `google_bat` — không cái nào người dùng đặt
 * được ở đây, và một schema hai chiều là lời mời nhận đại cả bốn.
 *
 * Hôm nay đúng **một** trường. Danh tính (`display_name`, `bio`) chưa mở ở cửa này: nó
 * là nội dung công khai, cần luật độ dài + sanitize riêng, và trộn nó vào cùng lượt vá
 * với một cái công tắc boolean là cách phần khó bị làm vội.
 */
export type ToiSuaIn = {
    /**
     * Nhan Digest
     */
    nhan_digest?: boolean | null;
};

/**
 * TrichIn
 *
 * `POST /mocs/{id}/trich` — chủ mạch ghi một câu khán đài vào sổ (PLAN 5.6).
 *
 * Chỉ có `comment_id`: **mốc nhận trích nằm ở URL**, không nằm trong thân. Hai thứ đó
 * không được cùng ở một chỗ vì rào 1 ("tối đa 1 trích đang hiệu lực mỗi mốc") là một
 * ràng buộc trên `moc`, và người gọi phải nói rõ mốc nào trước khi server đi kiểm.
 *
 * Không có trường `body`: sổ trích **dẫn lại** một bình luận đã tồn tại, không phải chỗ
 * chủ mạch tự viết một câu rồi gán tên người khác vào.
 */
export type TrichIn = {
    /**
     * Comment Id
     */
    comment_id: number;
};

/**
 * TrichKetQuaOut
 *
 * Kết quả `POST`/`DELETE /mocs/{id}/trich` — PLAN 5.6.
 *
 * Trả về **cả thẻ mốc** (`moc`) chứ không chỉ mỗi khối trích: rào 4 của PLAN 5.6 bắt
 * khối trích render **tách bạch khỏi thân mốc** như một chú thích, nên UI phải vẽ lại cả
 * cái thẻ. Trả mỗi `TrichOut` thì client phải tự ghép vào state của thẻ — tức có một bản
 * thứ hai của luật "trích gắn vào đâu", và bản đó sẽ trôi.
 *
 * `moc.trich` là `null` sau khi gỡ. Hình dạng `moc` giống hệt `GET /machs/{id}`.
 */
export type TrichKetQuaOut = {
    moc: MocOut;
};

/**
 * TrichOut
 *
 * Bình luận được chủ mạch trích vào mốc — "trích vào sổ" (PLAN 5.6).
 *
 * Hai dấu thời gian đều có mặt vì rào 2 của PLAN 5.6 bắt blockquote hiện đủ cả hai
 * ("viết 10/06, trích 21/08") — chống trích hậu nghiệm để sổ đọc như tiên tri.
 *
 * `trang_thai = "da_xoa"` nghĩa là người viết đã xoá bình luận gốc **sau khi** nó vào
 * sổ; blockquote vẫn còn nguyên nội dung, vì sổ là "không-xoá-được" (PLAN 5.6). Bình
 * luận bị **mod ẩn** thì cả khối trích biến mất khỏi response, không có trạng thái nào
 * biểu diễn nó.
 */
export type TrichOut = {
    /**
     * Anchor Moc Seq
     */
    anchor_moc_seq: number | null;
    author: NguoiDungTomTatOut;
    /**
     * Body
     */
    body: string;
    /**
     * Comment Created At
     */
    comment_created_at: string;
    /**
     * Comment Id
     */
    comment_id: number;
    /**
     * Trang Thai
     */
    trang_thai: 'binh_thuong' | 'da_xoa' | 'da_an';
    /**
     * Trich Created At
     */
    trich_created_at: string;
};

/**
 * VoteCuaToiOut
 *
 * Một lá phiếu của **người đang xem** trên một mốc hoặc một bình luận của mạch này.
 */
export type VoteCuaToiOut = {
    /**
     * Target Id
     */
    target_id: number;
    /**
     * Target Type
     */
    target_type: string;
    /**
     * Value
     */
    value: number;
};

/**
 * VoteIn
 *
 * Vote / đổi / rút — `POST /votes` (PLAN 5.7, mục 7).
 *
 * `value = 0` nghĩa là **rút**: hàng `Vote` bị xoá, không lưu `0`.
 */
export type VoteIn = {
    /**
     * Target Id
     */
    target_id: number;
    /**
     * Target Type
     *
     * "moc" hoặc "comment"
     */
    target_type: string;
    /**
     * Value
     */
    value: number;
};

/**
 * VoteOut
 *
 * Kết quả một lượt vote — `POST /votes` (PLAN 5.7).
 *
 * Trả về **con số mới của đích** chứ không chỉ "ok": UI vote lạc quan (optimistic) cần
 * một nguồn sự thật để đối chiếu sau khi mạng trả lời, nếu không hai lượt bấm nhanh sẽ
 * để lại một con số client tự cộng mà server không đồng ý. `value = 0` nghĩa là vừa rút.
 *
 * `up_count`/`down_count` chỉ có nghĩa với đích là **bình luận** — mốc chỉ lưu `score`
 * (PLAN mục 6), nên với mốc hai trường này là `null`, không phải `0`.
 */
export type VoteOut = {
    /**
     * Down Count
     */
    down_count: number | null;
    /**
     * Score
     */
    score: number;
    /**
     * Target Id
     */
    target_id: number;
    /**
     * Target Type
     */
    target_type: string;
    /**
     * Up Count
     */
    up_count: number | null;
    /**
     * Value
     */
    value: number;
};

/**
 * XemTruocOut
 *
 * Nội dung xem trước của một thẻ feed, lấy từ **mốc 1**.
 *
 * ## Thứ tự ưu tiên, và vì sao chỉ có HAI tầng chứ không ba
 *
 * Yêu cầu ban đầu là ba tầng: **gallery → ảnh trong nội dung → chữ**. Tầng giữa hôm nay
 * **không có nguồn nào**: `body` của mốc đi qua bộ markdown tập-con ở
 * `apps/web/lib/markdown.ts`, và bộ ấy **cố ý không có cú pháp ảnh** (`![]()` in ra
 * thành văn bản thường). Nên không tồn tại đường nào để một tấm ảnh nằm *trong* nội
 * dung — ảnh chỉ sống ở gallery (`MocAnh`).
 *
 * Trường `anh` vì thế mang đúng một nghĩa hôm nay: **ảnh đầu của gallery**. Ngày nào
 * markdown mở cú pháp ảnh thì tầng giữa cắm vào đây mà không đổi hình dạng schema —
 * người gọi vẫn chỉ hỏi "có ảnh không", không hỏi "ảnh từ đâu ra".
 *
 * ## `trich` LUÔN có mặt, kể cả khi đã có ảnh
 *
 * Không phải để vẽ cả hai: nó là `alt` của tấm ảnh, và là thứ hiện ra khi ảnh chưa tải
 * xong hoặc tải hỏng. Một thẻ feed rỗng vì một tấm ảnh 404 là một thẻ không ai bấm.
 */
export type XemTruocOut = {
    anh: AnhOut | null;
    /**
     * So Anh
     */
    so_anh: number;
    /**
     * Trich
     */
    trich: string;
};

export type XoaAnhMocData = {
    body?: never;
    path: {
        /**
         * Anh Id
         */
        anh_id: number;
    };
    query?: never;
    url: '/api/v1/anh/{anh_id}';
};

export type XoaAnhMocErrors = {
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
};

export type XoaAnhMocError = XoaAnhMocErrors[keyof XoaAnhMocErrors];

export type XoaAnhMocResponses = {
    /**
     * OK
     */
    200: AnhOut;
};

export type XoaAnhMocResponse = XoaAnhMocResponses[keyof XoaAnhMocResponses];

export type XoaBinhLuanData = {
    body?: never;
    path: {
        /**
         * Comment Id
         */
        comment_id: number;
    };
    query?: never;
    url: '/api/v1/comments/{comment_id}';
};

export type XoaBinhLuanErrors = {
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
    /**
     * Conflict
     */
    409: LoiOut;
};

export type XoaBinhLuanError = XoaBinhLuanErrors[keyof XoaBinhLuanErrors];

export type XoaBinhLuanResponses = {
    /**
     * OK
     */
    200: KetQuaXoaOut;
};

export type XoaBinhLuanResponse = XoaBinhLuanResponses[keyof XoaBinhLuanResponses];

export type SuaBinhLuanData = {
    body: BinhLuanSuaIn;
    path: {
        /**
         * Comment Id
         */
        comment_id: number;
    };
    query?: never;
    url: '/api/v1/comments/{comment_id}';
};

export type SuaBinhLuanErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
    /**
     * Conflict
     */
    409: LoiOut;
};

export type SuaBinhLuanError = SuaBinhLuanErrors[keyof SuaBinhLuanErrors];

export type SuaBinhLuanResponses = {
    /**
     * OK
     */
    200: BinhLuanOut;
};

export type SuaBinhLuanResponse = SuaBinhLuanResponses[keyof SuaBinhLuanResponses];

export type LietKeFeedDangDienRaData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Sub
         */
        sub?: string | null;
        /**
         * Sort
         */
        sort?: 'tu_nhien' | 'nhieu_diem';
        /**
         * Khoang
         */
        khoang?: 'ngay' | 'tuan' | 'thang' | 'tat_ca';
        /**
         * Cursor
         */
        cursor?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/feeds/dang-dien-ra';
};

export type LietKeFeedDangDienRaErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
};

export type LietKeFeedDangDienRaError = LietKeFeedDangDienRaErrors[keyof LietKeFeedDangDienRaErrors];

export type LietKeFeedDangDienRaResponses = {
    /**
     * OK
     */
    200: FeedOut;
};

export type LietKeFeedDangDienRaResponse = LietKeFeedDangDienRaResponses[keyof LietKeFeedDangDienRaResponses];

export type LietKeFeedMoiData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Sub
         */
        sub?: string | null;
        /**
         * Sort
         */
        sort?: 'tu_nhien' | 'nhieu_diem';
        /**
         * Khoang
         */
        khoang?: 'ngay' | 'tuan' | 'thang' | 'tat_ca';
        /**
         * Cursor
         */
        cursor?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/feeds/moi';
};

export type LietKeFeedMoiErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
};

export type LietKeFeedMoiError = LietKeFeedMoiErrors[keyof LietKeFeedMoiErrors];

export type LietKeFeedMoiResponses = {
    /**
     * OK
     */
    200: FeedOut;
};

export type LietKeFeedMoiResponse = LietKeFeedMoiResponses[keyof LietKeFeedMoiResponses];

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type GetHealthErrors = {
    /**
     * Service Unavailable
     */
    503: HealthOut;
};

export type GetHealthError = GetHealthErrors[keyof GetHealthErrors];

export type GetHealthResponses = {
    /**
     * OK
     */
    200: HealthOut;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type TaoMachData = {
    body: MachMoiIn;
    path?: never;
    query?: never;
    url: '/api/v1/machs';
};

export type TaoMachErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
    /**
     * Too Many Requests
     */
    429: LoiThoiGianOut;
};

export type TaoMachError = TaoMachErrors[keyof TaoMachErrors];

export type TaoMachResponses = {
    /**
     * Created
     */
    201: MachChiTietOut;
};

export type TaoMachResponse = TaoMachResponses[keyof TaoMachResponses];

export type XemMachData = {
    body?: never;
    path: {
        /**
         * Mach Id
         */
        mach_id: number;
    };
    query?: never;
    url: '/api/v1/machs/{mach_id}';
};

export type XemMachErrors = {
    /**
     * Not Found
     */
    404: LoiOut;
};

export type XemMachError = XemMachErrors[keyof XemMachErrors];

export type XemMachResponses = {
    /**
     * OK
     */
    200: MachChiTietOut;
};

export type XemMachResponse = XemMachResponses[keyof XemMachResponses];

export type DongSoMachData = {
    body: DongSoIn;
    path: {
        /**
         * Mach Id
         */
        mach_id: number;
    };
    query?: never;
    url: '/api/v1/machs/{mach_id}/close';
};

export type DongSoMachErrors = {
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
    /**
     * Conflict
     */
    409: LoiOut;
};

export type DongSoMachError = DongSoMachErrors[keyof DongSoMachErrors];

export type DongSoMachResponses = {
    /**
     * OK
     */
    200: MachChiTietOut;
};

export type DongSoMachResponse = DongSoMachResponses[keyof DongSoMachResponses];

export type LietKeBinhLuanMachData = {
    body?: never;
    path: {
        /**
         * Mach Id
         */
        mach_id: number;
    };
    query?: {
        /**
         * Sort
         */
        sort?: string;
        /**
         * Cursor
         */
        cursor?: string | null;
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number | null;
        /**
         * Dang Doc
         */
        dang_doc?: boolean;
    };
    url: '/api/v1/machs/{mach_id}/comments';
};

export type LietKeBinhLuanMachErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
};

export type LietKeBinhLuanMachError = LietKeBinhLuanMachErrors[keyof LietKeBinhLuanMachErrors];

export type LietKeBinhLuanMachResponses = {
    /**
     * OK
     */
    200: KhanDaiOut;
};

export type LietKeBinhLuanMachResponse = LietKeBinhLuanMachResponses[keyof LietKeBinhLuanMachResponses];

export type VietBinhLuanData = {
    body: BinhLuanMoiIn;
    path: {
        /**
         * Mach Id
         */
        mach_id: number;
    };
    query?: never;
    url: '/api/v1/machs/{mach_id}/comments';
};

export type VietBinhLuanErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
    /**
     * Conflict
     */
    409: LoiOut;
    /**
     * Too Many Requests
     */
    429: LoiThoiGianOut;
};

export type VietBinhLuanError = VietBinhLuanErrors[keyof VietBinhLuanErrors];

export type VietBinhLuanResponses = {
    /**
     * Created
     */
    201: BinhLuanOut;
};

export type VietBinhLuanResponse = VietBinhLuanResponses[keyof VietBinhLuanResponses];

export type BoTheoMachData = {
    body?: never;
    path: {
        /**
         * Mach Id
         */
        mach_id: number;
    };
    query?: never;
    url: '/api/v1/machs/{mach_id}/follow';
};

export type BoTheoMachErrors = {
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
};

export type BoTheoMachError = BoTheoMachErrors[keyof BoTheoMachErrors];

export type BoTheoMachResponses = {
    /**
     * OK
     */
    200: TheoMachOut;
};

export type BoTheoMachResponse = BoTheoMachResponses[keyof BoTheoMachResponses];

export type TheoMachData = {
    body?: never;
    path: {
        /**
         * Mach Id
         */
        mach_id: number;
    };
    query?: never;
    url: '/api/v1/machs/{mach_id}/follow';
};

export type TheoMachErrors = {
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
};

export type TheoMachError = TheoMachErrors[keyof TheoMachErrors];

export type TheoMachResponses = {
    /**
     * OK
     */
    200: TheoMachOut;
};

export type TheoMachResponse = TheoMachResponses[keyof TheoMachResponses];

export type XemMachCuaToiData = {
    body?: never;
    path: {
        /**
         * Mach Id
         */
        mach_id: number;
    };
    query?: never;
    url: '/api/v1/machs/{mach_id}/me';
};

export type XemMachCuaToiErrors = {
    /**
     * Not Found
     */
    404: LoiOut;
};

export type XemMachCuaToiError = XemMachCuaToiErrors[keyof XemMachCuaToiErrors];

export type XemMachCuaToiResponses = {
    /**
     * OK
     */
    200: MachCuaToiOut;
};

export type XemMachCuaToiResponse = XemMachCuaToiResponses[keyof XemMachCuaToiResponses];

export type NoiMocData = {
    body: MocMoiIn;
    path: {
        /**
         * Mach Id
         */
        mach_id: number;
    };
    query?: never;
    url: '/api/v1/machs/{mach_id}/mocs';
};

export type NoiMocErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
    /**
     * Conflict
     */
    409: LoiOut;
    /**
     * Too Many Requests
     */
    429: LoiThoiGianOut;
};

export type NoiMocError = NoiMocErrors[keyof NoiMocErrors];

export type NoiMocResponses = {
    /**
     * Created
     */
    201: MocOut;
};

export type NoiMocResponse = NoiMocResponses[keyof NoiMocResponses];

export type MoLaiMachData = {
    body?: never;
    path: {
        /**
         * Mach Id
         */
        mach_id: number;
    };
    query?: never;
    url: '/api/v1/machs/{mach_id}/reopen';
};

export type MoLaiMachErrors = {
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
    /**
     * Conflict
     */
    409: LoiOut;
};

export type MoLaiMachError = MoLaiMachErrors[keyof MoLaiMachErrors];

export type MoLaiMachResponses = {
    /**
     * OK
     */
    200: MachChiTietOut;
};

export type MoLaiMachResponse = MoLaiMachResponses[keyof MoLaiMachResponses];

export type DanhDauDaXemData = {
    body: DaXemIn;
    path: {
        /**
         * Mach Id
         */
        mach_id: number;
    };
    query?: never;
    url: '/api/v1/machs/{mach_id}/seen';
};

export type DanhDauDaXemErrors = {
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
};

export type DanhDauDaXemError = DanhDauDaXemErrors[keyof DanhDauDaXemErrors];

export type DanhDauDaXemResponses = {
    /**
     * OK
     */
    200: DaXemOut;
};

export type DanhDauDaXemResponse = DanhDauDaXemResponses[keyof DanhDauDaXemResponses];

export type XemToiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/me';
};

export type XemToiResponses = {
    /**
     * OK
     */
    200: ToiOut;
};

export type XemToiResponse = XemToiResponses[keyof XemToiResponses];

export type SuaToiData = {
    body: ToiSuaIn;
    path?: never;
    query?: never;
    url: '/api/v1/me';
};

export type SuaToiErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
};

export type SuaToiError = SuaToiErrors[keyof SuaToiErrors];

export type SuaToiResponses = {
    /**
     * OK
     */
    200: ToiOut;
};

export type SuaToiResponse = SuaToiResponses[keyof SuaToiResponses];

export type XoaMocData = {
    body?: never;
    path: {
        /**
         * Moc Id
         */
        moc_id: number;
    };
    query?: never;
    url: '/api/v1/mocs/{moc_id}';
};

export type XoaMocErrors = {
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
    /**
     * Conflict
     */
    409: LoiOut;
};

export type XoaMocError = XoaMocErrors[keyof XoaMocErrors];

export type XoaMocResponses = {
    /**
     * OK
     */
    200: MocOut;
};

export type XoaMocResponse = XoaMocResponses[keyof XoaMocResponses];

export type SuaMocData = {
    body: MocSuaIn;
    path: {
        /**
         * Moc Id
         */
        moc_id: number;
    };
    query?: never;
    url: '/api/v1/mocs/{moc_id}';
};

export type SuaMocErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
    /**
     * Conflict
     */
    409: LoiOut;
};

export type SuaMocError = SuaMocErrors[keyof SuaMocErrors];

export type SuaMocResponses = {
    /**
     * OK
     */
    200: MocOut;
};

export type SuaMocResponse = SuaMocResponses[keyof SuaMocResponses];

export type TaiAnhMocData = {
    /**
     * FileParams
     */
    body: {
        /**
         * File
         */
        file: Blob | File;
    };
    path: {
        /**
         * Moc Id
         */
        moc_id: number;
    };
    query?: never;
    url: '/api/v1/mocs/{moc_id}/anh';
};

export type TaiAnhMocErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
    /**
     * Conflict
     */
    409: LoiOut;
    /**
     * Request Entity Too Large
     */
    413: LoiOut;
};

export type TaiAnhMocError = TaiAnhMocErrors[keyof TaiAnhMocErrors];

export type TaiAnhMocResponses = {
    /**
     * Created
     */
    201: AnhOut;
};

export type TaiAnhMocResponse = TaiAnhMocResponses[keyof TaiAnhMocResponses];

export type LietKeBinhLuanMocData = {
    body?: never;
    path: {
        /**
         * Moc Id
         */
        moc_id: number;
    };
    query?: never;
    url: '/api/v1/mocs/{moc_id}/comments';
};

export type LietKeBinhLuanMocErrors = {
    /**
     * Not Found
     */
    404: LoiOut;
};

export type LietKeBinhLuanMocError = LietKeBinhLuanMocErrors[keyof LietKeBinhLuanMocErrors];

export type LietKeBinhLuanMocResponses = {
    /**
     * OK
     */
    200: NganKeoOut;
};

export type LietKeBinhLuanMocResponse = LietKeBinhLuanMocResponses[keyof LietKeBinhLuanMocResponses];

export type DatReactionData = {
    body: ReactionIn;
    path: {
        /**
         * Moc Id
         */
        moc_id: number;
    };
    query?: never;
    url: '/api/v1/mocs/{moc_id}/reactions';
};

export type DatReactionErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
    /**
     * Conflict
     */
    409: LoiOut;
};

export type DatReactionError = DatReactionErrors[keyof DatReactionErrors];

export type DatReactionResponses = {
    /**
     * OK
     */
    200: ReactionOut;
};

export type DatReactionResponse = DatReactionResponses[keyof DatReactionResponses];

export type LietKeBanCuMocData = {
    body?: never;
    path: {
        /**
         * Moc Id
         */
        moc_id: number;
    };
    query?: never;
    url: '/api/v1/mocs/{moc_id}/revisions';
};

export type LietKeBanCuMocErrors = {
    /**
     * Not Found
     */
    404: LoiOut;
};

export type LietKeBanCuMocError = LietKeBanCuMocErrors[keyof LietKeBanCuMocErrors];

export type LietKeBanCuMocResponses = {
    /**
     * OK
     */
    200: MocRevisionsOut;
};

export type LietKeBanCuMocResponse = LietKeBanCuMocResponses[keyof LietKeBanCuMocResponses];

export type GoTrichData = {
    body?: never;
    path: {
        /**
         * Moc Id
         */
        moc_id: number;
    };
    query?: never;
    url: '/api/v1/mocs/{moc_id}/trich';
};

export type GoTrichErrors = {
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
    /**
     * Conflict
     */
    409: LoiOut;
};

export type GoTrichError = GoTrichErrors[keyof GoTrichErrors];

export type GoTrichResponses = {
    /**
     * OK
     */
    200: TrichKetQuaOut;
};

export type GoTrichResponse = GoTrichResponses[keyof GoTrichResponses];

export type TrichVaoSoData = {
    body: TrichIn;
    path: {
        /**
         * Moc Id
         */
        moc_id: number;
    };
    query?: never;
    url: '/api/v1/mocs/{moc_id}/trich';
};

export type TrichVaoSoErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
    /**
     * Conflict
     */
    409: LoiOut;
};

export type TrichVaoSoError = TrichVaoSoErrors[keyof TrichVaoSoErrors];

export type TrichVaoSoResponses = {
    /**
     * Created
     */
    201: TrichKetQuaOut;
};

export type TrichVaoSoResponse = TrichVaoSoResponses[keyof TrichVaoSoResponses];

export type LietKeThongBaoData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Cursor
         */
        cursor?: string | null;
    };
    url: '/api/v1/notifications';
};

export type LietKeThongBaoErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Unauthorized
     */
    401: LoiOut;
};

export type LietKeThongBaoError = LietKeThongBaoErrors[keyof LietKeThongBaoErrors];

export type LietKeThongBaoResponses = {
    /**
     * OK
     */
    200: ChuongOut;
};

export type LietKeThongBaoResponse = LietKeThongBaoResponses[keyof LietKeThongBaoResponses];

export type DanhDauDaDocData = {
    body: DanhDauDaDocIn;
    path?: never;
    query?: never;
    url: '/api/v1/notifications/read';
};

export type DanhDauDaDocErrors = {
    /**
     * Unauthorized
     */
    401: LoiOut;
};

export type DanhDauDaDocError = DanhDauDaDocErrors[keyof DanhDauDaDocErrors];

export type DanhDauDaDocResponses = {
    /**
     * OK
     */
    200: DaDocOut;
};

export type DanhDauDaDocResponse = DanhDauDaDocResponses[keyof DanhDauDaDocResponses];

export type GuiBaoCaoData = {
    body: BaoCaoMoiIn;
    path?: never;
    query?: never;
    url: '/api/v1/reports';
};

export type GuiBaoCaoErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
    /**
     * Conflict
     */
    409: LoiOut;
};

export type GuiBaoCaoError = GuiBaoCaoErrors[keyof GuiBaoCaoErrors];

export type GuiBaoCaoResponses = {
    /**
     * Created
     */
    201: BaoCaoDaGuiOut;
};

export type GuiBaoCaoResponse = GuiBaoCaoResponses[keyof GuiBaoCaoResponses];

export type LietKeSubData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/subs';
};

export type LietKeSubResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<SubChiTietOut>;
};

export type LietKeSubResponse = LietKeSubResponses[keyof LietKeSubResponses];

export type XemSubData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/subs/{slug}';
};

export type XemSubErrors = {
    /**
     * Not Found
     */
    404: LoiOut;
};

export type XemSubError = XemSubErrors[keyof XemSubErrors];

export type XemSubResponses = {
    /**
     * OK
     */
    200: SubChiTietOut;
};

export type XemSubResponse = XemSubResponses[keyof XemSubResponses];

export type TimKiemData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Q
         */
        q?: string;
        /**
         * Sub
         */
        sub?: string | null;
        /**
         * Sort
         */
        sort?: 'lien_quan' | 'moi';
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/tim-kiem';
};

export type TimKiemErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
};

export type TimKiemError = TimKiemErrors[keyof TimKiemErrors];

export type TimKiemResponses = {
    /**
     * OK
     */
    200: TimKiemOut;
};

export type TimKiemResponse = TimKiemResponses[keyof TimKiemResponses];

export type XemHoSoData = {
    body?: never;
    path: {
        /**
         * Username
         */
        username: string;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/{username}';
};

export type XemHoSoErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
};

export type XemHoSoError = XemHoSoErrors[keyof XemHoSoErrors];

export type XemHoSoResponses = {
    /**
     * OK
     */
    200: HoSoOut;
};

export type XemHoSoResponse = XemHoSoResponses[keyof XemHoSoResponses];

export type DatVoteData = {
    body: VoteIn;
    path?: never;
    query?: never;
    url: '/api/v1/votes';
};

export type DatVoteErrors = {
    /**
     * Bad Request
     */
    400: LoiOut;
    /**
     * Unauthorized
     */
    401: LoiOut;
    /**
     * Forbidden
     */
    403: LoiOut;
    /**
     * Not Found
     */
    404: LoiOut;
    /**
     * Conflict
     */
    409: LoiOut;
};

export type DatVoteError = DatVoteErrors[keyof DatVoteErrors];

export type DatVoteResponses = {
    /**
     * OK
     */
    200: VoteOut;
};

export type DatVoteResponse = DatVoteResponses[keyof DatVoteResponses];
