# Generated by Django 5.2.17 on 2026-08-21 14:52

import core.models.moc
import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('ten', models.CharField(max_length=80)),
                ('mo_ta', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'sub',
                'verbose_name_plural': 'subs',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='ban_permanent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='ban_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='banned_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('target_type', models.CharField(max_length=16)),
                ('target_id', models.BigIntegerField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=60)),
                ('title', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('open', 'Đang mở'), ('closed', 'Đã đóng sổ')], default='open', max_length=8)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('ket_qua', models.CharField(blank=True, max_length=40, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('last_entry_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('entry_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machs', to=settings.AUTH_USER_MODEL)),
                ('hidden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machs_da_an', to=settings.AUTH_USER_MODEL)),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machs', to='core.sub')),
            ],
            options={
                'verbose_name': 'mạch',
                'verbose_name_plural': 'mạch',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_moc_seq', models.PositiveIntegerField(blank=True, null=True)),
                ('body', models.TextField(validators=[django.core.validators.MaxLengthValidator(10000)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('up_count', models.PositiveIntegerField(default=0)),
                ('down_count', models.PositiveIntegerField(default=0)),
                ('score', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('up_count'), '-', models.F('down_count')), output_field=models.IntegerField())),
                ('path', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('hidden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments_da_an', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.comment')),
                ('mach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.mach')),
            ],
            options={
                'verbose_name': 'bình luận',
                'verbose_name_plural': 'bình luận',
            },
        ),
        migrations.CreateModel(
            name='Moc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('occurred_at', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('loai', models.CharField(blank=True, max_length=20, null=True)),
                ('body', models.TextField(validators=[django.core.validators.MaxLengthValidator(10000)])),
                ('question_for_crowd', models.CharField(blank=True, max_length=200, null=True)),
                ('figures', models.JSONField(blank=True, null=True, validators=[core.models.moc.kiem_figures])),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('edit_count', models.PositiveIntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mocs', to=settings.AUTH_USER_MODEL)),
                ('hidden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mocs_da_an', to=settings.AUTH_USER_MODEL)),
                ('mach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mocs', to='core.mach')),
            ],
            options={
                'verbose_name': 'mốc',
                'verbose_name_plural': 'mốc',
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='MocAnh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r2_key', models.CharField(max_length=255)),
                ('thumb_key', models.CharField(blank=True, max_length=255, null=True)),
                ('exif_taken_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận')], default='pending', max_length=10)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('w', models.PositiveIntegerField(blank=True, null=True)),
                ('h', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('moc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anhs', to='core.moc')),
            ],
            options={
                'verbose_name': 'ảnh của mốc',
                'verbose_name_plural': 'ảnh của mốc',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MocRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('figures', models.JSONField(blank=True, null=True)),
                ('occurred_at', models.DateField()),
                ('loai', models.CharField(blank=True, max_length=20, null=True)),
                ('question_for_crowd', models.CharField(blank=True, max_length=200, null=True)),
                ('revised_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('moc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='core.moc')),
            ],
            options={
                'verbose_name': 'bản cũ của mốc',
                'verbose_name_plural': 'bản cũ của mốc',
                'ordering': ['-revised_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dedupe_key', models.CharField(blank=True, max_length=120, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'thông báo',
                'verbose_name_plural': 'thông báo',
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('len', '📈 lên'), ('xuong', '📉 xuống'), ('lua', '🔥 lửa'), ('bang', '🧊 băng'), ('trung', '🎯 trúng')], max_length=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('moc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.moc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reaction',
                'verbose_name_plural': 'reaction',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('mach', 'Mạch'), ('moc', 'Mốc'), ('comment', 'Bình luận')], max_length=8)),
                ('target_id', models.BigIntegerField()),
                ('ly_do', models.CharField(choices=[('phim_hang', 'Hô hào mua bán / phím hàng'), ('lua_dao', 'Lừa đảo, mời uỷ thác, room VIP'), ('spam', 'Spam'), ('khac', 'Khác')], max_length=16)),
                ('ghi_chu', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(blank=True, max_length=32, null=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_da_xu_ly', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'báo cáo',
                'verbose_name_plural': 'báo cáo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trichs', to='core.comment')),
                ('moc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trichs', to='core.moc')),
            ],
            options={
                'verbose_name': 'trích vào sổ',
                'verbose_name_plural': 'trích vào sổ',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('moc', 'Mốc'), ('comment', 'Bình luận')], max_length=8)),
                ('target_id', models.BigIntegerField()),
                ('value', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vote',
                'verbose_name_plural': 'vote',
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_seen_entry_seq', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to=settings.AUTH_USER_MODEL)),
                ('mach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='core.mach')),
            ],
            options={
                'verbose_name': 'theo mạch',
                'verbose_name_plural': 'theo mạch',
                'constraints': [models.UniqueConstraint(fields=('user', 'mach'), name='follow_duy_nhat_mach')],
            },
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(condition=models.Q(('parent__isnull', True)), fields=['mach', 'anchor_moc_seq'], name='comment_anchor_goc'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['mach', 'author'], name='comment_mach_author'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('mach', 'path'), name='comment_duy_nhat_path'),
        ),
        migrations.AddConstraint(
            model_name='moc',
            constraint=models.UniqueConstraint(fields=('mach', 'seq'), name='moc_duy_nhat_seq'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notif_user_created'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('user', 'dedupe_key'), name='notification_duy_nhat_dedupe'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(fields=('user', 'moc'), name='reaction_duy_nhat_moc'),
        ),
        migrations.AddIndex(
            model_name='mach',
            index=models.Index(fields=['sub', '-last_entry_at'], name='mach_sub_last_entry'),
        ),
        migrations.AddIndex(
            model_name='mach',
            index=models.Index(fields=['author', '-created_at'], name='mach_author_created'),
        ),
        migrations.AddIndex(
            model_name='mach',
            index=models.Index(fields=['-created_at'], name='mach_created_desc'),
        ),
        migrations.AddIndex(
            model_name='mach',
            index=models.Index(condition=models.Q(('status', 'open')), fields=['-last_entry_at'], name='mach_open_last_entry'),
        ),
        migrations.AddConstraint(
            model_name='trich',
            constraint=models.UniqueConstraint(condition=models.Q(('removed_at__isnull', True)), fields=('moc',), name='trich_mot_hieu_luc_moi_moc'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('user', 'target_type', 'target_id'), name='vote_duy_nhat_dich'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.CheckConstraint(condition=models.Q(('value__in', [-1, 1])), name='vote_gia_tri_hop_le'),
        ),
    ]
