# Generated by Django 5.2.17 on 2026-08-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_site_gikky'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nhan_digest',
            field=models.BooleanField(default=False),
        ),
    ]
