# Generated by Django 5.2.17 on 2026-08-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_nhan_digest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dang_ky_ip',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
    ]
