# Generated by Django 5.2.17 on 2026-08-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_phase6_han_muc_dang_ky_ip'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('resolved_at__isnull', True)), fields=('reporter', 'target_type', 'target_id'), name='bao_cao_mot_lan_moi_dich_dang_mo'),
        ),
    ]
