# Generated by Django 5.2.17 on 2026-08-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0010_phase_5_anh_local'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['dang_ky_ip', 'date_joined'], name='user_dangky_ip_ngay_idx'),
        ),
    ]
