# Generated by Django 5.2.17 on 2026-08-24 04:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_phase7_l40_index_dang_ky_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mods', to='core.sub')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_dang_mod', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mod chuyên mục',
                'verbose_name_plural': 'mod chuyên mục',
                'constraints': [models.UniqueConstraint(fields=('sub', 'user'), name='modsub_duy_nhat_sub_user')],
            },
        ),
    ]
