# Generated by Django 5.2.17 on 2026-08-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_modsub'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_khoa',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
