"""Bảng `AnhNoiDung` — ảnh nhúng thẳng vào thân bài (`plans/2026-08-24-tiptap-html.md`).

Chỉ `CreateModel`, không `RunPython`: đây là bảng MỚI cho một cửa upload mới, không có
dữ liệu cũ nào phải chuyển. Ảnh gallery (`MocAnh`) và avatar (`User.avatar_khoa`) ở
nguyên chỗ cũ — ba loài ảnh dùng chung thư mục đĩa nhưng ba bảng/cột khác nhau, xem
`core/management/commands/don_anh_mo_coi.py` để biết cả ba được whitelist ở đâu.

`khoa_luu_tru` **unique**: nó là khoá whitelist của lệnh dọn mồ côi, và hai hàng cùng khoá
nghĩa là xoá một hàng mà file vẫn "hợp lệ" nhờ hàng kia.

Lùi được sạch (`DeleteModel`) — nhưng lùi rồi thì mọi ảnh nội dung đã tải mất whitelist,
nên lượt `don_anh_mo_coi` kế tiếp sẽ XOÁ THẬT chúng. Lùi migration này đi kèm việc tắt
lệnh dọn cho tới khi tiến lại.
"""

# Generated by Django 5.2.17 on 2026-08-24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_phase_tiptap_body_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnhNoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('khoa_luu_tru', models.CharField(max_length=255, unique=True)),
                ('w', models.PositiveIntegerField(blank=True, null=True)),
                ('h', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('nguoi_tai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anh_noi_dung', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ảnh nội dung',
                'verbose_name_plural': 'ảnh nội dung',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['nguoi_tai', 'created_at'], name='anhnd_nguoi_ngay_idx')],
            },
        ),
    ]
