# Generated by Django 5.2.17 on 2026-08-24 15:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_anh_noi_dung'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheoSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nguoi_theo', to='core.sub')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theo_subs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'theo chuyên mục',
                'verbose_name_plural': 'theo chuyên mục',
                'indexes': [models.Index(fields=['user', '-created_at'], name='theo_sub_cua_user')],
                'constraints': [models.UniqueConstraint(fields=('user', 'sub'), name='theo_sub_duy_nhat')],
            },
        ),
    ]
