# Generated by Django 5.2.17 on 2026-08-26 01:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_reaction_emoji'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('nguoi_duoc_theo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nguoi_theo_toi', to=settings.AUTH_USER_MODEL)),
                ('nguoi_theo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dang_theo_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'theo người dùng',
                'verbose_name_plural': 'theo người dùng',
                'indexes': [models.Index(fields=['nguoi_theo', '-created_at'], name='theo_user_cua_toi'), models.Index(fields=['nguoi_duoc_theo'], name='theo_user_nguoi_duoc')],
                'constraints': [models.UniqueConstraint(fields=('nguoi_theo', 'nguoi_duoc_theo'), name='theo_user_duy_nhat'), models.CheckConstraint(condition=models.Q(('nguoi_theo', models.F('nguoi_duoc_theo')), _negated=True), name='theo_user_khong_tu_theo')],
            },
        ),
    ]
