# Generated by Django 5.2.17 on 2026-08-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_theouser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='ly_do',
            field=models.CharField(choices=[('phim_hang', 'Hô hào mua bán / phím hàng'), ('cam_ket_loi_nhuan', 'Cam kết lợi nhuận, hứa mức lãi'), ('lua_dao', 'Mời uỷ thác, room VIP trả phí, lừa đảo'), ('link_nhom_kin', 'Link nhóm kín (Zalo, Telegram, group riêng)'), ('spam', 'Spam, lôi kéo, đăng lặp'), ('khac', 'Khác')], max_length=24),
        ),
    ]
