# Generated by Django 5.2.17 on 2026-08-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_report_ly_do'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body_dinh_dang',
            field=models.CharField(default='markdown', max_length=8),
        ),
    ]
