# Generated by Django 5.2.17 on 2026-08-27 02:54

"""Bộ reaction: thêm `hay_lam`, và `lieu` đổi nhãn `🔥 liều` → `⚠️ rủi ro`.

**Không đụng một byte dữ liệu nào.** `choices` là metadata cấp Django, không phải ràng
buộc cấp Postgres — `AlterField` ở đây chỉ ghi lại state, cột `varchar(8)` giữ nguyên. Đối
lập hẳn với `0017`, migration đã XOÁ sạch hàng `Reaction` khi bộ khoá đổi nghĩa; lần này
không khoá cũ nào mất nghĩa nên không có gì phải dọn.

Hàng `emoji = 'lieu'` đã có vẫn hợp lệ và vẫn đếm đúng — chúng chỉ hiện ra dưới một cái
tên khác. Đó là chủ đích: xem ghi chú "khoá GIỮ NGUYÊN dù nhãn đổi" ở
`core/models/tuong_tac.py::Reaction`.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_comment_body_dinh_dang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='emoji',
            field=models.CharField(choices=[('ro_rang', '🧠 luận điểm rõ'), ('co_nguon', '📎 có dẫn nguồn'), ('can_them', '❓ cần thêm dữ kiện'), ('lieu', '⚠️ rủi ro'), ('hay_lam', '🔥 hay lắm')], max_length=8),
        ),
    ]
