# Generated by Django 5.2.17 on 2026-08-27 06:16

"""Đảo thứ tự bộ reaction: `hay_lam` lên đầu (user chốt 2026-08-27).

**Không đụng một byte dữ liệu**, và lần này còn ít hơn `0021`: `0021` ít ra có thêm một
khoá mới; ở đây **tập khoá y nguyên**, chỉ đổi THỨ TỰ liệt kê. Django coi thứ tự `choices`
là một phần state của field nên vẫn sinh `AlterField` — đó là toàn bộ nội dung migration
này.

Vì sao vẫn phải có nó thay vì chỉ đảo ở frontend: thứ tự khai trong `Reaction.Emoji` là
NGUỒN mà `apps/web/e2e/don-vi/ban-sao-python.spec.ts` đọc để ghim thứ tự năm cái nút. Đảo
một đầu thôi là hàng rào đỏ.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_reaction_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='emoji',
            field=models.CharField(choices=[('hay_lam', '🔥 hay lắm'), ('ro_rang', '🧠 luận điểm rõ'), ('co_nguon', '📎 có dẫn nguồn'), ('can_them', '❓ cần thêm dữ kiện'), ('lieu', '⚠️ rủi ro')], max_length=8),
        ),
    ]
