# Generated by Django 5.2.17 on 2026-08-28 05:59

"""Thống kê lượt xem: hai bảng MỚI, không đụng bảng nào đang có.

`CreateModel` thuần — không `AddField`, không `AlterField`, không data migration. Chiều
ngược (`migrate core 0022`) chỉ là `DROP TABLE` hai bảng ấy, nên nó chạy được và không
làm hỏng gì của phần còn lại; cái mất khi lùi là **dữ liệu thống kê**, và chỉ nó.

⚠ `TongNgay` giữ MÃI (`LuotXem` chỉ giữ 90 ngày — xem `core/models/luot_xem.py`), nên
lùi migration này trên một môi trường đã chạy thật là mất vĩnh viễn phần tổng đã gộp:
không có nguồn nào dựng lại được sau khi hàng thô đã bị `gom_luot_xem` dọn.
"""

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_reaction_emoji'),
    ]

    operations = [
        migrations.CreateModel(
            name='LuotXem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duong_dan', models.CharField(max_length=200)),
                ('luc', models.DateTimeField(default=django.utils.timezone.now)),
                ('la_bot', models.BooleanField(default=False)),
                ('ten_bot', models.CharField(blank=True, default='', max_length=40)),
            ],
            options={
                'indexes': [models.Index(fields=['luc', 'duong_dan'], name='luotxem_luc_duongdan')],
            },
        ),
        migrations.CreateModel(
            name='TongNgay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateField(db_index=True)),
                ('duong_dan', models.CharField(max_length=200)),
                ('so_luot_nguoi', models.PositiveIntegerField(default=0)),
                ('so_luot_bot', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ngay', 'duong_dan'), name='tongngay_ngay_duongdan')],
            },
        ),
    ]
