# Generated by Django 5.2.17 on 2026-08-30 04:42

"""Khách/ngày · nguồn · trình duyệt/thiết bị — **thuần additive**, không data migration.

Bốn `AddField` đều có `default=''` nên hàng cũ điền được ngay, không khoá bảng lâu và
không cần backfill. **Backfill là bất khả thi theo thiết kế**: UA và IP của những lượt
xem cũ chưa bao giờ được lưu, nên `""` ở đây nghĩa đúng là *"không đo được"* — và phía
đọc phân biệt nó với 0 (`KhachNgay` vắng mặt ⇒ ô biểu đồ trả `None`).

Chiều ngược (`migrate core 0023`) chạy được: `DROP COLUMN` bốn cột + `DROP TABLE` hai
bảng mới. Cái mất khi lùi là số khách đã gộp — `KhachNgay` giữ mãi và không dựng lại
được sau khi hàng thô đã bị dọn.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_luotxem_tongngay'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhachNgay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateField(unique=True)),
                ('so_khach', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MuoiNgay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateField(unique=True)),
                ('muoi', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='luotxem',
            name='khach',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='luotxem',
            name='nguon',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='luotxem',
            name='thiet_bi',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='luotxem',
            name='trinh_duyet',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
