# Generated by Django 5.2.17 on 2026-09-03 09:33

"""Nhắn tin riêng 1-1 — hai bảng MỚI, **thuần additive**, không data migration.

`plans/2026-09-03-nhan-tin-rieng.md`. Không cột nào được thêm vào bảng cũ và không hàng
nào được sửa, nên chạy trên prod chỉ là hai `CREATE TABLE` + ba index + hai constraint:
không khoá bảng đang có, không backfill.

**`hoi_thoai_a_truoc_b` là `CHECK (nguoi_a_id < nguoi_b_id)`** — bất biến "một cặp một
hàng" của `core/models/tin_nhan.py`. Nó chặn cả cặp đảo lẫn tự-nhắn-mình; `UNIQUE
(nguoi_a, nguoi_b)` một mình không làm được vì `(A, B)` và `(B, A)` là hai bộ khác nhau.
Bảng mới nên `CHECK` không phải kiểm hàng cũ nào — thêm nó sau, khi đã có dữ liệu, sẽ là
một lượt quét toàn bảng dưới `ACCESS EXCLUSIVE`.

Chiều ngược (`migrate core 0024`) chạy được: `DROP TABLE` hai bảng. Cái mất khi lùi là
toàn bộ tin nhắn — không dựng lại được từ đâu, vì không nguồn nào khác giữ chúng.
"""

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_khachngay_muoingay_luotxem_khach_luotxem_nguon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoiThoai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('cap_nhat_luc', models.DateTimeField(default=django.utils.timezone.now)),
                ('da_doc_den_a', models.BigIntegerField(default=0)),
                ('da_doc_den_b', models.BigIntegerField(default=0)),
                ('nguoi_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hoi_thoai_a', to=settings.AUTH_USER_MODEL)),
                ('nguoi_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hoi_thoai_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'hội thoại',
                'verbose_name_plural': 'hội thoại',
            },
        ),
        migrations.CreateModel(
            name='TinNhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('hoi_thoai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tin_nhan', to='core.hoithoai')),
                ('nguoi_gui', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tin_da_gui', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tin nhắn',
                'verbose_name_plural': 'tin nhắn',
            },
        ),
        migrations.AddIndex(
            model_name='hoithoai',
            index=models.Index(fields=['nguoi_a', '-cap_nhat_luc'], name='hoi_thoai_cua_a'),
        ),
        migrations.AddIndex(
            model_name='hoithoai',
            index=models.Index(fields=['nguoi_b', '-cap_nhat_luc'], name='hoi_thoai_cua_b'),
        ),
        migrations.AddConstraint(
            model_name='hoithoai',
            constraint=models.UniqueConstraint(fields=('nguoi_a', 'nguoi_b'), name='hoi_thoai_duy_nhat_cap'),
        ),
        migrations.AddConstraint(
            model_name='hoithoai',
            constraint=models.CheckConstraint(condition=models.Q(('nguoi_a__lt', models.F('nguoi_b'))), name='hoi_thoai_a_truoc_b'),
        ),
        migrations.AddIndex(
            model_name='tinnhan',
            index=models.Index(fields=['hoi_thoai', '-id'], name='tin_nhan_hoi_thoai_id'),
        ),
    ]
