# Generated by Django 5.2.17 on 2026-09-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_khachngay_muoingay_luotxem_khach_luotxem_nguon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='luotxem',
            name='da_dang_nhap',
            field=models.BooleanField(default=False),
        ),
    ]
