# Generated by Django 5.2.17 on 2026-09-05 03:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_mach_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moc',
            name='body',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(50000)]),
        ),
    ]
