# Generated by Django 5.2.17 on 2026-09-05 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_moc_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='CauHinhBienTap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phut_tu_sua_moc', models.PositiveIntegerField(default=60)),
            ],
            options={
                'verbose_name': 'cấu hình biên tập',
            },
        ),
        migrations.AddField(
            model_name='moc',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mocs_da_sua', to=settings.AUTH_USER_MODEL),
        ),
    ]
