# Generated by Django 5.2.17 on 2026-09-08 07:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_sub_thu_tu'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mach',
            name='mach_open_last_entry',
        ),
        migrations.AddField(
            model_name='mach',
            name='last_content_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mach',
            name='last_discussion_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='mach',
            index=models.Index(fields=['-last_content_at'], name='mach_last_content_desc'),
        ),
        migrations.AddIndex(
            model_name='mach',
            index=models.Index(fields=['sub', '-last_content_at'], name='mach_sub_last_content'),
        ),
        migrations.AddIndex(
            model_name='mach',
            index=models.Index(condition=models.Q(('status', 'open')), fields=['-last_discussion_at'], name='mach_open_last_disc'),
        ),
        migrations.AddIndex(
            model_name='mach',
            index=models.Index(fields=['sub', '-last_discussion_at'], name='mach_sub_last_disc'),
        ),
    ]
