# Generated by Django 5.2.17 on 2026-09-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_backfill_mach_last_content_and_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mach',
            name='bai_hoc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mach',
            name='rieng_tu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mach',
            name='truong_phai',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
