# Generated by Django 5.2.17 on 2026-09-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_trading_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='mach',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
