# Generated by Django 5.2.17 on 2026-09-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_mach_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='luotxem',
            name='quoc_gia',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
