# Generated by Django 5.2.17 on 2026-09-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_luotxem_quoc_gia'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='so_lan_doi_ten',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
