# Generated by Django 5.2.17 on 2026-09-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_user_so_lan_doi_ten'),
    ]

    operations = [
        migrations.AddField(
            model_name='cauhinhbientap',
            name='phut_tu_sua_binh_luan',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
