# Generated by Django 5.2.17 on 2026-09-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_cauhinhbientap_phut_tu_sua_binh_luan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='emoji',
            field=models.CharField(choices=[('hay_lam', '🔥 hay lắm'), ('lieu', '⚠️ rủi ro'), ('can_them', '❓ cần thêm dữ kiện')], max_length=8),
        ),
    ]
