# Generated by Django 5.2.17 on 2026-09-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_reaction_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='luotxem',
            name='tu_khoa',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
