# Generated by Django 5.2.17 on 2026-09-24 05:20

from django.db import migrations, models


def cap_nhat_slug_mach(apps, schema_editor):
    from django.utils.text import slugify
    BANG_DOI_D = str.maketrans({"Đ": "D", "đ": "d"})
    Mach = apps.get_model('core', 'Mach')
    for m in Mach.objects.all():
        slug = slugify(m.title.translate(BANG_DOI_D), allow_unicode=False)
        if len(slug) <= 160:
            moi = slug
        else:
            cat = slug[:160]
            if "-" in cat:
                cat = cat.rsplit("-", 1)[0]
            moi = cat.rstrip("-")
        if m.slug != moi:
            m.slug = moi
            m.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_luotxem_tu_khoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mach',
            name='slug',
            field=models.SlugField(blank=True, db_index=False, max_length=160),
        ),
        migrations.RunPython(cap_nhat_slug_mach, migrations.RunPython.noop),
    ]
